[package]
name = "spenso-macros"
version = "0.3.2"
edition.workspace = true
description = "Procedural macros for the spenso tensor library"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { workspace = true }
symbolica = { workspace = true, default-features = false, optional = true }
syn = { version = "2.0", features = ["extra-traits", "full"] }

[dev-dependencies]
linnet = { workspace = true, features = ["native", "nodestore-vec", "serde"] }
spenso = { workspace = true, features = ["native"] }

[features]
default = ["native"]
native = ["symbolica?/integer-gmp", "symbolica?/float-mpfr"]
shadowing = ["dep:symbolica"]
wasm = ["symbolica?/wasm"]
