#:schema https://raw.githubusercontent.com/alphal00p/gammaloop/refs/heads/main/assets/schemas/runtime.json
[kinematics.externals]
type = "constant"

[kinematics.externals.data]
momenta = [
    [
    1.0,
    0.0,
    0.0,
    0.0,
],
    [
    0.5,
    0.0,
    0.0,
    -0.5,
],
    "dependent",
]
helicities = [
    0,
    0,
    0,
]

[integrator]
n_start = 240000
n_increase = 0
n_max = 240000
target_relative_accuracy = 0.00001
seed = 1337
