[cli_settings]

[cli_settings.state]
folder = "./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564"
name = "NNLO_manual_GL564"

[[command_blocks]]
name = "setup"
commands = [
  "import model sm-default.json",
  "set model MT=173.0",
  "set model MH=125.0",
  "set model WT=0.0",
  "set model ymt=173.0",
  "set model aS=0.118",
  "set model aEWM1=132.507",
  "set model Gf=1.166390e-05",
  "set model MZ=91.188",
  "remove processes",
  "import graphs ./examples/cli/epem_a_ttxh/NNLO_manual/graphs/GL564.dot --process-spec 'e+ e- > t t~ h | e+ e- g t t~ h d d~ ghG ghG~ a QCD^2==4 QED^2==6 [{{4}} QCD=2]' -p epem_a_tth -i NNLO -o",
]

[[command_blocks]]
name = "generate_full"
commands = [
  "run setup",
  "set global kv global.generation.uv.generate_integrated=true",
  "generate existing -p epem_a_tth -i NNLO",
  "save state -o",
]

[[command_blocks]]
name = "generate_local_only"
commands = [
  "run setup",
  "set global kv global.generation.uv.generate_integrated=false",
  "generate existing -p epem_a_tth -i NNLO",
  "save state -o",
]

[[command_blocks]]
name = "display_generation"
commands = ["display integrand --process epem_a_tth --integrand-name NNLO --category generation"]

[[command_blocks]]
name = "display_structure"
commands = ["display integrand --process epem_a_tth --integrand-name NNLO --category orientation cuts --show-threshold-functions"]

[[command_blocks]]
name = "runtime_approach"
commands = ["set process -p epem_a_tth -i NNLO kv general.evaluator_method=SingleParametric general.generate_events=true general.store_additional_weights_in_event=true subtraction.disable_threshold_subtraction=false"]

[[command_blocks]]
name = "runtime_approach_threshold_off"
commands = ["set process -p epem_a_tth -i NNLO kv general.evaluator_method=SingleParametric general.generate_events=true general.store_additional_weights_in_event=true subtraction.disable_threshold_subtraction=true"]

# q12=-K0-K3+K1+K2 and q14=-K3+K1 in spatial momentum.
[[command_blocks]]
name = "approach_soft_e12"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,-91,64,83,31,-47,59,-134,69,5
  --approach-axis 0,0,0,0,0,0,0,0,0,211,-157,193
  --axis-label 'e12 soft' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_soft_e12.json"""]

[[command_blocks]]
name = "approach_soft_e14"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,-91,64,83,31,-47,59,-91,64,83
  --approach-axis 0,0,0,0,0,0,0,0,0,211,-157,193
  --axis-label 'e14 soft' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_soft_e14.json"""]

[[command_blocks]]
name = "approach_double_soft"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 31,-47,59,-91,64,83,31,-47,59,-91,64,83
  --approach-axis 113,-71,-149,0,0,0,0,0,0,211,-157,193
  --axis-label 'independent e12/e14 double soft' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_double_soft.json"""]

[[command_blocks]]
name = "approach_corr_e12_E26_E30_E36_E49"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,121,-77,63,-47,25,543.1172561311298,0,0,469.11725613112975
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E26/E30/E36/E49' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E26_E30_E36_E49.json"""]

[[command_blocks]]
name = "approach_corr_e12_E35_E60"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,121,-77,63,-121,77,214.48873851023217,0,0,277.48873851023217
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E35/E60' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E35_E60.json"""]

[[command_blocks]]
name = "approach_corr_e12_E62"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,0,0,277.48873851023217,0,0,-277.48873851023217,0,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E62' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E62.json"""]

[[command_blocks]]
name = "approach_corr_e12_E68_E73"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,220.071,0,0,-366.142,-52,137,-220.071,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E68/E73' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E68_E73.json"""]

[[command_blocks]]
name = "approach_corr_e14_E26_E68"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,0,0,469.11725613112975,31,-47,59,0,0,469.11725613112975
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e14 soft; E26/E68' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e14_E26_E68.json"""]

[[command_blocks]]
name = "approach_corr_e14_E30"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 152,-124,-347.11725613112975,121,-77,63,31,-47,59,121,-77,63
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e14 soft; E30' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e14_E30.json"""]

[[command_blocks]]
name = "approach_corr_e14_E35_E60"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,277.48873851023217,0,0,0,0,0,0,0,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e14 soft; E35/E60' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e14_E35_E60.json"""]

[[command_blocks]]
name = "approach_corr_e14_E36_E49_E73"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,0,0,0,0,0,395.4050785973398,0,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e14 soft; E36/E49/E73' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e14_E36_E49_E73.json"""]

[[command_blocks]]
name = "approach_corr_e14_E62"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,0,0,0,0,0,277.48873851023217,0,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e14 soft; E62' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e14_E62.json"""]

[[command_blocks]]
name = "approach_corr_double_ordinary"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 74,-52,137,0,0,469.11725613112975,74,-52,137,0,0,469.11725613112975
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'double soft; E26/E30/E36/E49/E68/E73' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_double_ordinary.json"""]

[[command_blocks]]
name = "approach_corr_double_four_top"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,0,0,277.48873851023217,0,0,0,0,0,277.48873851023217
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'double soft; E35/E60/E62' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_double_four_top.json"""]

[[command_blocks]]
name = "all_approaches"
commands = [
  "run approach_soft_e12", "run approach_soft_e14", "run approach_double_soft",
  "run approach_corr_e12_E26_E30_E36_E49", "run approach_corr_e12_E35_E60", "run approach_corr_e12_E62", "run approach_corr_e12_E68_E73",
  "run approach_corr_e14_E26_E68", "run approach_corr_e14_E30", "run approach_corr_e14_E35_E60", "run approach_corr_e14_E36_E49_E73", "run approach_corr_e14_E62",
  "run approach_corr_double_ordinary", "run approach_corr_double_four_top",
]

[[command_blocks]]
name = "approach_corr_e12_E35_E60_threshold_off"
commands = ["run runtime_approach_threshold_off", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,121,-77,63,-121,77,214.48873851023217,0,0,277.48873851023217
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E35/E60 threshold-off diagnostic' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E35_E60_threshold_off.json"""]

[[command_blocks]]
name = "approach_corr_e12_E62_threshold_off"
commands = ["run runtime_approach_threshold_off", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,0,0,277.48873851023217,0,0,-277.48873851023217,0,0,0
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E62 threshold-off diagnostic' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E62_threshold_off.json"""]

[[command_blocks]]
name = "threshold_off_diagnostics"
commands = ["run approach_corr_e12_E35_E60_threshold_off", "run approach_corr_e12_E62_threshold_off"]

[[command_blocks]]
name = "approach_corr_e12_E35_E60_arb"
commands = ["run runtime_approach", """approach -p epem_a_tth -i NNLO --momentum-space --graph-id 0
  --point 0,0,0,121,-77,63,-121,77,214.48873851023217,0,0,277.48873851023217
  --approach-axis 19,-23,41,47,29,-31,31,-17,47,211,-157,193
  --axis-label 'e12 soft; E35/E60 Arb diagnostic' --parameter-name lambda --n-points 50 --logarithmic --min-abs-t 1e-6 --max-abs-t 1e-2 --skip-midpoint --n-cores 3 --use_arb_prec
  --output-results ./examples/cli/epem_a_ttxh/NNLO_manual/states/state_GL564/approach_corr_e12_E35_E60_arb.json"""]

[[command_blocks]]
name = "integrate"
commands = [
  """set process -p epem_a_tth -i NNLO string '
    [integrator]
    n_start = 100
    n_increase = 0
    n_max = 10000000000
    seed = 1337

    [sampling]
    graphs = "monte_carlo"
    orientations = "summed"
    lmb_multichanneling = true
    lmb_channels = "monte_carlo"
    lmb_channel_weight = "ose"

    [stability]
    escalate_if_exact_zero = false
    loop_momenta_norm_escalation_factor = -1.0
    rotation_axis = [{ type = "z" }]

    [[stability.levels]]
    precision = "Double"
    required_precision_for_re = 1.0e-5
    required_precision_for_im = 1.0e-5
    escalate_for_large_weight_threshold = 1.0e99
    '""",
  """integrate -p epem_a_tth -i NNLO --n-cores 3
      --renderer tabled --batch-size 10 --show-phase both
      --show-max-weight-info --show-top-discrete-grid
      --show-discrete-contributions-sum --write-results-for-each-iteration
      --restart""",
]

[default_runtime_settings.general]
evaluator_method = "SingleParametric"
enable_cache = false
generate_events = true
store_additional_weights_in_event = true
integral_unit = "picobarn"
mu_r = 91.188
m_uv = 91.188

[default_runtime_settings.kinematics]
e_cm = 1000.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [[500.0, 0.0, 0.0, 500.0], [500.0, 0.0, 0.0, -500.0]]
helicities = ["summed_averaged", "summed_averaged"]

[default_runtime_settings.subtraction]
disable_threshold_subtraction = false
esurface_existence_threshold = 1.0e-7

[default_runtime_settings.integrator]
n_start = 100
n_increase = 0
n_max = 10000000000
seed = 1337

[default_runtime_settings.integrator.observables_output]
format = ["hwu", "json"]

[default_runtime_settings.sampling]
graphs = "monte_carlo"
orientations = "summed"
lmb_multichanneling = true
lmb_channels = "monte_carlo"
lmb_channel_weight = "ose"

[default_runtime_settings.stability]
escalate_if_exact_zero = false
loop_momenta_norm_escalation_factor = -1.0

[[default_runtime_settings.stability.rotation_axis]]
type = "z"

[[default_runtime_settings.stability.levels]]
precision = "Double"
required_precision_for_re = 1.0e-5
required_precision_for_im = 1.0e-5
escalate_for_large_weight_threshold = 1.0e99

[cli_settings.global.generation.evaluator]
do_algebra = false
iterative_orientation_optimization = false
store_atom = true
compile = false
summed = false
summed_function_map = false

[cli_settings.global.generation.threshold_subtraction]
enable_thresholds = true
check_esurface_at_generation = true
esurface_existence_threshold = 1.0e-7
skip_thresholds_that_are_cuts = true

[cli_settings.global.generation.uv]
softct = true
inner_products = true
generate_integrated = true
subtract_uv = true

[cli_settings.global.n_cores]
feyngen = 1
generate = 4
compile = 0
integrate = 3

[cli_settings.global.generation.tropical_subgraph_table]
panic_on_fail = true
disable_tropical_generation = false
