use std::{
    fmt::{Display, Formatter},
    ops::{Deref, DerefMut},
};

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    bincode_trait_derive::Encode,
    bincode_trait_derive::Decode,
)]
pub struct Autogen<T> {
    pub value: T,
    pub autogenerated: bool,
}

impl<T> Autogen<T> {
    pub fn explicit(value: T) -> Self {
        Self {
            value,
            autogenerated: false,
        }
    }

    pub fn generated(value: T) -> Self {
        Self {
            value,
            autogenerated: true,
        }
    }

    pub fn option(self) -> Option<T> {
        if self.autogenerated {
            None
        } else {
            Some(self.value)
        }
    }

    pub fn option_with_generated(self, include_autogenerated: bool) -> Option<T> {
        if include_autogenerated || !self.autogenerated {
            Some(self.value)
        } else {
            None
        }
    }

    pub fn from_option_or_generate(value: Option<T>, generate: impl FnOnce() -> T) -> Self {
        match value {
            Some(value) => Self::explicit(value),
            None => Self::generated(generate()),
        }
    }
}

impl<T> Deref for Autogen<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.value
    }
}

impl<T> DerefMut for Autogen<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.value
    }
}

impl<T: Display> Display for Autogen<T> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        Display::fmt(&self.value, f)
    }
}

#[cfg(test)]
mod tests {
    use super::Autogen;

    #[test]
    fn explicit_marks_value_as_non_autogenerated() {
        let value = Autogen::explicit(3);
        assert_eq!(value.value, 3);
        assert!(!value.autogenerated);
        assert_eq!(*value, 3);
    }

    #[test]
    fn generated_marks_value_as_autogenerated() {
        let value = Autogen::from_option_or_generate(None, || 7);
        assert_eq!(value.value, 7);
        assert!(value.autogenerated);
    }
}
