use itertools::Itertools;
use linnet::{
    half_edge::{HedgeGraph, NodeIndex, nodestore::BitVecNeighborIter},
    parser::DotVertexData,
};

use symbolica::atom::Atom;

use crate::{
    GammaLoopContext,
    model::{Model, ModelGammaLoopExt, ParticleId, ParticleIdGammaLoopExt, VertexRuleId},
};
use color_eyre::Result;
use eyre::{Context, eyre};
use feynkit_graph::VertexId as FeynkitVertexId;

use super::{
    Autogen,
    edge::ParseEdge,
    global::ParseData,
    hedge_data::ParseHedgeData,
    parse::{StripParse, ToQuoted, extract_oriented_particles_from_vertex_hedges},
};

#[derive(Debug, Clone, bincode_trait_derive::Encode, bincode_trait_derive::Decode)]
#[trait_decode(trait = GammaLoopContext)]
pub struct Vertex {
    // #[bincode(with_serde)]
    pub name: Autogen<String>,
    pub vertex_rule: Option<VertexRuleId>,
    pub num: Autogen<Atom>,
    // pub num_spin: ParamTensor<OrderedStructure<Euclidean, Aind>>,
    // pub num_color: ParamTensor<OrderedStructure<Euclidean, Aind>>,
    pub dod: Autogen<i32>,
}

impl Vertex {
    pub(crate) fn get_num(&self) -> Atom {
        self.num.value.clone() //.kill_color()
    }

    pub(crate) fn to_dot_data(&self, include_autogenerated_fields: bool) -> DotVertexData {
        let mut v = DotVertexData::empty();
        if include_autogenerated_fields || !self.name.autogenerated {
            v.name = Some(self.name.value.clone());
        }
        if let Some(vertex_rule) = self.vertex_rule {
            v.add_statement("vertex_rule_id", vertex_rule.index());
        }
        if include_autogenerated_fields || !self.dod.autogenerated {
            v.add_statement("dod", self.dod.value);
        }
        if include_autogenerated_fields || !self.num.autogenerated {
            v.add_statement("num", self.num.value.to_quoted());
        }
        if include_autogenerated_fields {
            if self.name.autogenerated {
                v.add_statement("name_autogen", true);
            }
            if self.dod.autogenerated {
                v.add_statement("dod_autogen", true);
            }
            if self.num.autogenerated {
                v.add_statement("num_autogen", true);
            }
        }
        v
    }
}

impl From<&Vertex> for DotVertexData {
    fn from(value: &Vertex) -> Self {
        value.to_dot_data(false)
    }
}
impl Vertex {}

#[derive(Debug, Clone)]
pub struct ParseVertex {
    pub name: Option<String>,
    /// Transient identity used only by the finalized FeynKit runtime bridge.
    /// It is deliberately not serialized into runtime DOT artifacts.
    pub(crate) feynkit_id: Option<FeynkitVertexId>,
    // pub strict: bool,
    pub vertex_rule: Option<VertexRuleId>,
    pub num: Option<Atom>,
    pub dod: Option<i32>,
}

impl From<&ParseVertex> for DotVertexData {
    fn from(value: &ParseVertex) -> Self {
        let mut v = DotVertexData::empty();
        if let Some(name) = &value.name {
            v.name = Some(name.clone());
        }
        if let Some(vertex_rule) = value.vertex_rule {
            v.add_statement("vertex_rule_id", vertex_rule.index());
        }
        if let Some(dod) = value.dod {
            v.add_statement("dod", dod);
        }
        if let Some(num) = &value.num {
            v.add_statement("num", num.to_quoted());
        }
        v
    }
}

impl ParseVertex {
    pub fn with_num(mut self, num: Atom) -> Self {
        self.num = Some(num);
        self
    }

    pub fn with_label(mut self, label: String) -> Self {
        self.name = Some(label);
        self
    }
}

impl From<VertexRuleId> for ParseVertex {
    fn from(vertex_rule: VertexRuleId) -> Self {
        ParseVertex {
            name: None,
            feynkit_id: None,
            // strict: false,
            vertex_rule: Some(vertex_rule),
            dod: None,
            num: None,
        }
    }
}

pub trait ParticleEdge {
    fn particle(&self) -> Option<ParticleId>;
    fn is_dummy(&self) -> bool;
}

impl ParseVertex {
    pub(crate) fn parse<'a>(
        model: &'a Model,
        parse_data: &'a ParseData,
    ) -> impl FnMut(
        &'a HedgeGraph<ParseEdge, &'a DotVertexData, ParseHedgeData>,
        BitVecNeighborIter<'a>,
        &'a &'a DotVertexData,
    ) -> Result<Self> {
        move |g, n, v| {
            let name = v.name().map(|id| id.to_string());

            let dod = v
                .get::<_, String>("dod")
                .transpose()
                .with_context(|| "Error parsing vertex dod".to_string())?
                .map(|a| a.strip_parse())
                .transpose()?;

            if let Some(num) = v.get::<_, String>("num") {
                let num = num?;
                Ok(ParseVertex {
                    dod,
                    name,
                    feynkit_id: None,
                    vertex_rule: None,
                    num: Some(num.strip_parse().with_context(|| {
                        format!(
                            "Error parsing vertex num {num} of graph {}",
                            parse_data.name
                        )
                    })?),
                })
            } else if let Some(id) = v.get::<_, usize>("vertex_rule_id") {
                let vertex_rule = Some(
                    model
                        .vertex_rule_id_at(id?)
                        .with_context(|| "Error parsing vertex-rule ID".to_string())?,
                );

                Ok(ParseVertex {
                    dod,
                    name,
                    feynkit_id: None,
                    vertex_rule,
                    num: None,
                })
            } else if let Some(n) = v.get::<_, String>("int_id") {
                let vertex_rule = Some(model.get_vertex_rule(n?));

                Ok(ParseVertex {
                    dod,
                    name,
                    feynkit_id: None,
                    vertex_rule,
                    num: None,
                })
            } else {
                let node_id = n
                    .clone()
                    .next()
                    .map(|h| g.node_id(h))
                    .unwrap_or(NodeIndex(0));
                let mut particles = extract_oriented_particles_from_vertex_hedges(g, n, model);
                particles.sort_unstable();

                let rules = model.vertex_rules_for_particles(&particles);
                if !rules.is_empty() {
                    if rules.len() == 1 {
                        Ok(ParseVertex {
                            dod,
                            name,
                            feynkit_id: None,
                            vertex_rule: Some(rules[0]),
                            num: None,
                        })
                    } else {
                        Err(eyre!("Multiple vertex rules for {:?}", particles))
                    }
                } else {
                    let particles = particles
                        .iter()
                        .map(|particle| particle.resolve(model).name.as_str())
                        .collect_vec();
                    Err(eyre!(
                        "Failed to find vertex rule for particles: {:?} for node {node_id} in graph {}",
                        particles,
                        parse_data.name,
                    ))
                }
            }
        }
    }
}
