try_strings = true
override_state = false

[state]
folder = "./examples/cli/epem_a_ttxh/NLO/state"
name = ""

[global]
logfile_directive = "off"
display_directive = "info"

[global.log_style]
log_format = "Long"
short_timestamp = false
full_line_source = false
include_fields = false

[global.generation]
vector_polarization_sum_gauge = "LightLikeAxial"
force_cuts = []
override_lmb_heuristics = false

[global.generation.evaluator]
do_algebra = false
iterative_orientation_optimization = false
summed = false
summed_function_map = false
compile = true
store_atom = true
do_fn_map_replacements = false
horner_iterations = 10
n_cores = 1
abort_level = 0
max_horner_scheme_variables = 500
max_common_pair_cache_entries = 1000000
max_common_pair_distance = 1000
verbose = false

[global.generation.feyngen]
gamma_simplification_closure_check = false

[global.generation.orientation_pattern]

[global.generation.compile]
compilation_mode = "assembly"
optimization_level = "O3"
fast_math = true
unsafe_math = true
compiler = "clang++"
custom = []

[global.generation.tropical_subgraph_table]
panic_on_fail = true
target_omega = 1.0
disable_tropical_generation = false

[global.generation.threshold_subtraction]
enable_thresholds = false
check_esurface_at_generation = true
skip_thresholds_that_are_cuts = true
disable_integrated_ct = false
assume_positive_external_energies = true

[global.generation.uv]
softct = false
generate_integrated = false
subtract_uv = true
only_integrated = false
pole_part = false
add_sigma = false
keep_sigma = true
inner_products = true
use_legacy = true
cached = true
renormalization_schemes = []

[global.generation.uv.vakint]
form_exe_path = "form"
python_exe_path = "python3"
evaluation_methods = [
    "alphaloop",
    "matad",
    "fmft",
]
run_time_decimal_precision = 100
clean_tmp_dir = true
normalization = "MSbar"
additional_normalization = "1"

[global.generation.uv.vakint.matad]
expand_masters = true
susbstitute_masters = true
substitute_hpls = true
direct_numerical_substition = true

[global.generation.uv.vakint.alphaloop]
susbstitute_masters = true

[global.generation.uv.vakint.fmft]
expand_masters = true
susbstitute_masters = true

[global.generation.uv.vakint.pysecdec]
quiet = true
relative_precision = 0.0000001
min_n_evals = 10000
max_n_evals = 1000000000000

[global.n_cores]
feyngen = 10
generate = 10
compile = 10
integrate = 10
