# Generated by just ci-update from nix/ci.nix and nix/ci-workspace-graph.json.
{
  dependencies = {
    "checks.x86_64-linux.gammaloop-clippy" = [
      "packages.x86_64-linux.cargoArtifacts"
    ];
    "packages.x86_64-linux.cargoArtifacts" = [
      "packages.x86_64-linux.crate-deps-gammaloop-workspace-hack"
    ];
    "packages.x86_64-linux.ci-test-inputs" = [
      "packages.x86_64-linux.cargoArtifacts"
      "packages.x86_64-linux.crate-deps-gammaloop-workspace-hack"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-doctest" = [
      "packages.x86_64-linux.cargoArtifacts"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-clinnet" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-core" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-feynkit" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-integration" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-linnet" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-python-api" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-spenso" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-vakint" = [
      "packages.x86_64-linux.ci-test-inputs"
    ];
  };
  dependency-discovery = {
    enable = false;
  };
  deploy = {
    ci-passed = {
      branches = "all";
      package = "packages.x86_64-linux.nix-ci-passed";
      system = "x86_64-linux";
    };
  };
  fail-fast = false;
  fail-on-dangling-dependencies = true;
  onlyBuild = [
    "checks.x86_64-linux.gammaloop-clippy"
    "checks.x86_64-linux.gammaloop-fmt"
    "checks.x86_64-linux.gammaloop-guppy-workspace-graph"
    "packages.x86_64-linux.cargoArtifacts"
    "packages.x86_64-linux.ci-test-inputs"
    "packages.x86_64-linux.crate-deps-gammaloop-workspace-hack"
    "packages.x86_64-linux.nix-ci-check-gammaloop-doctest"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-clinnet"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-core"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-feynkit"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-integration"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-linnet"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-python-api"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-spenso"
    "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-vakint"
    "packages.x86_64-linux.nix-ci-passed"
  ];
  systems = [
    "x86_64-linux"
  ];
  test = {
    gammaloop-doctest = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-doctest";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-clinnet = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-clinnet";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-core = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-core";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-feynkit = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-feynkit";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-integration = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-integration";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-linnet = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-linnet";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-python-api = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-python-api";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-spenso = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-spenso";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
    gammaloop-nextest-vakint = {
      in-repo = true;
      package = "packages.x86_64-linux.nix-ci-check-gammaloop-nextest-vakint";
      secrets = [
        "SYMBOLICA_LICENSE"
      ];
      system = "x86_64-linux";
    };
  };
}
