commands = [
  "import model sm",
  "import graphs tests/resources/graphs/uv_tests/ad_ad_1L_gluon.dot ",
  "generate",
  "profile  ultra-violet ",
]

[cli_settings.global]
display_directive = "info,gammalooprs[{#uv}]=debug,gammalooprs[{#span_context}]=debug"
logfile_directive = "gammalooprs[{#uv}]=debug"

[cli_settings.global.generation.uv]
generate_integrated = true
add_sigma = true

[cli_settings.global.generation.threshold_subtraction]
enable_thresholds = true

[cli_settings.global.log_style]
include_fields = true
full_line_source = true
log_format = "Full"
short_timestamp = true

[default_runtime_settings.subtraction]
disable_threshold_subtraction = false

[default_runtime_settings.kinematics]
e_cm = 300.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
  [500.0, 0.0, 500.0, 0.0],
  [500.0, 0.0, 0.0, -500.0],
  [500.0, 300.0, 200.0, 346.4101615],
  "dependent"
]
# helicities = [+1, -1, +1, -1]  # gives zero
helicities = [+1, +1, -1, -1]

[default_runtime_settings.general]
additional_param_values = [1.0, 1.0]
