[package]
name = "symbolica-expansion-mre"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
symbolica = { git = "https://github.com/symbolica-dev/symbolica", rev = "06906976bca24fefc5203aee699d90d62ebe08cd", default-features = false, features = ["bincode", "float-mpfr", "integer-gmp", "native_code_generation", "serde"] }

[profile.release]
opt-level = 2
debug = 2
lto = false

[profile.release.package."*"]
opt-level = 3

[[bin]]
name = "expansion"
path = "expansion.rs"

[[bin]]
name = "polynomial_emission"
path = "polynomial_emission.rs"
