= Retained maxima after the repaired confirmation
<retained-maxima-after-the-repaired-confirmation>
Prepared protocol only. The interrupted build5 confirmation is incomplete and must not supply a pooled confirmation estimate or a complete five-seed maximum ranking. Its exact failed Sample and all successful/failed rows remain separate evidence.

Use the unchanged frozen choices: a=`optimized_lmb`, b=`cuts`, c=`cuts_combined_joint`; seeds 10007,20011,30013,40009,50021; N=32768 per method/seed; 20 workers; one fresh iteration. Do not select new candidates from the confirmation. The final collection must contain the actual complete Cartesian 3×5 set, with one authenticated physical program/card/state lineage and no discarded numerical failure. Any source repair requires a new execution manifest; the old build5 executable is not evidence for the repaired source.

After the final collection completes, use the existing `analyze_physics_pilots.py FINAL_MANIFEST FINAL_PILOT_DIRECTORY --workers 20 --screen screen-selection-frozen-build5.json`. Require its normal acceptance and frozen-screen authentication. Write and freeze these statistics before maximum replay, since the latter hashes the entire pilot directory. No synthetic merged state, partial-run pooling or baseline throughput-control duplication is needed.

Reuse the exact max29b source `drivers/max_replay_current.rs` (SHA256 29b9c6a48448935aee70159787063bb8a2c1cdd5b6a762ff596fd2d9061ca498), including frozen `gate-max-support.rs` b53. Root links it against the #strong[same exact completed API/core artifacts used by the final confirmation];, using the existing compile helper and `--extra-core-extern bincode`. Freeze its source, dependency and executable hashes. This needs no new runner, sampling logic or Gamma helper.

The existing invocation is `FINAL_MAX_BINARY FINAL_MANIFEST FINAL_PILOT_DIRECTORY NEW_MAX_OUTPUT_DIRECTORY`, with `RAYON_NUM_THREADS=1 GL_DISPLAY_FILTER=off`. Send its log and resource record to siblings of both input and output directories. It recovers original bincode Samples, including every phase/sign alias, from the actual final integration states. First-iteration max\_eval0 and complete Sample weights remain authoritative. It then selects two distinct largest complex norms per method #strong[among the stored signed extrema across all five seeds];, with ordinary and forced-Arb controls. These are not the unrecorded global complex-norm maxima over all draws.

Require the max summary to complete without error, preserve state/pilot hashes and pass `audit_maximum_results.py NEW_MAX_OUTPUT_DIRECTORY`. That existing audit checks report replay, all six cut events, decomposition/factors and ordinary-versus-Arb accuracy. Event and CT weights already include the outer Sample factor.

Only after these gates, compare the new maxima with the retained screen cases and use the existing metadata joins for attribution. If an unresolved dominant term needs native centers/stars, reuse the scoped `max_replay_trace.rs --trace` entry with a newly authenticated request targeting the actual final maxima; do not automatically rerun the three old screen points or add an approach scan. Any resulting trace must first match the retained forced-Arb result exactly. No additional numerical experiment is requested by this preparation.
