#!/usr/bin/env python3

from gammaloop import DotExportSettings, GammaLoopAPI
from symbolica import S, E
from symbolica.community import idenso
from pydot import graph_from_dot_data

dot_settings = DotExportSettings()
dot_settings.include_autogenerated_fields = True

gl_session = GammaLoopAPI("./dLTD_state", clean_state=True)
_ = gl_session.run("import model sm-default.json")
_ = gl_session.run("remove processes -p dLTD")

_ = gl_session.run(
    "generate amp {} > {} | g ghg b t QED==0 QCD==2 [{2}] --numerator-grouping group_identical_graphs_up_to_sign -p dLTD_2L -i 2L --only-diagrams"
)
dot_files_2L = gl_session.get_dot_files("dLTD_2L", settings=dot_settings)
dot_graphs_2L = graph_from_dot_data(dot_files_2L)
print("\n".join(graph.to_string() for graph in dot_graphs_2L))
stop

_ = gl_session.run(
    "generate amp {} > {} | g ghg b t QED==0 QCD==4 [{3}] --numerator-grouping group_identical_graphs_up_to_sign -p dLTD_3L -i 3L --only-diagrams"
)
dot_files_3L = gl_session.get_dot_files("dLTD_3L", settings=dot_settings)
dot_graphs_3L = graph_from_dot_data(dot_files_3L)
print("\n".join(graph.to_string() for graph in dot_graphs_3L))

print(dir(gl_session))
