[package]
name = "spynso3"
version = "0.1.2"
edition = "2024"
description = "Pyo3 bindings for spenso"
license = "MIT"
repository = "https://github.com/alphal00p/gammaloop"

[dependencies]
ahash = { workspace = true, features = ["serde"] }
idenso = { workspace = true, features = ["python"] }
spenso = { workspace = true, features = ["portable-payload", "python", "shadowing"] }
spenso-hep-lib = { workspace = true, default-features = false }
spenso-macros = { workspace = true }
xpct = "0.5.1"

eyre = { workspace = true }
pyo3 = { workspace = true, features = ["eyre"] }

itertools = "0.14.0"
pyo3-stub-gen = { workspace = true, default-features = false, features = ["infer_signature"], optional = true }
pyo3-stub-gen-derive = { workspace = true }
tabled = { workspace = true }
thiserror = { workspace = true }
tymbolica-atom-payload = { workspace = true }

[dependencies.symbolica]
workspace = true
default-features = false
features = ["bincode", "python_export", "serde"]

[features]
default = ["native"]
native = [
  "idenso/native",
  "pyo3/multiple-pymethods",
  "spenso/native-code-generation",
  "spenso-hep-lib/native",
  "tymbolica-atom-payload/native",
]
wasm = [
  "idenso/wasm",
  "spenso/wasm",
  "spenso-hep-lib/wasm",
  "symbolica/wasm",
  "tymbolica-atom-payload/wasm",
]
python_stubgen = [
  "dep:pyo3-stub-gen",
  "idenso/python_stubgen",
  "spenso/python_stubgen",
  "symbolica/python_stubgen",
]

# [patch.crates-io]
# pyo3-stub-gen = { git = "https://github.com/benruijl/pyo3-stub-gen", branch = "patched" }
