= Same-graph ordinary U versus soft H: source audit

This is a historical run report. Its findings and summary measurements are retained; raw logs, JSON receipts, and JUnit reports are not distributed with the source. Historical artifact names and local paths below identify the original run, not files available in this checkout.
<same-graph-ordinary-u-versus-soft-h-source-audit>
The 314 GiB failure is not explained merely by saying that a soft operator has more terms. The current direct implementation has #strong[no U/S/US forest-node triplication or residue-key Cartesian product] at the inspected boundaries. It already forms `H(X) = S(X) + U(X - S(X))`. The concrete soft-specific growth opportunity is inside each completed branch: S constructs a Taylor coefficient and U then processes the larger, potentially only partially cancelled remainder. That is a candidate boundary, not a measured cause of the large failure.

This audit is read-only. No generation, rerun, source changes, graph-numerator expansion, or new profile was performed. The bounds-panic diagnosis explains the final crash mechanism hypothesis; it does not explain why the expression grew.

== Shared inputs and first differences
<shared-inputs-and-first-differences>
For the #strong[same imported graph, model, canonical LMB, cuts, selected production keys, retained UV regions and disabled integrated terms];, change the two existing positive-degree `IR` prescriptions to `MUV`. Both prescriptions retain the same classified regions: classification removes `Unsubtracted`, while `Spinney::with_scheme` chooses its LMB independently of the scheme. The wood deduplicates by subgraph filter, and operation identity is the canonical trace key. Thus an IR→MUV-only change should preserve the wood/forest topology, apart from labels identifying the scheme. Sources: #link("../../../crates/gammalooprs/src/uv/uv_graph.rs:156")[classification];, #link("../../../crates/gammalooprs/src/uv/spinney.rs:87")[scheme-independent LMB];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:207")[wood filter deduplication];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:420")[operation identity];.

A control must change the actual `renormalization_prescription` rules. The legacy `uv.softct` field is declared/defaulted but has no production read in the repository-wide Rust search; production dispatch reads the chosen scheme. `subtract_uv=false` removes the forest and therefore cannot isolate soft H from ordinary U. Sources: #link("../../../crates/gammalooprs/src/uv/settings.rs:201")[prescription selection];, #link("../../../crates/gammalooprs/src/uv/settings.rs:459")[softct field];, #link("../../../crates/gammalooprs/src/uv/uv_graph.rs:174")[bare classification];.

Ordered direct pipeline: stored parent CFF and exact production key → component-owned numerator mapping → common `start` momentum/OSE setup → #strong[first operator difference: U versus S followed by U on X−S(X)] → same branch-owned cograph numerator mapping/normalization → materialize key selectors or replace them by one → sum forest-node final atoms → evaluator preprocessing. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/kernel.rs:338")[Kernel dispatch];, #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/kernel.rs:375")[H remainder form already implemented];, #link("../../../crates/gammalooprs/src/uv/approx/final_integrand.rs:117")[final direct assembly];.

Ordinary U performs one projection; positive-degree H performs two. Logarithmic IR (`dod==0`) directly takes the ordinary U path. There is no general constant size multiplier: nesting feeds a completed child atom into the next operation, and Taylor coefficients can increase internal algebra substantially even when the number of typed sectors/keys is unchanged. The implementation does not explicitly call `expand` on graph numerators in this direct pipeline. The `series(...).to_atom()` boundary still materializes coefficient algebra; absence of an explicit `expand` call is not a bound on its size. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/kernel.rs:719")[Projection and series];.

== Count relationships and retained work
<count-relationships-and-retained-work>
#figure(
  align(center)[#table(
    columns: 3,
    align: (auto,auto,auto,),
    table.header([Boundary], [Source-level relationship], [Consequence],),
    table.hline(),
    [Direct root], [Groups CFF contributions by existing production ID and cut index], [It sums rows for a key; no new H-specific keys are generated. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/forest.rs:142")[Root];],
    [One local Taylor step], [One output `DirectSector` per input sector; same keys pass through `fallible_map`], [U→H changes each atom, not the sector/key product. Syntactic zero keys may disappear. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/forest.rs:380")[Sector map];, #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/branches.rs:186")[key map];],
    [Sequential integrated addback], [Adds one localized sector only when the finite parent counterterm is nonzero], [Absent for this fixture. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/forest.rs:321")[Addback guard];],
    [Disconnected union replay], [A chain of d operations has d+1 integrated-prefix choices; disjoint components form the product of their choice counts, excluding the all-integrated state from local replay], [Expected prefix combinations, not a soft-specific Cartesian product. Zero prefixes retain typed sectors but remain algebraically zero; zero localization skips CFF generation. #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:977")[Replay recursion];, #link("../../../crates/gammalooprs/src/uv/approx/local_3d/integrated_localizer.rs:22")[zero handling];],
    [Branch addition], [Exact complete keys are coalesced additively; distinct source maps on the same host remain distinct], [Coalescing adds contributions rather than deduplicating equal expressions. An upstream duplicate contribution could still double its coefficient; key-count equality alone does not certify multiplicity. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/branches.rs:105")[Key coalescing];],
    [Final orientation/forest aggregation], [Linear sum over keys, then one final atom per compatible forest node; both active and final node forms remain stored], [Large atoms can be retained and copied in several representations. This is shared U/H machinery, not an identified soft bug. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/branches.rs:217")[Materialization];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:678")[stored forms];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:1384")[forest sum];],
  )]
  , kind: table
  )

The final normalizer resolves color and dot products before summing orientations, intentionally keeping numerator/CFF factors attached. Later `collect_color` sees each already materialized forest-node atom. These are secondary size boundaries to measure if the direct Taylor outputs remain small. Neither stage is selected specifically by IR. #link("../../../crates/gammalooprs/src/uv/approx/final_integrand.rs:320")[Normalizer];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:1393")[later color collection];.

The separate local-4D lane does form U+S−US as three computed atoms, but it is excluded for the crashing direct case: its card sets `generate_integrated=false` and the direct route sets projected local-4D false, so `Forests::compute` seeds zero integrated coefficients without computing local 4D atoms. #link("../../../tests/resources/run_cards/paper_figure_b1_double_triangle_soft_ir.toml:46")[Card];, #link("../../../crates/gammalooprs/src/uv/hedge_poset.rs:1314")[route guard];, #link("../../../crates/gammalooprs/src/uv/approx/local_4d.rs:2247")[separate 4D composition];.

== Smallest useful comparison
<smallest-useful-comparison>
The completed huge run is not an equal-work U/H measurement: its localized case keeps exactly one production orientation, whereas explicit mode clears that filter and retains the full source inventory, including repeated direction signatures with different energy maps. A successful ordinary #emph[two-loop] double triangle also changes the graph from this three-loop dressed fixture. #link("../../../tests/tests/uv.rs:5216")[Explicit filter reset];, #link("../../../tests/tests/uv.rs:5280")[source multiplicity contract];.

Start with the same three-loop graph and the same audited single residue key in U and H. Compare the structure-only forest DOT (same covers, operation paths, component source sets and counts), root key/cut inventories, and aggregate byte sizes #strong[per node and per key];. The first shared input is the identical mapped `start` atom at the first IR operation. Existing size checkpoints bracket momentum replacement, loop/OSE rescaling, `series`, and final parameter removal. H\'s first call is S, its second is U on X−S(X); U\'s single call is ordinary. #link("../../../crates/gammalooprs/src/uv/approx/direct_3d/kernel.rs:563")[Existing checkpoints];.

If counts first differ before this scheme dispatch, investigate classification, replay or map multiplicity. If counts agree but one H Taylor output grows disproportionately, retain that smallest factorized branch and examine its exact cancellation/representation without distributing its numerator. If individual branches remain bounded but aggregation grows, compare all per-key byte sizes and the size of their materialized sum. A later matched localized/explicit comparison must use the same key inventory and certify `sum(selector * body)` versus `sum(body)` through the complete selector truth table before attributing anything to the shared algebra.

No upstream duplicate, lost factorization certificate, or exact unexpected-growth factor has yet been established. The next comparison is the matched single-key U/H byte-size trace at the first changed Taylor operation; the parent is arranging bounded comparisons separately.
