commands = []

[cli_settings]
[cli_settings.state]
folder = "./examples/cli/eos/cool_qm/NLO/state"
name = "cool_qm_eos_NLO"

[[command_blocks]]
name = "generate"
commands = [
    "import model sm-default.json",

    "remove processes",
    """generate amp {} > {} | u u~ d d~ b b~ g ghG ghG~ [{2}]
            --numerator-grouping group_identical_graphs_up_to_scalar_rescaling
            --max-n-bridges 0
            --number-of-factorized-loop-subtopologies -1 -1
            --only-diagrams
            -p cool_qm_eos
            -i NLO
    """,
    "generate",
    "save dot",
    "save state -o",
]

[[command_blocks]]
name = "integrate"
commands = [
    "set process -p cool_qm_eos -i NLO defaults",
    "display settings process -p cool_qm_eos -i NLO",

    "set process -p cool_qm_eos -i NLO kv integrator.n_start=100000 integrator.n_max=100000000",
    """integrate --process cool_qm_eos -i NLO
        --workspace-path ./examples/cli/eos/cool_qm/NLO/integration_workspace
        --target 0.0,-0.0625236069139053
        --restart
    """,

]

[default_runtime_settings.general]
evaluator_method = "SummedFunctionMap"
enable_cache = false
debug_cache = false
inverse_temperature = 10.0
m_uv = 2.0
renormalization_localization_scale = 2.0
mu_r = 2.0

[default_runtime_settings.model]
aS = [1.0, 0.0]
muB = [3.0, 0.0]
MB = [0.2, 0.0]

[default_runtime_settings.kinematics]
e_cm = 1.0

[default_runtime_settings.integrator]
integrated_phase = "imag"

[default_runtime_settings.sampling]
graphs = "monte_carlo"
orientations = "summed"
lmb_multichanneling = true
lmb_channels = "monte_carlo"
coordinate_system = "spherical"
mapping = "linear"
b = 1.0

[cli_settings.global.generation.medium]
mode = "thermodynamic_equilibrium"
vacuum_subtraction = true

[cli_settings.global.generation.uv]
subtract_uv = true
softct = false
generate_integrated = true

[cli_settings.global.generation.compile]
compilation_mode = "symjit"
optimization_level = "O3"
jit_direct_translation = false
fast_math = true
unsafe_math = true
custom = []

[cli_settings.global.n_cores]
feyngen = 10
generate = 10
compile = 10
integrate = 10

[cli_settings.global.generation.tropical_subgraph_table]
panic_on_fail = true
disable_tropical_generation = true

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = false
store_atom = false
compile = true
summed = false
summed_function_map = true
do_algebra = true
do_fn_map_replacements = false
direct_translation = true

[cli_settings.global.generation]
override_lmb_heuristics = true

[cli_settings.global.generation.threshold_subtraction]
enable_thresholds = false
check_esurface_at_generation = false

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.stability]
check_on_norm = true
escalate_if_exact_zero = true
loop_momenta_norm_escalation_factor = 100.0
rotation_axis = [
  { type = "x" },
  { type = "z" },
]

[[default_runtime_settings.stability.levels]]
precision = "Double"
required_precision_for_re = 1.0e-10
required_precision_for_im = 1.0e-10
escalate_for_large_weight_threshold = 0.9

[[default_runtime_settings.stability.levels]]
precision = "Arb"
required_precision_for_re = 1.0e-5
required_precision_for_im = 1.0e-5
escalate_for_large_weight_threshold = -1.0
