//! Collect the exact polynomial produced by the trace recurrence before
//! materializing atoms. Original scalar weights remain opaque polynomial variables.

use std::{collections::HashMap, sync::Arc};

use spenso::structure::partial::{PartialStructure, PartialStructureExt};
use symbolica::{
    atom::{Atom, AtomCore, AtomView},
    domains::rational::{Q, Rational, RationalField},
    poly::{PolyVariable, polynomial::MultivariatePolynomial},
};
use symbolica_utils::PolynomialExpressionExt;

use super::TraceAlgebra;
use crate::tensor::{
    SymbolicTensor,
    inference::{InterfaceInference, TensorInferenceError},
    simplification::observation::DomainObservations,
};

type Polynomial = MultivariatePolynomial<RationalField, u32>;

pub(in crate::dirac::simplify) struct CollectedOutput<'a> {
    source: &'a DomainObservations,
    atoms: [HashMap<Atom, Polynomial>; 2],
    opaque: Vec<Atom>,
    variables: Arc<Vec<PolyVariable>>,
    tensors: HashMap<PolyVariable, Option<bool>>,
    refused: bool,
    emitted: HashMap<Atom, Polynomial>,
}

impl<'a> CollectedOutput<'a> {
    pub(in crate::dirac::simplify) fn new(source: &'a DomainObservations) -> Self {
        Self {
            source,
            atoms: Default::default(),
            opaque: Vec::new(),
            variables: Arc::default(),
            tensors: HashMap::new(),
            refused: false,
            emitted: HashMap::new(),
        }
    }

    // Selected exterior coefficients can be collected across trace sectors.
    // Vector weights and power bases retain their original scalar-sum boundaries.
    fn polynomial(&mut self, value: AtomView<'_>, collect_sums: bool) -> Polynomial {
        if let Some(polynomial) = self.atoms[usize::from(collect_sums)].get(value.get_data()) {
            return polynomial.clone();
        }
        let mut polynomial = if !collect_sums
            && matches!(value, AtomView::Add(_))
            && self
                .source
                .region(value)
                .is_some_and(|region| region.certifies_scalar_interface_syntax())
        {
            // This sum already existed in a coefficient of the source
            // vector. It is not arithmetic generated by the trace identity.
            let variable = PolyVariable::Temporary(self.opaque.len());
            self.opaque.push(value.to_owned());
            Polynomial::new(&Q, Some(1), Arc::new(vec![variable]))
                .monomial(Rational::one(), vec![1])
        } else {
            match value {
                AtomView::Add(sum) => sum.iter().fold(Polynomial::new_zero(&Q), |sum, term| {
                    sum + self.polynomial(term, collect_sums)
                }),
                AtomView::Mul(product) => {
                    product
                        .iter()
                        .fold(Polynomial::new_one(&Q), |product, factor| {
                            let factor = self.polynomial(factor, collect_sums);
                            self.product(product, factor)
                        })
                }
                AtomView::Pow(power) => {
                    let (base, exponent) = power.get_base_exp();
                    if let Ok(exponent) = i64::try_from(exponent)
                        && let Ok(exponent) = u32::try_from(exponent)
                    {
                        // Contraction can combine two source powers. Reuse the
                        // opaque base even when the resulting power is new.
                        let base = self.polynomial(base, false);
                        if exponent <= i32::MAX as u32
                            && (0..base.nvars()).all(|variable| {
                                base.degree(variable)
                                    .checked_mul(exponent)
                                    .is_some_and(|degree| degree <= i32::MAX as u32)
                            })
                        {
                            base.pow(exponent as usize)
                        } else {
                            self.refused = true;
                            Polynomial::new_zero(&Q)
                        }
                    } else {
                        Polynomial::new(
                            &Q,
                            Some(1),
                            Arc::new(vec![PolyVariable::Power(value.to_owned())]),
                        )
                        .monomial(Rational::one(), vec![1])
                    }
                }
                _ => match value.try_to_polynomial(&Q, None) {
                    Ok(polynomial) => polynomial,
                    Err(_) => {
                        // Rounded or unsupported coefficient domains retain the
                        // established Atom arithmetic, including its grouping.
                        self.refused = true;
                        Polynomial::new_zero(&Q)
                    }
                },
            }
        };
        if !self.refused {
            // Every temporary coefficient uses a prefix of the same ordering.
            // Unification can then extend exponent rows without re-sorting a
            // large polynomial every time another pairing introduces a variable.
            for variable in polynomial.variables().iter() {
                if !self.variables.contains(variable) {
                    Arc::make_mut(&mut self.variables).push(variable.clone());
                }
            }
            Polynomial::new(&Q, None, self.variables.clone()).unify_variables(&mut polynomial);
            self.atoms[usize::from(collect_sums)].insert(value.to_owned(), polynomial.clone());
        }
        polynomial
    }

    fn product(&mut self, mut left: Polynomial, mut right: Polynomial) -> Polynomial {
        if self.refused {
            return Polynomial::new_zero(&Q);
        }
        // Reuse the owned inputs when aligning variables. Multiplication would
        // otherwise clone both just to unify their coefficient contexts.
        left.unify_variables(&mut right);
        // Symbolica stores u32 exponents but its arithmetic uses signed bounds.
        // Ordinary trace degrees are small; only unusually large input powers
        // need the more expensive per-variable degree check.
        if !left
            .exponents
            .iter()
            .chain(&right.exponents)
            .all(|&exponent| exponent <= i32::MAX as u32 / 2)
            && (0..left.nvars()).any(|variable| {
                u64::from(left.degree(variable)) + u64::from(right.degree(variable))
                    > i32::MAX as u64
            })
        {
            self.refused = true;
            return Polynomial::new_zero(&Q);
        }
        &left * &right
    }

    fn emit_coefficient(&self, polynomial: &Polynomial) -> Atom {
        let coefficient = polynomial
            .to_expression_with_variables(|variable| {
                Some(match variable {
                    PolyVariable::Temporary(index) => self.opaque[*index].clone(),
                    variable => variable.to_atom(),
                })
            })
            .expect("every temporary has its original scalar scope");
        // Distribute numerical coefficients using Symbolica's own normalizer.
        // This can cancel 2*(x+y)-2*x-2*y while leaving products and powers of
        // unrelated scalar sums factorized. Tensor factors are emitted outside.
        coefficient.expand_num()
    }

    pub(super) fn finish(&mut self, value: Polynomial) -> Option<Atom> {
        #[cfg(feature = "reference-cases")]
        let _phase = crate::reference_cases::timing::scope(
            crate::reference_cases::timing::Phase::OutputNormalization,
        );
        if self.refused {
            return None;
        }
        let mut tensors = Vec::new();
        for (position, variable) in value.variables().iter().enumerate() {
            if matches!(variable, PolyVariable::Temporary(_)) {
                continue;
            }
            if (*self.tensors.entry(variable.clone()).or_insert_with(|| {
                InterfaceInference::replacement_interface(variable.to_atom().as_view())
                    .ok()
                    .map(|interface| !interface.logical_slots().is_empty())
            }))? {
                tensors.push(position);
            }
        }
        let expression = value
            .to_polynomial_in(&tensors)
            .to_expression_with_coeff_map(|_, coefficient, out| {
                *out = self.emit_coefficient(coefficient);
            });
        self.emitted.insert(expression.clone(), value);
        Some(expression)
    }

    pub(super) fn begin_trace(&mut self) {
        self.refused = false;
    }

    pub(in crate::dirac::simplify) fn retain_product(&mut self, expression: &Atom) {
        if self.emitted.contains_key(expression) {
            return;
        }
        let polynomial = self.polynomial(expression.as_view(), false);
        if !self.refused {
            self.emitted.insert(expression.clone(), polynomial);
        }
    }

    /// Combine only certified generated sectors. The collector retains every
    /// unrelated spectator outside this frontier and does not open it here.
    pub(in crate::dirac::simplify) fn collect(
        &mut self,
        states: &mut Vec<(
            SymbolicTensor<PartialStructure>,
            SymbolicTensor<PartialStructure>,
        )>,
    ) -> Result<(), TensorInferenceError> {
        #[cfg(feature = "reference-cases")]
        let _phase = crate::reference_cases::timing::scope(
            crate::reference_cases::timing::Phase::CoefficientMerge,
        );
        let mut generated: Vec<(SymbolicTensor<PartialStructure>, Polynomial)> = Vec::new();
        let mut retained = Vec::new();
        for (selected, coefficient) in std::mem::take(states) {
            let Some(polynomial) = self.emitted.get(&selected.expression) else {
                // Some terminal identities normalize to a metric before the
                // bound recurrence runs. Their selected coefficients still
                // receive the requested numerical-factor distribution.
                let expression = coefficient.expression.expand_num();
                let coefficient = if expression == coefficient.expression {
                    coefficient
                } else {
                    let observations = coefficient
                        .reduction_observations()
                        .updated(expression.as_view());
                    coefficient.with_identity_result(expression, Some(observations))?
                };
                retained.push((selected, coefficient));
                continue;
            };
            let facts = coefficient.reduction_observations();
            if facts.identity_candidates() != 0
                || !(facts.excludes_internal_connections()
                    || (coefficient.is_scalar() && facts.can_certify_scalar()))
                || !selected.reduction_observations().is_terminal_polynomial()
            {
                retained.push((selected, coefficient));
                continue;
            }
            let polynomial = polynomial.clone();
            let interface = InterfaceInference::merge_explicit_interface_sequence(&[
                selected.structure.clone(),
                coefficient.structure.clone(),
            ])?;
            if interface.logical_slots().len()
                != selected.structure.logical_slots().len()
                    + coefficient.structure.logical_slots().len()
            {
                retained.push((selected, coefficient));
                continue;
            }
            self.refused = false;
            let coefficient_polynomial = self.polynomial(coefficient.expression.as_view(), true);
            if self.refused {
                retained.push((selected, coefficient));
                continue;
            }
            let polynomial = self.product(polynomial, coefficient_polynomial);
            if self.refused {
                retained.push((selected, coefficient));
                continue;
            }
            if let Some(position) = generated.iter().position(|(previous, _)| {
                InterfaceInference::additive_interfaces_match(&previous.structure, &interface)
            }) {
                let (_, previous): &mut (_, Polynomial) = &mut generated[position];
                *previous = std::mem::replace(previous, Polynomial::new_zero(&Q)) + polynomial;
            } else {
                let selected = if coefficient.is_scalar() {
                    selected
                } else {
                    SymbolicTensor::collection_product(&[selected, coefficient])?
                };
                generated.push((selected, polynomial));
            }
        }
        self.refused = false;
        for (selected, polynomial) in generated {
            let expression = self
                .finish(polynomial)
                .expect("certified trace variables retain their interfaces");
            let observations = DomainObservations::terminal_polynomial(&selected.structure, true);
            let selected = selected.with_identity_result(expression, Some(observations))?;
            let coefficient = SymbolicTensor::from_validated_parts(
                Atom::one(),
                PartialStructure::from_logical_slots([]),
            );
            retained.push((selected, coefficient));
        }
        *states = retained;
        Ok(())
    }
}

impl TraceAlgebra for &mut CollectedOutput<'_> {
    type Value = Polynomial;

    fn unit(&mut self, trace_unit: AtomView<'_>) -> Polynomial {
        self.polynomial(trace_unit, false)
    }

    fn scale(&mut self, coefficient: i32, value: Polynomial) -> Polynomial {
        value.mul_coeff(coefficient.into())
    }

    fn metric_product(
        &mut self,
        metric: AtomView<'_>,
        coefficient: i32,
        value: Polynomial,
    ) -> Polynomial {
        let metric = self.polynomial(metric, false);
        self.product(metric, value).mul_coeff(coefficient.into())
    }

    fn dimension_product(
        &mut self,
        dimension: AtomView<'_>,
        constant: i32,
        linear: i32,
        value: Polynomial,
    ) -> Polynomial {
        let dimension = self.polynomial(dimension, false).mul_coeff(linear.into());
        self.product(
            dimension + Polynomial::new_one(&Q).mul_coeff(constant.into()),
            value,
        )
    }

    fn add(&mut self, left: Polynomial, right: Polynomial) -> Polynomial {
        left + right
    }
    fn subtract(&mut self, left: Polynomial, right: Polynomial) -> Polynomial {
        left - right
    }
    fn sum(&mut self, values: Vec<Polynomial>) -> Polynomial {
        values
            .into_iter()
            .fold(Polynomial::new_zero(&Q), |sum, value| sum + value)
    }

    #[cfg(test)]
    fn finish(self, value: Polynomial) -> Atom {
        CollectedOutput::finish(self, value).unwrap()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unrepresentable_power_refuses_without_expanding_its_scalar_base() {
        let source = SymbolicTensor::infer(symbolica::parse!("overflow_x + overflow_y")).unwrap();
        let mut output = CollectedOutput::new(source.reduction_observations());
        let expression = source.expression.pow(i64::from(i32::MAX) + 1);
        let polynomial = output.polynomial(expression.as_view(), false);
        assert!(output.refused);
        assert!(output.finish(polynomial).is_none());
        assert_eq!(output.opaque, std::slice::from_ref(&source.expression));
        assert!(output.emitted.is_empty());
    }

    #[test]
    fn product_checks_all_monomials_after_aligning_variables() {
        let source = SymbolicTensor::infer(Atom::one()).unwrap();
        let mut output = CollectedOutput::new(source.reduction_observations());
        let left = Polynomial::from_coefficient_list(
            vec![Rational::one(), Rational::one()],
            vec![0, i32::MAX as u32, 1, 0],
            vec![PolyVariable::Temporary(0), PolyVariable::Temporary(1)].into(),
            &Q,
        );
        let right = Polynomial::from_coefficient_list(
            vec![Rational::one()],
            vec![1, 0],
            vec![PolyVariable::Temporary(1), PolyVariable::Temporary(0)].into(),
            &Q,
        );
        let polynomial = output.product(left, right);
        assert!(output.refused);
        assert!(output.finish(polynomial).is_none());
    }

    #[test]
    fn refused_finalizer_product_retains_the_exact_selected_state() {
        let source = SymbolicTensor::infer(symbolica::parse!("retained_x + retained_y")).unwrap();
        let mut output = CollectedOutput::new(source.reduction_observations());
        let selected = SymbolicTensor::from_validated_parts(
            source.expression.pow(i64::from(i32::MAX)),
            PartialStructure::from_logical_slots([]),
        );
        selected
            .proofs
            .observations
            .set(Arc::new(DomainObservations::terminal_polynomial(
                &selected.structure,
                false,
            )))
            .unwrap();
        output.retain_product(&selected.expression);
        assert!(!output.refused);
        let coefficient = SymbolicTensor::infer(source.expression.pow(2)).unwrap();
        let original = (selected, coefficient);
        let mut states = vec![original.clone()];
        output.collect(&mut states).unwrap();
        assert_eq!(states, [original]);
    }
}
