[[command_blocks]]
name = "setup_all_graphs_pmpm_kinematics_a"
commands = [
  "run set_model_parameters",
  "run set_kinematics_a",
  "set process -p aa_aa kv kinematics.externals.data.helicities=[+1,-1,+1,-1] general.mu_r=91.188 general.m_uv=9.188",
]

[[command_blocks]]
name = "integrate_graph_summed_100k"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=100000 integrator.n_max=100000 integrator.seed=260715 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "summed"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_summed_invj_sumlmb_100k_workspace
             --renderer tabled
             --batch-size 1000
             --show-phase both
             --show-max-weight-info
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_summed_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260716 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "summed"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_summed_invj_sumlmb_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260717 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_hyperspherical_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260718 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "hyperspherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_hyperspherical_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_hyperspherical_ose_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260725 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "ose"
        coordinate_system = "hyperspherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_ose_sumlmb_hyperspherical_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_hyperspherical_no_lmb_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260726 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = false
        lmb_channels = "summed"
        coordinate_system = "hyperspherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_no_lmb_hyperspherical_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_power2_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260719 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "power"
        b = 1.0
        power = 2.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_power2_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_power4_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260720 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "power"
        b = 1.0
        power = 4.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_power4_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_power8_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260721 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "power"
        b = 1.0
        power = 8.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_power8_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_power2_b1em4_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260722 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "power"
        b = 1.0e-4
        power = 2.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_power2_b1em4_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_power2_b1em5_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260723 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "power"
        b = 1.0e-5
        power = 2.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_invj_sumlmb_power2_b1em5_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]

[[command_blocks]]
name = "integrate_graph_mc_lmbmc_inverse_1m"
commands = [
  "run setup_all_graphs_pmpm_kinematics_a",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=260724 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "monte_carlo"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_graph_mc_lmbmc_inverse_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]
