[cli_settings]
[cli_settings.state]
name = "aa_aa_2L_existing_state_sampling_probes"
folder = "/tmp/gammaloop_aa_aa_2l_all_graphs_invj_sumlmb_state"

[cli_settings.global]
display_directive = "info,gammalooprs[{#generation, #profile, #uv, #graph, #term, #summary}]=debug"
logfile_directive = "off"

[[command_blocks]]
name = "set_model_parameters"
commands = [
  "set model MT=173.0",
  "set model WT=0.0",
  "set model ymt=173.0",
  "set model aS=0.118",
  "set model aEWM1=137.036",
  "set model Gf=1.166390e-05",
  "set model MZ=91.188",
]

[[command_blocks]]
name = "set_kinematics_a"
commands = [
  """set process string '
    [kinematics.externals]
    type = "constant"
    [kinematics.externals.data]
    momenta = [
        [ 86.5, 0.0, 0.0, 86.5 ],
        [ 86.5, 0.0, 0.0, -86.5 ],
        [ 86.5, 0.0, -79.27855952273603, -34.6 ],
        "dependent"
    ]
    '""",
]

[[command_blocks]]
name = "integrate_ose_alpha_minus1_1m"
commands = [
  "run set_model_parameters",
  "run set_kinematics_a",
  "set process -p aa_aa kv kinematics.externals.data.helicities=[+1,-1,+1,-1] general.mu_r=91.188 general.m_uv=9.188",
  "set process -p aa_aa kv integrator.n_increase=0 integrator.n_start=1000000 integrator.n_max=1000000 integrator.seed=261201 integrator.integrated_phase=\"imag\" integrator.target_relative_accuracy=0.01",
  """set process -p aa_aa string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "summed"
        lmb_multichanneling = true
        lmb_channels = "summed"
        lmb_channel_weight = "ose"
        alpha = -1.0
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa -i 2L
             --n-cores 20
             --workspace-path /tmp/aa_aa_2l_ose_alpha_minus1_1m_workspace
             --renderer tabled
             --batch-size 10000
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
]
