# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import numpy
import numpy.typing
import os
import pathlib
import typing

@typing.final
class AdditionalWeight:
    @property
    def key(self) -> builtins.str: ...
    @property
    def value(self) -> typing.Any: ...

@typing.final
class BatchEvaluationResult:
    @property
    def samples(self) -> builtins.list[SampleEvaluationResult]: ...
    @property
    def observables(self) -> dict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ComponentDiscreteBreakdown:
    @property
    def re(self) -> typing.Optional[DiscreteBreakdown]: ...
    @property
    def im(self) -> typing.Optional[DiscreteBreakdown]: ...

@typing.final
class CutInfo:
    @property
    def incoming_pdgs(self) -> builtins.list[builtins.int]: ...
    @property
    def outgoing_pdgs(self) -> builtins.list[builtins.int]: ...
    @property
    def cut_id(self) -> builtins.int: ...
    @property
    def graph_id(self) -> builtins.int: ...
    @property
    def graph_group_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def orientation_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def lmb_channel_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def lmb_channel_edge_ids(self) -> typing.Optional[builtins.list[builtins.int]]: ...

@typing.final
class DiscreteBreakdown:
    @property
    def axis_label(self) -> builtins.str: ...
    @property
    def fixed_coordinates(self) -> builtins.list[DiscreteCoordinate]: ...
    @property
    def entries(self) -> builtins.list[DiscreteBreakdownEntry]: ...

@typing.final
class DiscreteBreakdownEntry:
    @property
    def bin_index(self) -> builtins.int: ...
    @property
    def bin_label(self) -> typing.Optional[builtins.str]: ...
    @property
    def pdf(self) -> builtins.float: ...
    @property
    def value(self) -> builtins.float: ...
    @property
    def error(self) -> builtins.float: ...
    @property
    def chi_sq(self) -> builtins.float: ...
    @property
    def processed_samples(self) -> builtins.int: ...

@typing.final
class DiscreteCoordinate:
    @property
    def axis_label(self) -> builtins.str: ...
    @property
    def bin_index(self) -> builtins.int: ...
    @property
    def bin_label(self) -> typing.Optional[builtins.str]: ...

@typing.final
class DotExportSettings:
    @property
    def combine_diagrams(self) -> builtins.bool: ...
    @combine_diagrams.setter
    def combine_diagrams(self, value: builtins.bool) -> None: ...
    @property
    def with_uv(self) -> builtins.bool: ...
    @with_uv.setter
    def with_uv(self, value: builtins.bool) -> None: ...
    @property
    def output_full_numerator(self) -> builtins.bool: ...
    @output_full_numerator.setter
    def output_full_numerator(self, value: builtins.bool) -> None: ...
    @property
    def split_xs_by_initial_states(self) -> builtins.bool: ...
    @split_xs_by_initial_states.setter
    def split_xs_by_initial_states(self, value: builtins.bool) -> None: ...
    @property
    def do_gamma_algebra(self) -> builtins.bool: ...
    @do_gamma_algebra.setter
    def do_gamma_algebra(self, value: builtins.bool) -> None: ...
    @property
    def do_color_algebra(self) -> builtins.bool: ...
    @do_color_algebra.setter
    def do_color_algebra(self, value: builtins.bool) -> None: ...
    @property
    def include_autogenerated_fields(self) -> builtins.bool: ...
    @include_autogenerated_fields.setter
    def include_autogenerated_fields(self, value: builtins.bool) -> None: ...
    def __new__(cls) -> DotExportSettings: ...

@typing.final
class EvaluationResult:
    @property
    def sample(self) -> SampleEvaluationResult: ...
    @property
    def integrand_result(self) -> complex: ...
    @property
    def integrator_weight(self) -> builtins.float: ...
    @property
    def generated_event_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def accepted_event_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def event_processing_time_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def parameterization_jacobian(self) -> typing.Optional[builtins.float]: ...
    @property
    def is_nan(self) -> typing.Optional[builtins.bool]: ...
    @property
    def stability_results(self) -> typing.Optional[builtins.list[StabilityResult]]: ...
    @property
    def event_groups(self) -> builtins.list[EventGroup]: ...
    @property
    def observables(self) -> dict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Event:
    @property
    def incoming_momenta(self) -> builtins.list[FourMomentum]: ...
    @property
    def outgoing_momenta(self) -> builtins.list[FourMomentum]: ...
    @property
    def cut_info(self) -> CutInfo: ...
    @property
    def weight(self) -> typing.Any: ...
    @property
    def additional_weights(self) -> builtins.list[AdditionalWeight]: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EventGroup:
    @property
    def events(self) -> builtins.list[Event]: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FourMomentum:
    @property
    def e(self) -> builtins.float: ...
    @property
    def px(self) -> builtins.float: ...
    @property
    def py(self) -> builtins.float: ...
    @property
    def pz(self) -> builtins.float: ...

@typing.final
class GammaLoopAPI:
    r"""
    Load, inspect, and evaluate one mutable GammaLoop session.

    One instance owns a GammaLoop state, run history, CLI settings, default runtime
    settings, and session state. Calls to ``run`` and the evaluation methods all act
    on that same in-memory session.

    Notes
    -----
    ``read_only_state=True`` prevents writes inside the active state directory; it
    does not make this Python object immutable. Commands may still change in-memory
    settings, processes, or run history. Create separate instances when independent
    sessions are required.
    """
    def __new__(cls, state_folder: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, boot_commands_path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, model_file: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, trace_logs_filename: typing.Optional[builtins.str] = None, level: typing.Optional[LogLevel] = None, logfile_level: typing.Optional[LogLevel] = None, logging_prefix: builtins.object | None = None, read_only_state: builtins.bool = ..., settings_global_path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, settings_runtime_defaults_path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, clean_state: builtins.bool = ...) -> GammaLoopAPI:
        r"""
        Load or create a GammaLoop state and initialize its CLI session.

        Parameters
        ----------
        state_folder : path-like, optional
            State directory to load or create. The default is ``./gammaloop_state``.
        boot_commands_path : path-like, optional
            TOML run card whose commands are applied during startup.
        model_file : path-like, optional
            Model file override used while loading or initializing the state.
        trace_logs_filename : str, optional
            File receiving native trace records for this session.
        level : LogLevel, optional
            Terminal log-level override for this session.
        logfile_level : LogLevel, optional
            File log-level override for this session.
        logging_prefix : object, optional
            Native logging-prefix configuration.
        read_only_state : bool, default=False
            Prevent writes whose target lies inside the active state directory and
            disable file logging there. In-memory session changes remain possible.
        settings_global_path : path-like, optional
            TOML file overriding the global settings loaded at startup.
        settings_runtime_defaults_path : path-like, optional
            TOML file overriding the default runtime settings loaded at startup.
        clean_state : bool, default=False
            Remove the resolved state path before startup. This is destructive and
            cannot be combined with ``read_only_state=True``.

        Returns
        -------
        GammaLoopAPI
            A stateful API instance sharing one state, history, and settings session.

        Raises
        ------
        Exception
            If startup options conflict, the state or settings cannot be loaded, a
            boot command fails, or a boot card requests process exit.

        Examples
        --------
        Open an existing generated state without permitting writes to it::

            api = GammaLoopAPI(state_folder="./state", read_only_state=True)
        """
    def evaluate_sample(self, point: typing.Sequence[builtins.float], process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None, use_arb_prec: builtins.bool = ..., minimal_output: builtins.bool = ..., return_events: typing.Optional[builtins.bool] = None, momentum_space: builtins.bool = ..., integrator_weight: typing.Optional[builtins.float] = None, discrete_dim: typing.Optional[typing.Sequence[builtins.int]] = None, graph_name: typing.Optional[builtins.str] = None, orientation: typing.Optional[builtins.int] = None) -> EvaluationResult:
        r"""
        Evaluate one integration or momentum-space sample.

        Parameters
        ----------
        point : Sequence[float]
            Coordinates for one sample. In integration space, the length must match
            the selected integrand and ``discrete_dim``. In momentum space, values
            are grouped as ``(px, py, pz)`` and the length must be a multiple of 3.
        process_id : int, optional
            Process containing the integrand. Supply this when selection is ambiguous.
        integrand_name : str, optional
            Integrand to evaluate. Supply this when selection is ambiguous.
        use_arb_prec : bool, default=False
            Request arbitrary-precision internal evaluation.
        minimal_output : bool, default=False
            Omit the optional evaluation metadata from the returned sample.
        return_events : bool, optional
            Temporarily override event generation for this call. The integrand setting
            is restored afterward.
        momentum_space : bool, default=False
            Interpret ``point`` as flattened three-momenta instead of integration-space
            coordinates.
        integrator_weight : float, optional
            Weight associated with this sample. The default is 1.0.
        discrete_dim : Sequence[int], optional
            Discrete integration coordinates used to determine the expected dimension.
        graph_name : str, optional
            Graph selected for momentum-space evaluation.
        orientation : int, optional
            Orientation index for ``graph_name`` in momentum-space evaluation.

        Returns
        -------
        EvaluationResult
            The sample evaluation and the observable snapshot for its one-row batch.

        Raises
        ------
        Exception
            If integrand selection is ambiguous or invalid, dimensions do not match,
            graph or orientation selection is invalid, or warm-up/evaluation fails.

        Notes
        -----
        Arbitrary precision affects the internal calculation, but Python-visible
        numeric fields use the package's ``float64`` output contract. Evaluation may
        warm the integrand and update in-memory caches or observable snapshots even in
        a read-only-state session.

        Examples
        --------
        Evaluate a point whose dimension matches integrand 0::

            result = api.evaluate_sample(point, process_id=0, minimal_output=True)
            value = result.integrand_result
        """
    def evaluate_samples(self, points: numpy.typing.NDArray[numpy.float64], process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None, use_arb_prec: builtins.bool = ..., minimal_output: builtins.bool = ..., return_events: typing.Optional[builtins.bool] = None, momentum_space: builtins.bool = ..., integrator_weights: typing.Optional[numpy.typing.NDArray[numpy.float64]] = None, discrete_dims: numpy.typing.NDArray[numpy.unsignedinteger] | None = None, graph_names: typing.Optional[typing.Sequence[typing.Optional[builtins.str]]] = None, orientations: typing.Optional[typing.Sequence[typing.Optional[builtins.int]]] = None) -> BatchEvaluationResult:
        r"""
        Evaluate a batch of integration or momentum-space samples.

        Parameters
        ----------
        points : numpy.ndarray[numpy.float64]
            Two-dimensional array with one sample per row. Integration-space columns
            must match the selected integrand; momentum-space columns are flattened
            ``(px, py, pz)`` groups.
        process_id : int, optional
            Process containing the integrand. Supply this when selection is ambiguous.
        integrand_name : str, optional
            Integrand to evaluate. Supply this when selection is ambiguous.
        use_arb_prec : bool, default=False
            Request arbitrary-precision internal evaluation.
        minimal_output : bool, default=False
            Omit the optional evaluation metadata from every returned sample.
        return_events : bool, optional
            Temporarily override event generation for this call. The integrand setting
            is restored afterward.
        momentum_space : bool, default=False
            Interpret each row as flattened three-momenta instead of integration-space
            coordinates.
        integrator_weights : numpy.ndarray[numpy.float64], optional
            One weight per row. Defaults to 1.0 for every sample.
        discrete_dims : numpy.ndarray[numpy.unsignedinteger], optional
            Two-dimensional array with one row of discrete coordinates per sample.
        graph_names : Sequence[str | None], optional
            Momentum-space graph selection for each sample.
        orientations : Sequence[int | None], optional
            Momentum-space orientation selection for each sample.

        Returns
        -------
        BatchEvaluationResult
            Per-sample evaluations and one observable snapshot for the complete batch.

        Raises
        ------
        Exception
            If integrand selection is ambiguous or invalid, array or option lengths do
            not match, dimensions are invalid, or warm-up/evaluation fails.

        Notes
        -----
        Arbitrary precision affects the internal calculation, but Python-visible
        numeric fields use the package's ``float64`` output contract. Evaluation may
        update in-memory caches or observable snapshots in a read-only-state session.

        Examples
        --------
        Evaluate a caller-provided two-dimensional array::

            points = numpy.asarray(points, dtype=numpy.float64)
            result = api.evaluate_samples(points, process_id=0, minimal_output=True)
        """
    def import_graphs(self, graphs: builtins.str, process_name: typing.Optional[builtins.str] = None, process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None, format: builtins.str = ..., overwrite: builtins.bool = ..., append: builtins.bool = ...) -> None: ...
    def get_lmbs(self, graphs: builtins.str, format: builtins.str = ...) -> builtins.list[builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.dict[builtins.int, tuple[builtins.list[builtins.int], builtins.list[builtins.int]]]]]]: ...
    def get_orientations(self, graph_name: builtins.str, process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None) -> builtins.list[builtins.dict[builtins.int, builtins.int]]: ...
    def get_model(self) -> builtins.str: ...
    def evaluate(self, process_id: typing.Optional[builtins.int] = None, graphs_group_name: typing.Optional[builtins.str] = None, result_path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, numerical: builtins.bool = ..., number_of_terms_in_epsilon_expansion: typing.Optional[builtins.int] = None) -> builtins.str: ...
    def import_model(self, model_specifier: builtins.str | os.PathLike | pathlib.Path, simplify_model: builtins.bool = ...) -> None: ...
    def list_outputs(self) -> tuple[builtins.dict[builtins.str, builtins.int], builtins.dict[builtins.str, builtins.int]]: ...
    def get_integrand_info(self, process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None) -> IntegrandInfo:
        r"""
        Describe the selected generated integrand and its graph structure.

        Parameters
        ----------
        process_id : int, optional
            Process containing the integrand. Supply this when selection is ambiguous.
        integrand_name : str, optional
            Integrand to inspect. Supply this when selection is ambiguous.

        Returns
        -------
        IntegrandInfo
            Structured process, backend, graph, orientation, cut, and size metadata.

        Raises
        ------
        Exception
            If no unique generated integrand matches the selection.

        Examples
        --------
        Inspect the active evaluation backend and graph count::

            info = api.get_integrand_info(process_id=0)
            print(info.active_f64_backend, info.graph_count)
        """
    def get_integrand_settings(self, process_id: typing.Optional[builtins.int] = None, integrand_name: typing.Optional[builtins.str] = None) -> SettingsValue:
        r"""
        Return a detached, read-only snapshot of one integrand's settings.

        Parameters
        ----------
        process_id : int, optional
            Process containing the integrand. Supply this when selection is ambiguous.
        integrand_name : str, optional
            Integrand whose settings are required.

        Returns
        -------
        SettingsValue
            Serialized settings snapshot supporting ``get(path)``, attribute access,
            indexing, and ``to_dict()``. Mutating it does not update the live session.

        Raises
        ------
        Exception
            If selection fails, the integrand has not been generated, or its settings
            cannot be serialized.

        Examples
        --------
        Read a nested setting without changing the live integrand::

            settings = api.get_integrand_settings(process_id=0)
            print(settings.get("general.generate_events"))
        """
    def get_run_history(self) -> builtins.str:
        r"""
        Render the current in-memory run history as TOML.

        Returns
        -------
        str
            TOML representation of the history owned by this API instance.

        Raises
        ------
        Exception
            If the current history cannot be serialized.

        Notes
        -----
        This reports the live session, including commands run through ``run``; it does
        not imply that the history has been persisted to the state directory.

        Examples
        --------
        Capture a reproducible run card from the current session::

            run_card_toml = api.get_run_history()
        """
    def get_global_settings(self) -> builtins.str:
        r"""
        Render the current effective CLI and global settings as TOML.

        Returns
        -------
        str
            TOML representation of the settings used by this API session.

        Raises
        ------
        Exception
            If the settings cannot be rendered.

        Examples
        --------
        Record the effective settings after applying startup overrides::

            settings_toml = api.get_global_settings()
        """
    def get_active_command_blocks(self) -> builtins.dict[builtins.str, builtins.list[builtins.str]]:
        r"""
        Return the named command blocks in the current run history.

        Returns
        -------
        dict[str, list[str]]
            Mapping from block name to its rendered CLI commands.

        Examples
        --------
        Inspect the commands currently grouped under each block::

            for name, commands in api.get_active_command_blocks().items():
                print(name, commands)
        """
    def get_default_runtime_settings(self) -> SettingsValue:
        r"""
        Return a detached, read-only snapshot of the default runtime settings.

        Returns
        -------
        SettingsValue
            Serialized settings including defaults. Use ``get(path)`` or ``to_dict()``
            to inspect it; changes to derived Python values do not affect the session.

        Raises
        ------
        Exception
            If the settings cannot be serialized.

        Examples
        --------
        Inspect a runtime default by its documented settings path::

            runtime = api.get_default_runtime_settings()
            print(runtime.get("integrator.n_start"))
        """
    def get_dot_files(self, process: typing.Optional[builtins.int | builtins.str] = None, integrand_name: typing.Optional[builtins.str] = None, settings: DotExportSettings = ...) -> builtins.str: ...
    def run(self, command: builtins.str) -> None:
        r"""
        Parse and execute a CLI command in this API instance's session.

        Parameters
        ----------
        command : str
            GammaLoop CLI command text.

        Returns
        -------
        None
            The command's normal output is emitted through the configured CLI/logging
            sinks; inspect structured state through the corresponding getter methods.

        Raises
        ------
        Exception
            If the command cannot be parsed or execution fails.

        Notes
        -----
        Commands share and may mutate the instance's in-memory state, settings, and run
        history. ``read_only_state=True`` only blocks writes inside the active state
        directory. The API does not automatically persist the session after this call;
        persistence depends on the executed command's explicit output behavior.

        Examples
        --------
        Display the processes loaded in the current state::

            api.run("display processes")
        """
    def generate_cff(self, dot_string: builtins.str, subgraph_nodes: typing.Sequence[builtins.str], reverse_dangling: typing.Sequence[builtins.int], orientation_pattern: typing.Optional[builtins.str] = None) -> builtins.list[tuple[builtins.dict[builtins.int, builtins.int], builtins.str]]: ...
    def generate_cff_as_json_string(self, dot_string: builtins.str, subgraph_nodes: typing.Sequence[builtins.str], reverse_dangling: typing.Sequence[builtins.int], orientation_pattern: typing.Optional[builtins.str] = None) -> builtins.str: ...

@typing.final
class HistogramAccumulator:
    @staticmethod
    def continuous(title: builtins.str, x_min: builtins.float, x_max: builtins.float, n_bins: builtins.int, type_description: builtins.str = ..., phase: builtins.str = ..., value_transform: builtins.str = ..., log_x_axis: builtins.bool = ..., log_y_axis: builtins.bool = ...) -> HistogramAccumulator: ...
    @staticmethod
    def discrete(title: builtins.str, min_bin_id: builtins.int, max_bin_id: builtins.int, ordering: builtins.str = ..., labels: typing.Optional[typing.Sequence[builtins.str]] = None, type_description: builtins.str = ..., phase: builtins.str = ..., log_y_axis: builtins.bool = ...) -> HistogramAccumulator: ...
    def snapshot(self) -> HistogramSnapshot: ...
    def merge_in_place(self, other: HistogramAccumulator) -> None: ...
    def rebin(self, contiguous_bins: builtins.int) -> HistogramAccumulator: ...
    def rescale(self, factor: builtins.float) -> None: ...
    def change_bin_ordering(self, ordering: builtins.str) -> None: ...
    def update_results(self) -> None: ...
    def fill_continuous_sample(self, entries: typing.Sequence[tuple[builtins.float, builtins.float]]) -> None: ...
    def fill_discrete_sample(self, entries: typing.Sequence[tuple[builtins.int, builtins.float]]) -> None: ...

@typing.final
class HistogramBin:
    @property
    def x_min(self) -> typing.Optional[builtins.float]: ...
    @property
    def x_max(self) -> typing.Optional[builtins.float]: ...
    @property
    def bin_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def label(self) -> typing.Optional[builtins.str]: ...
    @property
    def entry_count(self) -> builtins.int: ...
    @property
    def sum_weights(self) -> builtins.float: ...
    @property
    def sum_weights_squared(self) -> builtins.float: ...
    @property
    def mitigated_fill_count(self) -> builtins.int: ...
    def average(self, sample_count: builtins.int) -> builtins.float: ...
    def error(self, sample_count: builtins.int) -> builtins.float: ...

@typing.final
class HistogramSnapshot:
    @property
    def kind(self) -> builtins.str: ...
    @property
    def title(self) -> builtins.str: ...
    @property
    def type_description(self) -> builtins.str: ...
    @property
    def phase(self) -> builtins.str: ...
    @property
    def value_transform(self) -> builtins.str: ...
    @property
    def supports_misbinning_mitigation(self) -> builtins.bool: ...
    @property
    def x_min(self) -> typing.Optional[builtins.float]: ...
    @property
    def x_max(self) -> typing.Optional[builtins.float]: ...
    @property
    def sample_count(self) -> builtins.int: ...
    @property
    def log_x_axis(self) -> builtins.bool: ...
    @property
    def log_y_axis(self) -> builtins.bool: ...
    @property
    def discrete_min_bin_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def discrete_ordering(self) -> typing.Optional[builtins.str]: ...
    @property
    def bins(self) -> builtins.list[HistogramBin]: ...
    @property
    def underflow_bin(self) -> HistogramBin: ...
    @property
    def overflow_bin(self) -> HistogramBin: ...
    @property
    def statistics(self) -> HistogramStats: ...

@typing.final
class HistogramStats:
    @property
    def in_range_entry_count(self) -> builtins.int: ...
    @property
    def nan_value_count(self) -> builtins.int: ...
    @property
    def mitigated_pair_count(self) -> builtins.int: ...

@typing.final
class IntegralEstimate:
    @property
    def neval(self) -> builtins.int: ...
    @property
    def real_zero(self) -> builtins.int: ...
    @property
    def im_zero(self) -> builtins.int: ...
    @property
    def result(self) -> typing.Any: ...
    @property
    def error(self) -> typing.Any: ...
    @property
    def real_chisq(self) -> builtins.float: ...
    @property
    def im_chisq(self) -> builtins.float: ...

@typing.final
class IntegrandActiveThresholdCut:
    @property
    def cut_id(self) -> builtins.int: ...
    @property
    def can_become_pinched(self) -> builtins.bool: ...

@typing.final
class IntegrandCut:
    @property
    def cut_id(self) -> builtins.int: ...
    @property
    def edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def raising_power(self) -> builtins.int: ...
    @property
    def left_thresholds(self) -> builtins.list[IntegrandCutThreshold]: ...
    @property
    def right_thresholds(self) -> builtins.list[IntegrandCutThreshold]: ...

@typing.final
class IntegrandCutThreshold:
    @property
    def esurface_id(self) -> builtins.int: ...
    @property
    def status(self) -> builtins.str: ...
    @property
    def cut_boundary_edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def threshold_boundary_edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def invariant_bound_is_applicable(self) -> builtins.bool: ...

@typing.final
class IntegrandGraph:
    @property
    def graph_id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def is_master(self) -> builtins.bool: ...

@typing.final
class IntegrandGraphGroup:
    @property
    def group_id(self) -> builtins.int: ...
    @property
    def graphs(self) -> builtins.list[IntegrandGraph]: ...
    @property
    def orientation_edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def orientations(self) -> builtins.list[IntegrandOrientation]: ...
    @property
    def loop_momentum_bases(self) -> builtins.list[IntegrandLoopMomentumBasis]: ...
    @property
    def threshold_esurface_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def threshold_esurfaces(self) -> builtins.list[IntegrandThresholdEsurface]: ...
    @property
    def cuts(self) -> builtins.list[IntegrandCut]: ...

@typing.final
class IntegrandInfo:
    @property
    def process_id(self) -> builtins.int: ...
    @property
    def process_name(self) -> builtins.str: ...
    @property
    def integrand_name(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def generation_backend(self) -> builtins.str: ...
    @property
    def generation_compile_options(self) -> typing.Optional[builtins.str]: ...
    @property
    def active_f64_backend(self) -> builtins.str: ...
    @property
    def graph_count(self) -> builtins.int: ...
    @property
    def graph_group_count(self) -> builtins.int: ...
    @property
    def record_size_bytes(self) -> builtins.int: ...
    @property
    def graph_groups(self) -> builtins.list[IntegrandGraphGroup]: ...

@typing.final
class IntegrandLoopMomentumBasis:
    @property
    def basis_id(self) -> builtins.int: ...
    @property
    def channel_id(self) -> typing.Optional[builtins.int]: ...
    @property
    def edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def matches_generation_basis(self) -> builtins.bool: ...

@typing.final
class IntegrandOrientation:
    @property
    def orientation_id(self) -> builtins.int: ...
    @property
    def signature(self) -> builtins.list[builtins.int]: ...

@typing.final
class IntegrandThresholdEsurface:
    @property
    def esurface_id(self) -> builtins.int: ...
    @property
    def representative_graph_id(self) -> builtins.int: ...
    @property
    def edge_ids(self) -> builtins.list[builtins.int]: ...
    @property
    def classification(self) -> typing.Optional[builtins.str]: ...
    @property
    def active_cuts(self) -> builtins.list[IntegrandActiveThresholdCut]: ...

@typing.final
class IntegrationOutput:
    @property
    def workspace_path(self) -> pathlib.Path: ...
    @property
    def result(self) -> IntegrationResult: ...
    @property
    def observables(self) -> dict: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class IntegrationResult:
    @property
    def slots(self) -> builtins.list[SlotIntegrationResult]: ...
    def slot(self, key: builtins.str) -> typing.Optional[SlotIntegrationResult]: ...
    def single_slot(self) -> typing.Optional[SlotIntegrationResult]: ...

@typing.final
class IntegrationStatisticsSnapshot:
    @property
    def num_evals(self) -> builtins.int: ...
    @property
    def average_total_time_seconds(self) -> builtins.float: ...
    @property
    def average_parameterization_time_seconds(self) -> builtins.float: ...
    @property
    def average_integrand_time_seconds(self) -> builtins.float: ...
    @property
    def average_evaluator_time_seconds(self) -> builtins.float: ...
    @property
    def average_observable_time_seconds(self) -> builtins.float: ...
    @property
    def average_integrator_time_seconds(self) -> builtins.float: ...
    @property
    def f64_percentage(self) -> builtins.float: ...
    @property
    def f128_percentage(self) -> builtins.float: ...
    @property
    def arb_percentage(self) -> builtins.float: ...
    @property
    def nan_percentage(self) -> builtins.float: ...
    @property
    def nan_or_unstable_percentage(self) -> builtins.float: ...
    @property
    def generated_event_count(self) -> builtins.int: ...
    @property
    def accepted_event_count(self) -> builtins.int: ...
    @property
    def selection_efficiency_percentage(self) -> typing.Optional[builtins.float]: ...

@typing.final
class IntegrationTableComponentResult:
    @property
    def component(self) -> builtins.str: ...
    @property
    def value(self) -> builtins.float: ...
    @property
    def error(self) -> builtins.float: ...
    @property
    def relative_error_percent(self) -> typing.Optional[builtins.float]: ...
    @property
    def chi_sq_per_dof(self) -> builtins.float: ...
    @property
    def target_delta_sigma(self) -> typing.Optional[builtins.float]: ...
    @property
    def target_delta_percent(self) -> typing.Optional[builtins.float]: ...
    @property
    def max_weight_impact(self) -> builtins.float: ...

@typing.final
class MaxWeightInfoEntry:
    @property
    def component(self) -> builtins.str: ...
    @property
    def sign(self) -> builtins.str: ...
    @property
    def max_eval(self) -> builtins.float: ...
    @property
    def coordinates(self) -> typing.Optional[builtins.str]: ...

@typing.final
class SampleEvaluationResult:
    @property
    def integrand_result(self) -> complex: ...
    @property
    def integrator_weight(self) -> builtins.float: ...
    @property
    def generated_event_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def accepted_event_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def event_processing_time_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def parameterization_jacobian(self) -> typing.Optional[builtins.float]: ...
    @property
    def is_nan(self) -> typing.Optional[builtins.bool]: ...
    @property
    def stability_results(self) -> typing.Optional[builtins.list[StabilityResult]]: ...
    @property
    def event_groups(self) -> builtins.list[EventGroup]: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SettingsValue:
    @property
    def path(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str: ...
    def is_object(self) -> builtins.bool: ...
    def is_array(self) -> builtins.bool: ...
    def is_scalar(self) -> builtins.bool: ...
    def keys(self) -> builtins.list[builtins.str]: ...
    def get(self, path: builtins.str) -> typing.Any: ...
    def to_dict(self) -> typing.Any: ...
    def __getattr__(self, name: builtins.str) -> typing.Any: ...
    def __dir__(self) -> builtins.list[builtins.str]: ...
    def __len__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __getitem__(self, key: typing.Any, /) -> typing.Any: ...

@typing.final
class SlotIntegrationResult:
    @property
    def key(self) -> builtins.str: ...
    @property
    def process(self) -> builtins.str: ...
    @property
    def integrand(self) -> builtins.str: ...
    @property
    def target(self) -> typing.Optional[typing.Any]: ...
    @property
    def integral(self) -> IntegralEstimate: ...
    @property
    def table_results(self) -> builtins.list[IntegrationTableComponentResult]: ...
    @property
    def integration_statistics(self) -> IntegrationStatisticsSnapshot: ...
    @property
    def max_weight_info(self) -> builtins.list[MaxWeightInfoEntry]: ...
    @property
    def grid_breakdown(self) -> ComponentDiscreteBreakdown: ...

@typing.final
class StabilityResult:
    @property
    def precision(self) -> builtins.str: ...
    @property
    def estimated_relative_accuracy(self) -> typing.Optional[builtins.float]: ...
    @property
    def status(self) -> builtins.str: ...
    @property
    def sample_count(self) -> builtins.int: ...
    @property
    def total_time_seconds(self) -> builtins.float: ...

@typing.final
class LogLevel(enum.Enum):
    Off = ...
    r"""
    A level lower than all log levels.
    """
    Error = ...
    r"""
    Corresponds to the `Error` log level.
    """
    Warn = ...
    r"""
    Corresponds to the `Warn` log level.
    """
    Info = ...
    r"""
    Corresponds to the `Info` log level.
    """
    Debug = ...
    r"""
    Corresponds to the `Debug` log level.
    """
    Trace = ...
    r"""
    Corresponds to the `Trace` log level.
    """

def atom_to_canonical_string(atom_str: builtins.str) -> builtins.str:
    r"""
    Parse a Symbolica expression and return its canonical string form.

    Parameters
    ----------
    atom_str : str
        Symbolica expression to parse and normalize.

    Returns
    -------
    str
        The parsed expression in canonical string form.

    Raises
    ------
    Exception
        If ``atom_str`` is not a valid Symbolica expression.

    Examples
    --------
    Normalize a symbolic expression before comparing or storing it::

        atom_to_canonical_string("x + x")
    """

def evaluate_graph_overall_factor(overall_factor: builtins.str) -> builtins.str:
    r"""
    Evaluate a graph's symbolic overall factor and return its canonical form.

    Parameters
    ----------
    overall_factor : str
        Symbolica expression used as the graph's overall factor.

    Returns
    -------
    str
        The evaluated factor in canonical Symbolica form.

    Raises
    ------
    Exception
        If the expression cannot be parsed or evaluated.

    Examples
    --------
    Evaluate the symmetry and fermion-loop factors attached to a graph::

        evaluate_graph_overall_factor(
            "AutG(2)^-1*InternalFermionLoopSign(-1)"
        )
    """

def to_dots(atom_str: builtins.str) -> builtins.str:
    r"""
    Rewrite a Symbolica tensor expression into Idenso dot-product notation.

    Parameters
    ----------
    atom_str : str
        Symbolica tensor expression whose repeated indices encode contractions.

    Returns
    -------
    str
        The equivalent expression using Idenso dot-product notation.

    Raises
    ------
    Exception
        If ``atom_str`` cannot be parsed or converted.

    Examples
    --------
    Rewrite a contraction before passing it to an Idenso workflow::

        to_dots("p(mu) * q(mu)")
    """

