commands = [
    "import model sm-default",
    "import amplitude ./qqx_aaa_pentagon.dot",
    "generate",
    "inspect -m -p 0.1 0.2 0.3",
]


[default_runtime_settings.general]
m_uv = 1.0
mu_r_sq = 8315.251344

[default_runtime_settings.Kinematics]
e_cm = 2.0

[default_runtime_settings.Kinematics.externals]
type = "constant"

[default_runtime_settings.Kinematics.externals.data]
momenta = [
    "dependent",
    [
        1.0,
        0.0,
        0.0,
        1.0,
    ],
    [
        1.0,
        0.0,
        0.0,
        -1.0,
    ],
    [
        0.9903067841547669,
        0.3734458315384239,
        0.6393671561700484,
        -0.657613394982612,
    ],
    [
        0.2053558277500182,
        -0.1412408546154445,
        -0.0869119059139323,
        0.121112995127698,
    ],
]
helicities = [1, 1, -1, -1, -1]

[default_runtime_settings.integrator]
n_increase = 0
n_max = 20000000
discrete_dim_learning_rate = 1.5
continuous_dim_learning_rate = 1.5
max_prob_ratio = 0.01

[default_runtime_settings.stability]
check_on_norm = true
rotation_axis = []

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[cli_settings.global]
display_directive = "debug"
logfile_directive = "debug"

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = true
compile = true

[cli_settings.global.generation.compile]
inline_asm = true
optimization_level = "O3"
