generation:
  compile_cff: true
  numerator_settings:
    eval_settings:
      type: Single
      cpe_rounds: 1
      compile_options:
        subtype: Compiled
    parse_mode: Polynomial
    dump_expression: null
    gamma_algebra: Symbolic
  cpe_rounds_cff: 1
  orientation_pattern:
    pat: null
  compile_separate_orientations: true
  gammaloop_compile_options:
    inline_asm: false
    optimization_level: 3
    fast_math: true
    unsafe_math: false
    compiler: g++
    custom: []
  tropical_subgraph_table_settings:
    panic_on_fail: false
    target_omega: 1.0
    disable_tropical_generation: true
  enable_thresholds: true
  uv_settings:
    generate_integrated: true
