General:
  debug: 0
  use_ltd: false
  load_compiled_cff: false
  load_compiled_separate_orientations: false
Integrand:
  type: unit_volume
  n_3d_momenta: 11
Kinematics:
  e_cm: 64
  externals: 
    type: constant
    momenta:
      - - 2.0
        - 2.0
        - 3.0
        - 4.0
      - - 1.0
        - 2.0
        - 9.0
        - 3.0
Parameterization:
  mode: spherical
  mapping: linear
  b: 1.0
Integrator:
  seed: 69
  n_bins: 64
  bin_number_evolution: null
  min_samples_for_update: 1000
  n_start: 100000
  n_increase: 10000
  n_max: 10000000000
  integrated_phase: real
  discrete_dim_learning_rate: 1.5
  continuous_dim_learning_rate: 1.5
  train_on_avg: false
  show_max_wgt_info: true
  max_prob_ratio: 0.01
Observables: []
Selectors: []
Stability:
  rotation_axis: []
  levels:
  - precision: Double
    required_precision_for_re: 1e-5
    required_precision_for_im: 1e-5
    escalate_for_large_weight_threshold: 0.9
  - precision: Quad
    required_precision_for_re: 1e-5
    required_precision_for_im: 1e-5
    escalate_for_large_weight_threshold: -1.0
sampling: 
  type: default
subtraction:
  sliver_width: 10.0
  dampen_integrable_singularity: false
  dynamic_sliver: false
  integrated_ct_hfunction: 
    function: poly_exponential
    sigma: 1.0
    enabled_dampening: true
    power: null
