= GL638 fixed-count confirmation
<gl638-fixed-count-confirmation>
The joint sampler did #strong[not] confirm a uniform gain over cut sampling. At 163,840 draws per method, composing Cut 1 LU-h focusing with the H/Z map reduced the imaginary-part empirical variance by 35.1%, but increased the real-part variance by 10.8%. Its real standard error is 5.2% worse and its imaginary standard error 19.4% better. The corresponding absolute-component variances show the same pattern. The preselected joint method remains the primary estimate; this result does not justify changing the winner after confirmation.

All 15 fresh runs completed with finite, stable results: five independent seeds (10007, 20011, 30013, 40009, 50021), 32,768 draws each, one iteration, 20 workers, 491,520 draws in total. The #link("GL638_MC_SCREEN.typ")[seven-method screen] fixed the three methods and the common score scales before these results. The interrupted #link("GL638_CONFIRMATION_ROOT.typ")[first attempt] contributes no samples to this table. All physical settings and channel cards remain fixed; `cuts_combined_joint` contains the six cut channels plus the composed Cut 1 LU-h → H/Z channel, without the optional soft LMB. It still includes the standalone Cut 1 sibling.

Means and pooled empirical standard errors below are in #strong[10⁻⁴ pb];. Maxima are absolute real/imaginary signed-component extrema in #strong[pb];, not a global maximum of the complex norm.

#figure(
  align(center)[#table(
    columns: 6,
    align: (auto,right,right,right,right,right,),
    table.header([Method], [Re ± SE], [Abs Re ± SE], [Im ± SE], [Abs Im ± SE], [Max Re / Im (pb)],),
    table.hline(),
    [Optimized LMB], [−2.51161 ± 1.3955], [9.90813 ± 1.3953], [−4.30107 ± 1.8401], [14.9515 ± 1.8398], [18.1509 / 18.9359],
    [Six cut channels], [0.930612 ± 1.0210], [4.14422 ± 1.0210], [0.627503 ± 1.1079], [5.43792 ± 1.1078], [10.4734 / 11.5199],
    [Cuts + composed joint], [1.15444 ± 1.0745], [3.80035 ± 1.0745], [−0.0135545 ± 0.89273], [4.60965 ± 0.89265], [12.2190 / 6.22638],
  )]
  , kind: table
  )

The resulting current #strong[GL638 graph contribution];, rather than the full ttH process cross-section, is

\[ \\operatorname{Re} I=(1.15444\\pm1.07450),10^{-4}\\ \\mathrm{pb},\\qquad \\operatorname{Im} I=(-0.0135545\\pm0.892727),10^{-4}\\ \\mathrm{pb}. \]

These are pooled empirical errors. The five-seed mean-dispersion errors are #strong[1.60928 × 10⁻⁴ pb] for Re and #strong[1.11355 × 10⁻⁴ pb] for Im. Neither error prescription is a calibrated tail-probability statement with five seeds. The largest primary weights alone contribute 48.17% and 18.12% of the empirical sums of squared real and imaginary weights. Those fractions are 63.03%/39.45% for LMB and 39.20%/40.28% for cuts. Rare large contributions still dominate the uncertainty; confident convergence and finite variance remain unestablished. Differences in absolute moments across methods are retained as convergence diagnostics, without claiming that their descriptive standardized differences establish bias.

The screen had selected the composed method with a worst normalized variance score only 0.03947% below direct joint sampling. In confirmation its score is 4947.443, versus 4467.037 for cuts and 8344.468 for LMB, using the original fixed scales. Thus the hoped-for broad improvement over cuts was not reproduced. The #link("LOCAL_CUT_MATCHED_HZ.typ")[two local H/Z approaches] still show finite plateaus for the tested joint paths, down to R ≈ 2.5 × 10⁻⁶ GeV; the composed coefficient there was about 7.9 times smaller than the direct-joint coefficient. That local observation does not cover other tangents, CT-star images, soft limits or Gram degeneracies. The much larger confirmation maxima do not establish a bounded maximum, and the joint real maximum exceeds the cut-only real maximum.

All 60 stored signed extrema replay bit exactly from 48 distinct complete Samples. Their original nested grid probabilities are retained and applied once. Every ordinary replay is stable Double with six physical cuts. Six forced-Arb controls cover the two largest retained complex norms per method. The existing native accuracy audit passes 551 checks, and an independent artifact audit passes 415; the largest ordinary/Arb relative complex error is 1.17633 × 10⁻¹² for totals and 1.17645 × 10⁻¹² for cuts. Six near-zero component-relative diagnostics remain visible under the original norm acceptance criteria. This proves numerical reproduction for the retained controls, not a global weight bound. The primary method\'s actual |Im| maximum at seed 20011 lies outside its top two complex norms. The subsequent #link("GL638_CONFIRMATION_MAXIMUM_PHYSICS.typ")[maximum study] therefore extends the retained controls to four per method, with 605 accuracy checks and 78 checks preserving the original results. It supplies that missing Arb control and traces the three distinct maximum configurations. These include a shared b/c real maximum whose weight increases by exactly 7/6 when the inactive joint channel is added, and imaginary maxima enhanced at projected counterterm points. This attribution is separate from the earlier #link("GL638_MAXIMUM_PHYSICS_ATTRIBUTION.typ")[screen maximum traces];.

The #link("gl638_hosted_joint_gate/mc_confirmation/protocol_build7/provenance.json")[protocol archive] retains the final manifest, frozen selection, 57 validator artifact tests, original analyzer, actual driver/link records and committed source proof. Build7 exactly matches source commit `7818ffcb887aeed4f8fd2baa484897b69603d2af`; the narrow #link("CANONICAL_LU_ENDPOINT_CERTIFICATION.typ")[endpoint certification repair] does not change proposal formulas or physical tolerances. The old preflight and screen remain authenticated historical evidence; all confirmation samples are new runs.

The #link("gl638_hosted_joint_gate/mc_confirmation/results_build7/provenance.json")[result archive] retains all 222 files from the frozen pilot directory, including all 15 complete integration checkpoints. The #link("gl638_hosted_joint_gate/mc_confirmation/analysis_build7/provenance.json")[analysis archive] contains the final numerical report and independent 135-check audit; all 168 reported input hashes and 35 state hashes agree. The #link("gl638_hosted_joint_gate/mc_confirmation/maximum_build7/provenance.json")[maximum archive] retains original Samples, aliases, native controls and exact audit reproduction. All 222 input hashes are unchanged before and after replay. Raw artifacts are losslessly gzipped and identical prior settings/source bytes are referenced by hash; no generated-process saved-state payload or executable is copied.

Execution used the sourced development environment and supplied license, with `GL_DISPLAY_FILTER=off`; confirmation used `RAYON_NUM_THREADS=20` and maximum replay used one worker. Their respective whole-process elapsed times were 3820.512 s and 138.612 s, with peak RSS 69,037,992 KiB and 6,194,220 KiB. These are provenance, not a new performance comparison. Exact commands and original paths are in the archived run records. Reproduction restores the original logical files through `artifact_hashes.json`, uses the archived analyzer/protocol and runs the existing maximum auditor after statistics are frozen. No old partial results, local ray points or screen samples enter the confirmation estimate.
