ty = "native"

[options]
use_simd = true
use_threads = false
cse = false
fastmath = false
complex = false
symbolica = true
simd_branch = false
compact = true
compress = false
direct = false
fast_complex = true
huge = false
opt_level = 2

[debug]
bytecode = false
scalar = false
simd = false
stats = false
