commands = ["run generate_grouped_diagrams generate_gl000_integrand integrate_gl000"]

[cli_settings]
override_state = true

[cli_settings.state]
name = "aa_aa_3L_grouped_gl000"
folder = "./examples/3L/gammaloop_state"

[cli_settings.global]
display_directive = "info"
logfile_directive = "info"

[cli_settings.global.log_style]
include_fields = true
full_line_source = true
log_format = "Full"
short_timestamp = true

[cli_settings.global.generation]
override_lmb_heuristics = false

[cli_settings.global.generation.uv]
softct = false
generate_integrated = false
subtract_uv = false
final_integrand = "ThreeD"
add_marker = false
keep_marker = true
inner_products = true
orchestrator = "legacy_dag_forest"

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = false
store_atom = false
compile = false
summed = false
summed_function_map = false
direct_translation = true
horner_iterations = 5
cpe_iterations = 5

[cli_settings.global.generation.threshold_subtraction]
enable_thresholds = false
check_esurface_at_generation = false

[cli_settings.global.generation.tropical_subgraph_table]
panic_on_fail = true
disable_tropical_generation = true

[cli_settings.global.n_cores]
feyngen = 10
generate = 10
compile = 1
integrate = 20

[[command_blocks]]
name = "generate_grouped_diagrams"
commands = [
  "import model sm-default.json",
  "set global kv global.n_cores.feyngen=10",
  "remove processes -p aa_aa",
  """generate amp a a > a a | a t t~ g ghG ghG~ QCD==4 QED==4 [{3}]
        --numerator-grouping group_identical_graphs_up_to_scalar_rescaling
        --number-of-samples-for-numerator-comparisons 1
        --fully-numerical-substitution-when-comparing-numerators=true
        --compare-canonized-numerator=false
        --symmetrize-initial-states=true --symmetrize-final-states=true
        -p aa_aa -i 3L --only-diagrams""",
  "save dot ./examples/3L/graphs_grouped",
]

[[command_blocks]]
name = "generate_gl000_integrand"
commands = [
  "remove processes -p aa_aa_gl000",
  "import graphs ./examples/3L/graphs_grouped/processes/amplitudes/aa_aa/3L/GL000.dot -p aa_aa_gl000 -i 3L -o",
  "generate existing -p aa_aa_gl000 -i 3L",
]

[[command_blocks]]
name = "integrate_gl000"
commands = [
  "run set_model_parameters",
  "run set_kinematics_a",
  "set process -p aa_aa_gl000 kv kinematics.externals.data.helicities=[+1,-1,+1,-1]",
  "set process -p aa_aa_gl000 kv general.mu_r=91.188 general.m_uv=9.188 general.evaluator_method=\"SingleParametric\"",
  "set process -p aa_aa_gl000 kv integrator.n_increase=0 integrator.n_start=20 integrator.n_max=20 integrator.seed=1337 integrator.integrated_phase=\"real\" integrator.target_relative_accuracy=1.0",
  """set process -p aa_aa_gl000 string '
        [sampling]
        graphs = "monte_carlo"
        orientations = "monte_carlo"
        lmb_multichanneling = true
        lmb_channels = "monte_carlo"
        lmb_channel_weight = "inverse_jacobian"
        coordinate_system = "spherical"
        mapping = "linear"
        b = 1.0
    '""",
  """integrate -p aa_aa_gl000 -i 3L
             --n-cores 20
             --workspace-path /tmp/aa_aa_3l_grouped_gl000_workspace
             --renderer tabled
             --batch-size 1
             --show-phase both
             --show-max-weight-info
             --show-top-discrete-grid
             --show-discrete-contributions-sum
             --write-results-for-each-iteration
             --restart
    """,
  "quit",
]

[[command_blocks]]
name = "set_model_parameters"
commands = [
  "set model MT=173.0",
  "set model WT=0.0",
  "set model ymt=173.0",
  "set model aS=0.118",
  "set model aEWM1=137.036",
  "set model Gf=1.166390e-05",
  "set model MZ=91.188",
]

[[command_blocks]]
name = "set_kinematics_a"
commands = [
  # s / m_t^2 = 1, u / s = -0.3
  """set process -p aa_aa_gl000 string '
    [kinematics.externals]
    type = "constant"
    [kinematics.externals.data]
    momenta = [
        [ 86.5, 0.0, 0.0, 86.5 ],
        [ 86.5, 0.0, 0.0, -86.5 ],
        [ 86.5, 0.0, -79.27855952273603, -34.6 ],
        "dependent"
    ]
    '""",
]

[default_runtime_settings.kinematics]
e_cm = 300.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
  [86.5, 0.0, 0.0, 86.5],
  [86.5, 0.0, 0.0, -86.5],
  [86.5, 0.0, -79.27855952273603, -34.6],
  "dependent",
]
helicities = [+1, -1, +1, -1]

[default_runtime_settings.general]
evaluator_method = "SingleParametric"
enable_cache = false
debug_cache = false
generate_events = false
store_additional_weights_in_event = false
integral_unit = "none"
mu_r = 91.188
m_uv = 9.188

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.sampling]
graphs = "monte_carlo"
orientations = "monte_carlo"
lmb_multichanneling = true
lmb_channels = "monte_carlo"
lmb_channel_weight = "inverse_jacobian"
coordinate_system = "spherical"
mapping = "linear"
b = 1.0

[default_runtime_settings.integrator]
n_start = 20
n_increase = 0
n_max = 20
integrated_phase = "real"
target_relative_accuracy = 1.0
seed = 1337
