#:schema https://raw.githubusercontent.com/alphal00p/gammaloop/8f2c4def42f0c41341d450f09fb53e7fa82fbf1e/assets/schemas/runtime.json
[general]
m_uv = 50.0
renormalization_localization_scale = 600.0
mu_r = 91.188
integral_unit = "picobarn"

[kinematics]
e_cm = 600.0

[kinematics.externals]
type = "constant"

[kinematics.externals.data]
momenta = [
    [
    300.0,
    0.0,
    0.0,
    300.0,
],
    [
    300.0,
    0.0,
    0.0,
    -300.0,
],
]
helicities = [
    "summed_averaged",
    "summed_averaged",
]

[integrator]
n_bins = 16
min_samples_for_update = 64
n_start = 81920
n_increase = 0
discrete_dim_learning_rate = 0.25
continuous_dim_learning_rate = 0.25
seed = 62001

[stability]
integrated_energy_dimension = -2
check_on_norm = false
min_abs_wgt_for_escalation = 0.000000000001

[[stability.levels]]
precision = "Double"
required_precision_for_re = 0.000001
required_precision_for_im = 0.000001
escalate_for_large_weight_threshold = 0.9

[[stability.levels]]
precision = "Quad"
required_precision_for_re = 0.0000000001
required_precision_for_im = 0.0000000001
escalate_for_large_weight_threshold = -1.0

[[stability.levels]]
precision = "Arb"
required_precision_for_re = 0.000000000001
required_precision_for_im = 0.000000000001
ecm_relative_tolerance_for_re = 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
escalate_for_large_weight_threshold = -1.0

[sampling]
graphs = "monte_carlo"
sampling_multichanneling = true
sampling_channels = "monte_carlo"
b = 0.3
power = 2.0
default_channel_selection = ["auto:optimized_lmb"]

[sampling.channel_selection]
GL638 = [
    "auto:optimized_lmb",
    "lu_cut_0",
    "lu_cut_1",
    "lu_cut_2",
    "lu_cut_3",
    "lu_cut_4",
    "lu_cut_5",
    "cut1_joint_HZ",
    "cut3_right_5_10",
    "cut1_left_7_8_and_Z",
]

[sampling.channel_definitions.GL638.cut1_joint_HZ]
around = "then(block(lmb(6,10),phase_space(cut(2,6,10))),complement(7),block(lmb(3),at_cut(cut(2,6,10),intersect(surface(2,4,12),surface(3,10,13)))))"
subspace_lmb = []
parent_lmb = [
    3,
    6,
    7,
    10,
]
on_cut = [1]

[sampling.channel_definitions.GL638.cut1_joint_HZ.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.cut1_left_7_8_and_Z]
around = "then(block(lmb(6,10),phase_space(cut(2,6,10))),block(lmb(7),at_cut(cut(2,6,10),surface(7,8))),block(lmb(3),at_cut(cut(2,6,10),surface(3,10,13))))"
subspace_lmb = []
parent_lmb = [
    3,
    6,
    7,
    10,
]
on_cut = [1]

[sampling.channel_definitions.GL638.cut1_left_7_8_and_Z.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.cut3_right_5_10]
around = "then(block(lmb(4,12),phase_space(cut(2,4,12))),complement(7),block(lmb(5),at_cut(cut(2,4,12),surface(5,10))))"
subspace_lmb = []
parent_lmb = [
    4,
    5,
    7,
    12,
]
on_cut = [3]

[sampling.channel_definitions.GL638.cut3_right_5_10.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_0]
around = "phase_space(cut(2,6,12,13))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [0]

[sampling.channel_definitions.GL638.lu_cut_0.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_1]
around = "phase_space(cut(2,6,10))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [1]

[sampling.channel_definitions.GL638.lu_cut_1.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_2]
around = "phase_space(cut(2,6,7,13,14))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [2]

[sampling.channel_definitions.GL638.lu_cut_2.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_3]
around = "phase_space(cut(2,4,12))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [3]

[sampling.channel_definitions.GL638.lu_cut_3.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_4]
around = "phase_space(cut(2,4,10,13))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [4]

[sampling.channel_definitions.GL638.lu_cut_4.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[sampling.channel_definitions.GL638.lu_cut_5]
around = "phase_space(cut(2,4,7,14))"
subspace_lmb = [
    3,
    4,
    7,
    10,
]
parent_lmb = [
    3,
    4,
    7,
    10,
]
on_cut = [5]

[sampling.channel_definitions.GL638.lu_cut_5.radial_profile]
kind = "lu_h"
broad_fraction = 0.02

[subtraction]
esurface_existence_threshold = 0.00000000000001

[h_function]
power = 3
