commands = [
  "import model sm-default",
  "import graphs ./integration-tests/resources/graphs/physical_2L_6photons.dot",
  "generate"
]

[default_runtime_settings.general]
m_uv = 1.0
mu_r_sq = 8315.251344
enable_cache = false

[default_runtime_settings.kinematics]
e_cm = 1000.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
  [
    500.0,
    0.0,
    -300.0,
    400.0,
  ],
  [
    500.0,
    0.0,
    300.0,
    -400.0,
  ],
  [
    88.55133305450298,
    -22.10069028768998,
    40.08035319168533,
    -75.80543095693663,
  ],
  [
    328.3294192270985,
    -103.8496118834563,
    -301.9337553895401,
    76.49492138716589,
  ],
  [
    152.3581094674306,
    -105.8809596665922,
    -97.7096383269757,
    49.54838522679282,
  ],
  "dependent",
]
helicities = [
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
]

[default_runtime_settings.integrator]
n_increase = 0
n_start = 100000
n_max = 100000
discrete_dim_learning_rate = 0.5
continuous_dim_learning_rate = 0.5
max_prob_ratio = 100.0

[default_runtime_settings.stability]
check_on_norm = true
rotation_axis = []

[[default_runtime_settings.stability.levels]]
precision = "Double"
required_precision_for_re = 0.00000001
required_precision_for_im = 0.00000001
escalate_for_large_weight_threshold = 0.9

[[default_runtime_settings.stability.levels]]
precision = "Quad"
required_precision_for_re = 0.00001
required_precision_for_im = 0.00001
escalate_for_large_weight_threshold = -1.0

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.sampling]
type = "default"
mode = "spherical"
mapping = "linear"
b = 10.0

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = false
compile = false
