commands = [
    "set default-runtime kv subtraction.disable_threshold_subtraction=true",
    "set global kv global.generation.threshold_subtraction.enable_thresholds=false",
    "import model sm-default",
    "import graphs ./dot_graphs/loop_graphs/qqx_aaa_subtracted.dot",
    "generate",
    "inspect -m -x 0.1 0.2 0.3",
	"quit -o"
]


[default_runtime_settings.general]
m_uv = 1.0
mu_r_sq = 8315.251344

[default_runtime_settings.kinematics]
e_cm = 2.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
    "dependent",
    [
        1.0,
        0.0,
        0.0,
        1.0,
    ],
    [
        1.0,
        0.0,
        0.0,
        -1.0,
    ],
    [
        0.9903067841547669,
        0.3734458315384239,
        0.6393671561700484,
        -0.657613394982612,
    ],
    [
        0.2053558277500182,
        -0.1412408546154445,
        -0.0869119059139323,
        0.121112995127698,
    ],
]
helicities = [1, 1, -1, -1, -1]

[default_runtime_settings.integrator]
n_increase = 0
n_max = 1000000
discrete_dim_learning_rate = 1.5
continuous_dim_learning_rate = 1.5
max_prob_ratio = 0.01

[default_runtime_settings.stability]
check_on_norm = true
rotation_axis = []

[cli_settings.global]
display_directive = "gammalooprs=info"
logfile_directive = "gammalooprs=debug"

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = true
compile = true

[cli_settings.global.generation.compile]
inline_asm = true
optimization_level = "O3"
