commands = []

[[command_blocks]]
name = "generate"
commands = [
  "import model sm-default",
  "remove processes",
  "import graphs ./tests/resources/graphs/local_ir_quark_self_energy.dot -p local_ir_quark_self_energy -i local_ir_quark_self_energy",
  "generate existing -p local_ir_quark_self_energy -i local_ir_quark_self_energy",
]

[[command_blocks]]
name = "profile_uv"
commands = [
  "profile ultra-violet -p local_ir_quark_self_energy -i local_ir_quark_self_energy --min-scaling 8 --max-scaling 12 --n-points 25 --seed 1337 --per-orientation",
]

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
  [0.2, 0.0, 0.0, 0.2],
  "dependent",
]
helicities = [1, 1]

[default_runtime_settings.general]
evaluator_method = "SingleParametric"

[cli_settings.global]
logfile_directive = "off"
display_directive = "info"

[cli_settings.global.generation.uv]
generate_integrated = false
add_marker = false
inner_products = true
orchestrator = "compare"

[[cli_settings.global.generation.uv.renormalization_prescription.overrides]]
prescription = "IR"

[cli_settings.global.generation.uv.renormalization_prescription.overrides.ct_identifier]
external_pdg_set = [-1, 1]
internal_pdg_set = [1, 21]

[cli_settings.global.generation.tropical_subgraph_table]
panic_on_fail = false
disable_tropical_generation = true

[cli_settings.global.generation.threshold_subtraction]
enable_thresholds = false
