use idenso::{
    color::{ColorSimplifier, ColorSimplifySettings},
    dirac::GammaSimplifier,
    shorthands::metric::MetricSimplifier,
};
use linnet::{
    half_edge::{
        HedgeGraph,
        involution::{Flow, HedgePair},
        subgraph::SubSetLike,
    },
    parser::{DotEdgeData, DotGraph, DotHedgeData, DotVertexData},
};
use spenso::shadowing::symbolica_utils::SpensoPrintSettings;
use symbolica::atom::AtomCore;

use crate::{
    graph::Graph,
    processes::DotExportSettings,
    utils::{GS, W_},
    uv::UltravioletGraph,
};

use super::{
    ParseGraph,
    string_utils::{ToQuoted, dot_statement_value},
};

impl Graph {
    pub fn to_dot_graph_with_settings(&self, settings: &DotExportSettings) -> DotGraph {
        let mut dotgraph = if settings.split_xs_by_initial_states {
            self.to_split_dotgraph_with_autogenerated_fields(settings.include_autogenerated_fields)
        } else {
            self.to_dot_graph_with_autogenerated_fields(settings.include_autogenerated_fields)
        };

        if settings.output_full_numerator {
            let mut num = (self
                .numerator(&self.full_filter(), &self.empty_subgraph())
                .get_single_atom()
                .unwrap()
                * &self.global_prefactor.num
                * &self.global_prefactor.projector
                * &self.overall_factor)
                .simplify_metrics();

            if settings.do_color_algebra {
                num = num.simplify_color_with(
                    ColorSimplifySettings::default().with_cof_dimension_invariants(),
                );
            }

            if settings.do_gamma_algebra {
                num = num.simplify_gamma();
                crate::debug_tags!(#generation, #graph, #inspect, #dump;
                    stage = "graph_serialization_after_simplify_gamma",
                    log.after_gamma = num,
                    "Graph serialization after gamma simplification"
                );
            }

            dotgraph.global_data.statements.insert(
                "full_num".into(),
                dot_statement_value(
                    &num.printer(SpensoPrintSettings::typst_options())
                        .to_string(),
                ),
            );
        }

        dotgraph
    }

    pub fn to_split_dotgraph(&self) -> DotGraph {
        self.to_split_dotgraph_with_autogenerated_fields(false)
    }

    fn to_split_dotgraph_with_autogenerated_fields(
        &self,
        include_autogenerated_fields: bool,
    ) -> DotGraph {
        let global_data = self.global_data(include_autogenerated_fields);

        let mut graph: HedgeGraph<DotEdgeData, DotVertexData, DotHedgeData> =
            if self.initial_state_cut.is_empty() {
                self.underlying.map_data_ref(
                    |_, _, v| v.to_dot_data(include_autogenerated_fields),
                    |_, _, p, e| {
                        if let HedgePair::Unpaired { flow, .. } = p {
                            e.map(|e| {
                                let mut dot = e.to_dot_data(include_autogenerated_fields);
                                match flow {
                                    Flow::Source => {
                                        dot.add_statement("pin", "x:@+right".to_string());
                                    }
                                    Flow::Sink => {
                                        dot.add_statement("pin", "x:@-left".to_string());
                                    }
                                }
                                dot
                            })
                        } else {
                            e.map(|e| e.to_dot_data(include_autogenerated_fields))
                        }
                    },
                    |_, d| d.into(),
                )
            } else {
                self.initial_state_cut
                    .clone()
                    .to_owned_graph_ref(&self.underlying)
                    .map(
                        |_, _, v| v.to_dot_data(include_autogenerated_fields),
                        |_, _, p, _, e| {
                            e.map(|e| {
                                let mut dot =
                                    e.edge_data().to_dot_data(include_autogenerated_fields);

                                match e.flow() {
                                    Some(Flow::Source) => {
                                        dot.add_statement("is_cut", self.inv(p.any_hedge()));
                                        dot.add_statement(
                                            "pin",
                                            format!("x:@+right,y:@edge{}", e.index),
                                        );
                                    }
                                    Some(Flow::Sink) => {
                                        dot.add_statement("is_cut", p.any_hedge());
                                        dot.add_statement(
                                            "pin",
                                            format!("x:@-left,y:@edge{}", e.index),
                                        );
                                    }
                                    None => {}
                                }
                                dot
                            })
                        },
                        |_, d| d.into(),
                    )
            };

        // self.normal_emr_replacement(subgraph, lmb, rep_args, filter_pair)
        for (_, i, _) in self.iter_edges() {
            let loop_expr = self
                .loop_momentum_basis
                .loop_atom(i, GS.loop_mom, &[W_.a___], false);
            let external_expr =
                self.loop_momentum_basis
                    .ext_atom(i, GS.external_mom, &[W_.a___], false);

            graph[i].add_statement("lmb_rep", (loop_expr + external_expr).to_quoted());
        }

        for (l, i) in self.loop_momentum_basis.loop_edges.iter_enumerated() {
            graph[i].0.add_statement("lmb_id", l);
        }

        DotGraph { global_data, graph }
    }

    fn to_dot_graph_with_autogenerated_fields(
        &self,
        include_autogenerated_fields: bool,
    ) -> DotGraph {
        let global_data = self.global_data(include_autogenerated_fields);

        let mut graph: HedgeGraph<DotEdgeData, DotVertexData, DotHedgeData> =
            self.underlying.map_data_ref(
                |_, _, v| v.to_dot_data(include_autogenerated_fields),
                |_, _, _, e| e.map(|e| e.to_dot_data(include_autogenerated_fields)),
                |_, d| d.into(),
            );

        for (_, i, _) in self.iter_edges() {
            let loop_expr = self
                .loop_momentum_basis
                .loop_atom(i, GS.loop_mom, &[W_.a___], false);
            let external_expr =
                self.loop_momentum_basis
                    .ext_atom(i, GS.external_mom, &[W_.a___], false);

            graph[i].add_statement("lmb_rep", (loop_expr + external_expr).to_quoted());
        }

        for i in self.initial_state_cut.left.included_iter() {
            let eid = graph[&i];
            graph[eid].add_statement("is_cut", i);
        }

        for (l, i) in self.loop_momentum_basis.loop_edges.iter_enumerated() {
            graph[i].0.add_statement("lmb_id", l);
        }

        DotGraph { global_data, graph }
    }
}

impl From<&Graph> for DotGraph {
    fn from(value: &Graph) -> Self {
        value.to_dot_graph_with_autogenerated_fields(false)
    }
}

impl From<&ParseGraph> for DotGraph {
    fn from(value: &ParseGraph) -> Self {
        let global_data = value.global_data();
        let graph: HedgeGraph<DotEdgeData, DotVertexData, DotHedgeData> = value.graph.map_data_ref(
            |_, _, v| v.into(),
            |_, _, _, e| e.map(|e| e.into()),
            |_, d| d.into(),
        );

        DotGraph { global_data, graph }
    }
}

impl ParseGraph {
    #[allow(dead_code)]
    fn to_simple_dot(&self) -> DotGraph {
        let global_data = self.global_data();
        let graph: HedgeGraph<DotEdgeData, DotVertexData, DotHedgeData> = self.graph.map_data_ref(
            |_, _, v| v.into(),
            |_, _, _, e| e.map(|e| e.into()),
            |_, d| d.into(),
        );

        DotGraph { global_data, graph }
    }
}

#[cfg(test)]
mod tests {
    use linnet::half_edge::involution::EdgeIndex;
    use symbolica::{atom::Atom, function};

    use super::Graph;
    use crate::{
        dot,
        graph::{
            autogen::Autogen,
            parse::IntoGraph,
            threshold_counterterms::{
                THRESHOLD_COUNTERTERM_SCHEMA_VERSION, ThresholdCountertermCut,
                ThresholdCountertermMultiplier, ThresholdCountertermSpec,
                ThresholdCountertermThreshold, ThresholdCountertermVariant,
            },
        },
        initialisation::test_initialise,
        processes::DotExportSettings,
        utils::{GS, load_generic_model},
    };

    #[test]
    fn full_numerator_is_a_spenso_aware_typst_fragment() {
        let graph: Graph = dot!(digraph G {
            ext [style=invis]
            node [num=1]
            ext -> A
            C -> A
            A -> D
            D -> B
            B -> C
            C -> D
            B -> ext
        })
        .unwrap();
        let graph = graph.with_global_numerator_only(
            "typst_full_num".to_string(),
            function!(GS.uv_truncate, Atom::num(1)),
        );
        let dot = graph.to_dot_graph_with_settings(&DotExportSettings {
            output_full_numerator: true,
            ..DotExportSettings::default()
        });
        let full_num = &dot.global_data.statements["full_num"];

        assert_eq!(full_num, r#"op(\"Tr\")(1)"#);
        assert!(!full_num.contains("gammalooprs::Truncate"));
    }

    fn triangle() -> Graph {
        test_initialise().unwrap();
        dot!(digraph threshold_counterterm_roundtrip {
            edge [pdg=1000]
            ext [style=invis]
            ext -> v4 [id=0]
            v5 -> ext [id=1]
            v6 -> ext [id=2]
            v4 -> v5 [id=3, lmb_id=0]
            v5 -> v6 [id=4]
            v6 -> v4 [id=5]
        }, "scalars")
        .unwrap()
    }

    #[test]
    fn generated_threshold_counterterms_are_exported_only_when_requested() {
        let graph = triangle();
        assert!(graph.threshold_counterterms.autogenerated);
        assert_eq!(
            graph.threshold_counterterms.value,
            ThresholdCountertermSpec::default()
        );

        let ordinary = graph.dot_serialize(&DotExportSettings::default());
        assert!(!ordinary.contains("threshold_counterterms"));

        let normalized = graph.dot_serialize(&DotExportSettings {
            include_autogenerated_fields: true,
            ..DotExportSettings::default()
        });
        assert!(normalized.contains("threshold_counterterms"));

        let reparsed: Graph = normalized
            .into_graph(&load_generic_model("scalars"))
            .unwrap();
        assert!(!reparsed.threshold_counterterms.autogenerated);
        assert_eq!(
            reparsed.threshold_counterterms.value,
            ThresholdCountertermSpec::default()
        );
        assert!(reparsed.threshold_counterterms.is_legacy_equivalent());
    }

    #[test]
    fn explicit_threshold_counterterms_round_trip_embedded_strings() {
        let mut graph = triangle();
        let spec = ThresholdCountertermSpec {
            schema_version: THRESHOLD_COUNTERTERM_SCHEMA_VERSION,
            cuts: vec![ThresholdCountertermCut {
                edges: vec![],
                thresholds: vec![ThresholdCountertermThreshold {
                    edges: vec![EdgeIndex(4), EdgeIndex(5)],
                    counterterms: vec![ThresholdCountertermVariant {
                        name: Some("quoted \"variant\" η".to_string()),
                        subspace: Some(vec![EdgeIndex(3)]),
                        parent_lmb: None,
                        disable: false,
                        multiplier: Some(ThresholdCountertermMultiplier {
                            expression: "custom(\"η\", \\path, tab:\t, line:\n)".to_string(),
                            symmetrize: true,
                            opaque_derivatives: true,
                        }),
                    }],
                }],
            }],
        };
        graph.threshold_counterterms = Autogen::explicit(spec.clone());

        let serialized = graph.dot_serialize(&DotExportSettings::default());
        assert!(serialized.contains("threshold_counterterms"));

        let reparsed: Graph = serialized
            .into_graph(&load_generic_model("scalars"))
            .unwrap();
        assert!(!reparsed.threshold_counterterms.autogenerated);
        assert_eq!(reparsed.threshold_counterterms.value, spec);
    }
}
