#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
invocation_dir=$(pwd -P)
if [[ -n ${1-} ]]; then
    case $1 in
        /*) output_dir=$1 ;;
        *) output_dir="$invocation_dir/$1" ;;
    esac
else
    output_dir="$repo_root/docs/assets/graphs"
fi

work_dir=$(mktemp -d "${TMPDIR:-/tmp}/gammaloop-portal-graphs.XXXXXX")
state_dir="$work_dir/state"
export_dir="$work_dir/export"
render_dir="$work_dir/rendered"
trap 'rm -rf -- "$work_dir"' EXIT

mkdir -p "$output_dir" "$render_dir"
output_dir=$(CDPATH= cd -- "$output_dir" && pwd -P)
cd "$repo_root"

case $(typst --version) in
    "typst 0.15."*) ;;
    *)
        printf 'portal graph rendering requires Typst 0.15.x\n' >&2
        exit 1
        ;;
esac

# `save dot` is the source of the drawing bundle. In particular, this creates
# the current GammaLoop figure/layout templates, matching Linnest and Kurvst
# packages, and the Standard Model-specific edge-style map.
cargo_profile_args=()
if [[ -n ${ALPHAL00P_DOCS_CARGO_PROFILE-} ]]; then
    cargo_profile_args=(--profile "$ALPHAL00P_DOCS_CARGO_PROFILE")
fi
command_export_dir=${export_dir//\\/\\\\}
command_export_dir=${command_export_dir//\"/\\\"}
cargo run --quiet --locked "${cargo_profile_args[@]}" -p gammaloop-api --bin gammaloop -- \
    --clean-state \
    -s "$state_dir" \
    -n \
    run \
    -c "import model sm-default; import graphs ./examples/cli/aa_aa/3L/graphs/processes/amplitudes/aa_aa/3L/GL000.dot; save dot \"$command_export_dir\""

for template in figure.typ layout.typ edge-style.typ; do
    test -f "$export_dir/drawings/templates/$template" || {
        printf 'save dot did not create %s\n' "$template" >&2
        exit 1
    }
done

# These are process outputs and test fixtures already used by GammaLoop. The
# directory family is retained so the generated template selects amplitude or
# cross-section placement exactly as it does for normal `save dot` output.
graphs=(
    "aa-2l-gl00|amplitudes|examples/cli/aa_aa/2L/graphs/GL00.dot"
    "aa-2l-gl08|amplitudes|examples/cli/aa_aa/2L/graphs/GL08.dot"
    "aa-3l-gl000|amplitudes|examples/cli/aa_aa/3L/graphs/processes/amplitudes/aa_aa/3L/GL000.dot"
    "aa-3l-gl150|amplitudes|examples/cli/aa_aa/3L/graphs/processes/amplitudes/aa_aa/3L/GL150.dot"
    "aa-3l-gl300|amplitudes|examples/cli/aa_aa/3L/graphs/processes/amplitudes/aa_aa/3L/GL300.dot"
    "gg-hhh-3l|amplitudes|examples/cli/gg_hhh/3L/3L_graph.dot"
    "gg-hhh-1l|amplitudes|tests/resources/graphs/gghhh.dot"
    "qq-aaa-pentabox|amplitudes|tests/resources/graphs/qqx_aaa_pentabox_user_numerator.dot"
    "ad-ad-gluon|amplitudes|tests/resources/graphs/uv_tests/ad_ad_1L_gluon.dot"
    "epem-bbx|amplitudes|tests/resources/graphs/uv_tests/epem_a_bbx.dot"
    "epem-ttbar-cut|cross_sections|tests/resources/graphs/epemttbar.dot"
)

for graph in "${graphs[@]}"; do
    IFS='|' read -r name family source <<<"$graph"
    install -Dm644 "$source" "$export_dir/processes/$family/portal/default/$name.dot"
done

# The website variants only remove the automatic graph title and opaque page;
# all topology layout, particle styling, and drawing callbacks remain those
# generated by `save dot`. The dark copy remaps the generated model palette to
# the portal's dark ink colours.
for theme in light dark; do
    cp "$export_dir/drawings/templates/figure.typ" \
        "$export_dir/drawings/templates/portal-figure-$theme.typ"
    cp "$export_dir/drawings/templates/layout.typ" \
        "$export_dir/drawings/templates/portal-layout-$theme.typ"

    sed -i \
        "s/#import \"layout.typ\": layout/#import \"portal-layout-$theme.typ\": layout/" \
        "$export_dir/drawings/templates/portal-figure-$theme.typ"
    sed -i \
        's/#set page(width: auto, height: auto, margin: (x: 2mm, y: 2mm))/#set page(width: auto, height: auto, margin: (x: 2mm, y: 2mm), fill: none)/' \
        "$export_dir/drawings/templates/portal-figure-$theme.typ"
    sed -i 's/title: auto,/title: none,/' \
        "$export_dir/drawings/templates/portal-layout-$theme.typ"
    sed -i '/title: none,/a\      node-fill: none,' \
        "$export_dir/drawings/templates/portal-layout-$theme.typ"

    grep -Fq "#import \"portal-layout-$theme.typ\": layout" \
        "$export_dir/drawings/templates/portal-figure-$theme.typ"
    grep -Fq 'fill: none' \
        "$export_dir/drawings/templates/portal-figure-$theme.typ"
    grep -Fq 'title: none,' \
        "$export_dir/drawings/templates/portal-layout-$theme.typ"
    grep -Fq 'node-fill: none,' \
        "$export_dir/drawings/templates/portal-layout-$theme.typ"
done

cp "$export_dir/drawings/templates/edge-style.typ" \
    "$export_dir/drawings/templates/edge-style-dark.typ"
sed -i \
    -e 's/c: black/c: rgb("#f8effa")/g' \
    -e 's/c: blue/c: rgb("#d8b9e3")/g' \
    "$export_dir/drawings/templates/edge-style-dark.typ"
sed -i \
    's/#import "edge-style.typ" as edge-style/#import "edge-style-dark.typ" as edge-style/' \
    "$export_dir/drawings/templates/portal-layout-dark.typ"
sed -i \
    '/#set page(width: auto, height: auto, margin: (x: 2mm, y: 2mm), fill: none)/a\#set text(fill: rgb("#f8effa"))' \
    "$export_dir/drawings/templates/portal-figure-dark.typ"
grep -Fq '#import "edge-style-dark.typ" as edge-style' \
    "$export_dir/drawings/templates/portal-layout-dark.typ"
grep -Fq '#set text(fill: rgb("#f8effa"))' \
    "$export_dir/drawings/templates/portal-figure-dark.typ"

render() {
    local name=$1
    local family=$2
    local theme=$3
    local destination="$render_dir/portal-graph-$name-$theme.svg"
    typst compile \
        --root "$export_dir" \
        --format svg \
        --creation-timestamp 0 \
        --input "data-path=../../processes/$family/portal/default/$name.dot" \
        --input steps=1200 \
        --input seed=42 \
        "$export_dir/drawings/templates/portal-figure-$theme.typ" \
        "$destination"
    if [[ $theme == dark ]]; then
        # Fermion arrow marks are supplied by Linnest rather than the generated
        # model map, so adapt their remaining default black paint as well.
        sed -i 's/#000000/#f8effa/g' "$destination"
    fi
}

# Typst's layout plugin is CPU-bound, so keep a small batch in flight while
# avoiding a memory spike on developer machines and CI runners.
pids=()
render_status=0
for graph in "${graphs[@]}"; do
    IFS='|' read -r name family _source <<<"$graph"
    for theme in light dark; do
        render "$name" "$family" "$theme" &
        pids+=("$!")
        if (( ${#pids[@]} == 4 )); then
            for pid in "${pids[@]}"; do
                if ! wait "$pid"; then
                    render_status=1
                fi
            done
            (( render_status == 0 )) || exit "$render_status"
            pids=()
        fi
    done
done
for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
        render_status=1
    fi
done
(( render_status == 0 )) || exit "$render_status"

for graph in "$render_dir"/*.svg; do
    install -m644 "$graph" "$output_dir/$(basename -- "$graph")"
done
