use super::*;
use crate::initialisation::test_initialise;

#[test]
fn unchanged_flow_clone_preserves_reparsed_graph_state() {
    test_initialise().unwrap();
    let model = crate::utils::load_generic_model("scalars");
    let process = ProcessDefinition {
        final_pdgs_lists: vec![vec![]],
        ..Default::default()
    };
    let mut graph = SymbolicaGraph::new();
    for _ in 0..2 {
        graph.add_node(NodeColorWithVertexRule::from_particles(
            ["scalar_0"; 3],
            &model,
        ));
    }
    for _ in 0..3 {
        graph.add_edge(0, 1, true, EdgeColor { pdg: 1000 }).unwrap();
    }
    let (normalized, _) = process.normalize_flows(&graph, &model).unwrap();
    assert_eq!(graph, normalized);

    let mut parsed =
        ParseGraph::from_symbolica_graph(&model, "", &graph, parse!("7/3*AutG(2)"), &[]).unwrap();
    parsed.global_data.num = parse!("flow_state_x+1");
    parsed.global_data.projectors = Some(parse!("flow_state_y"));
    parsed.global_data.parameters = vec![parse!("flow_state_x"), parse!("flow_state_y")];
    parsed.global_data.group_id = Some(crate::graph::GroupId(7));
    parsed.global_data.is_group_master = true;
    parsed.global_data.threshold_counterterms = Some(
        crate::graph::threshold_counterterms::ThresholdCountertermSpec {
            function_map: std::collections::BTreeMap::from([(
                "flow_weight".into(),
                "1+flow_state_x".into(),
            )]),
            ..Default::default()
        },
    );
    let mut global_data = parsed.global_data.clone();
    let mut original = Graph::from_parsed(parsed, &model).unwrap();
    original.name = "GL0000".into();
    let cloned = original.clone();

    // Reproduce the previous second parse, whose input name differs from
    // the original parse. Compare all emitted state, not just the topology.
    let mut reparsed = ParseGraph::from_symbolica_graph(
        &model,
        &original.name,
        &normalized,
        original.overall_factor.clone(),
        &[],
    )
    .unwrap();
    global_data.name = original.name.clone();
    reparsed.global_data = global_data;
    let reparsed = Graph::from_parsed(reparsed, &model).unwrap();
    let export = crate::processes::DotExportSettings {
        include_autogenerated_fields: true,
        output_full_numerator: true,
        do_color_algebra: false,
        ..Default::default()
    };
    assert_eq!(
        cloned.dot_serialize(&export),
        reparsed.dot_serialize(&export)
    );
    assert_eq!(cloned.loop_momentum_basis, reparsed.loop_momentum_basis);
    assert_eq!(cloned.initial_state_cut, reparsed.initial_state_cut);
    assert_eq!(cloned.tree_edges, reparsed.tree_edges);
    assert_eq!(cloned.overall_factor, reparsed.overall_factor);
    assert_eq!(cloned.global_prefactor, reparsed.global_prefactor);
    assert_eq!(cloned.polarizations, reparsed.polarizations);
    assert_eq!(cloned.group_id, reparsed.group_id);
    assert_eq!(cloned.is_group_master, reparsed.is_group_master);
    assert_eq!(
        cloned.threshold_counterterms,
        reparsed.threshold_counterterms
    );
    // Every function-map registration goes through these complete entries,
    // including alias scope, arguments, bodies and inlining policy.
    assert_eq!(cloned.param_builder.reps, reparsed.param_builder.reps);
    assert_eq!(cloned.param_builder.values, reparsed.param_builder.values);
    let cloned_pairs = (&cloned.param_builder.pairs).into_iter().collect_vec();
    let reparsed_pairs = (&reparsed.param_builder.pairs).into_iter().collect_vec();
    assert_eq!(cloned_pairs.len(), reparsed_pairs.len());
    for (cloned, reparsed) in cloned_pairs.into_iter().zip(reparsed_pairs) {
        assert_eq!(cloned.params, reparsed.params);
        assert_eq!(cloned.value_range, reparsed.value_range);
    }
}

#[test]
fn changed_fermion_flow_requires_its_own_parsed_chart() {
    test_initialise().unwrap();
    let model = crate::utils::load_generic_model("sm");
    let process = ProcessDefinition {
        final_pdgs_lists: vec![vec![]],
        ..Default::default()
    };
    let mut graph = SymbolicaGraph::new();
    for _ in 0..2 {
        graph.add_node(NodeColorWithVertexRule::from_particles(
            ["d", "d~", "g"],
            &model,
        ));
    }
    for (source, sink, pdg) in [(1, 0, -1), (0, 1, -1), (0, 1, 21)] {
        graph
            .add_edge(source, sink, true, EdgeColor { pdg })
            .unwrap();
    }
    let (normalized, _) = process.normalize_flows(&graph, &model).unwrap();
    assert_ne!(graph, normalized);
    let parse = |graph| {
        Graph::from_parsed(
            ParseGraph::from_symbolica_graph(&model, "GL0000", graph, Atom::one(), &[]).unwrap(),
            &model,
        )
        .unwrap()
    };
    let original = parse(&graph);
    let normalized = parse(&normalized);
    assert_ne!(original.loop_momentum_basis, normalized.loop_momentum_basis);
    assert_ne!(
        original
            .iter_edges()
            .map(|(_, _, edge)| edge.data.particle.particle().unwrap().pdg_code)
            .collect_vec(),
        normalized
            .iter_edges()
            .map(|(_, _, edge)| edge.data.particle.particle().unwrap().pdg_code)
            .collect_vec(),
    );
}

#[test]
fn grouped_scalar_weights_cancel_after_rational_rescaling() {
    test_initialise().unwrap();
    // FullSM two-loop GL51–56 are one independently proved scalar class.
    // Its two polynomial-denominator ratios cancel exactly with the unit
    // symmetry weights, even when expanding their sum leaves nonzero terms.
    let ratio = parse!(
        "(-5/3*UFO::cw^(-1)*UFO::sw+UFO::cw*UFO::sw^(-1))^(-1)*1/3*UFO::cw*UFO::sw^(-1)
        +(-5/3*UFO::cw^(-1)*UFO::sw+UFO::cw*UFO::sw^(-1))^(-1)*1/3*UFO::cw^(-1)*UFO::sw"
    );
    let opposite_ratio = parse!(
        "(-5/3*UFO::cw^(-1)*UFO::sw+UFO::cw*UFO::sw^(-1))^(-1)*-1*UFO::cw*UFO::sw^(-1)
        +(-5/3*UFO::cw^(-1)*UFO::sw+UFO::cw*UFO::sw^(-1))^(-1)*1/3*UFO::cw^(-1)*UFO::sw"
    );
    let weight = parse!("(AutG(1))^(-1)*ExternalFermionOrderingSign(1)");
    let grouped = [
        (51, Atom::one()),
        (52, ratio.clone()),
        (53, ratio.clone()),
        (54, ratio),
        (55, opposite_ratio.clone()),
        (56, opposite_ratio),
    ]
    .into_iter()
    .fold(Atom::Zero, |sum, (id, ratio)| {
        sum + function!(
            symbol!("NumeratorDependentGrouping"),
            Atom::num(id),
            ratio,
            weight.clone()
        )
    });
    assert!(grouped_overall_factor_is_zero(grouped.as_view()));

    // Choosing another common scalar normalization preserves cancellation.
    let rescaled = &grouped * parse!("UFO::ee^2/UFO::G^2");
    assert!(grouped_overall_factor_is_zero(rescaled.as_view()));

    let nonzero = &grouped
        + parse!("NumeratorDependentGrouping(99,1,(AutG(2))^(-1)*InternalFermionLoopSign(-1))");
    assert!(!grouped_overall_factor_is_zero(nonzero.as_view()));
    assert_eq!(
        evaluate_overall_factor(nonzero.as_view()).together(),
        parse!("-1/2")
    );
}

#[test]
fn numerator_comparisons_preserve_exact_ratios_and_failure_semantics() {
    test_initialise().unwrap();
    // These are already sampled scalar coefficients, not graph numerators.
    // Use the same lazy exact coefficient cache as the comparison owner.
    let record = |canonical: Option<Atom>, samples: &[&str]| {
        let samples = samples
            .iter()
            .map(|sample| symbolica::parse!(*sample))
            .collect::<Vec<_>>();
        let polynomials = (0..samples.len()).map(|_| OnceLock::new()).collect();
        ProcessedNumeratorForComparison {
            diagram_id: 0,
            canonized_numerator: canonical,
            sample_evaluations: samples,
            sample_evaluations_as_polynomial: polynomials,
        }
    };

    // A unique nonzero graph stops its exact Lorentz-zero check at the
    // first sample. Its other four samples need no polynomial conversion.
    let lazy = record(
        None,
        &["g*(g+1)", "h*(h+1)", "j*(j+1)", "k*(k+1)", "l*(l+1)"],
    );
    assert!(
        lazy.sample_evaluations_as_polynomial
            .iter()
            .all(|p| p.get().is_none())
    );
    assert!(!(0..lazy.sample_evaluations.len()).all(|index| lazy.sample_is_zero(index)));
    assert_eq!(
        lazy.sample_evaluations_as_polynomial
            .iter()
            .filter(|p| p.get().is_some())
            .count(),
        1
    );
    let first = lazy.sample_polynomial(0) as *const RationalPoly;
    assert_eq!(first, lazy.sample_polynomial(0) as *const RationalPoly);

    let peer = record(None, &["g^2+g", "h^2+h", "j^2+j", "k^2+k", "l^2+l"]);
    assert_eq!(lazy.compare_with_scalar_rescaling(&peer), Some(Atom::one()));
    let cached = lazy
        .sample_evaluations_as_polynomial
        .iter()
        .filter(|p| p.get().is_some())
        .count();
    assert_eq!(cached, 5);
    assert_eq!(lazy.compare_with_scalar_rescaling(&peer), Some(Atom::one()));
    assert_eq!(
        lazy.sample_evaluations_as_polynomial
            .iter()
            .filter(|p| p.get().is_some())
            .count(),
        cached
    );

    // Polynomial zero detection still sees cancellation hidden by factoring;
    // literal zero and nonzero numeric samples need no conversion at all.
    let zeros = record(None, &["g*(g+1)-g^2-g", "0", "2"]);
    assert!(zeros.sample_is_zero(0));
    assert!(zeros.sample_is_zero(1));
    assert!(!zeros.sample_is_zero(2));
    assert_eq!(
        zeros
            .sample_evaluations_as_polynomial
            .iter()
            .filter(|p| p.get().is_some())
            .count(),
        1
    );

    for (name, left, right, sign, scalar) in [
        ("empty", &[][..], &[][..], None, None),
        (
            "identical",
            &["2", "3", "5"][..],
            &["2", "3", "5"][..],
            Some("1"),
            Some("1"),
        ),
        (
            "opposite",
            &["-2", "-3", "-5"][..],
            &["2", "3", "5"][..],
            Some("-1"),
            Some("-1"),
        ),
        (
            "numeric rescaling",
            &["4", "6", "10"][..],
            &["2", "3", "5"][..],
            None,
            Some("2"),
        ),
        (
            "complex rescaling",
            &["2+4𝑖", "3+6𝑖", "5+10𝑖"][..],
            &["2", "3", "5"][..],
            None,
            Some("1+2𝑖"),
        ),
        (
            "coupling rescaling",
            &["2*g^2", "3*g^2", "5*g^2"][..],
            &["2", "3", "5"][..],
            None,
            Some("g^2"),
        ),
        (
            "coupling ratio",
            &["2*g", "3*g", "5*g"][..],
            &["2*h", "3*h", "5*h"][..],
            None,
            Some("g/h"),
        ),
        (
            "coefficient polynomial fallback",
            &["g*(g+1)", "2*g*(g+1)"][..],
            &["g^2+g", "2*g^2+2*g"][..],
            Some("1"),
            Some("1"),
        ),
        (
            "negative coefficient polynomial fallback",
            &["-g*(g+1)", "-2*g*(g+1)"][..],
            &["g^2+g", "2*g^2+2*g"][..],
            Some("-1"),
            Some("-1"),
        ),
        (
            "factored zero sample",
            &["g*(g+1)-g^2-g", "3"][..],
            &["0", "3"][..],
            Some("1"),
            Some("1"),
        ),
        (
            "first sample differs",
            &["7", "3", "5"][..],
            &["2", "3", "5"][..],
            None,
            None,
        ),
        (
            "second sample differs",
            &["2", "7", "5"][..],
            &["2", "3", "5"][..],
            None,
            None,
        ),
        (
            "last sample differs",
            &["2", "3", "7"][..],
            &["2", "3", "5"][..],
            None,
            None,
        ),
        (
            "inconsistent signs",
            &["2", "-3", "5"][..],
            &["2", "3", "5"][..],
            None,
            None,
        ),
        (
            "zero numerator",
            &["0", "3", "5"][..],
            &["2", "3", "5"][..],
            None,
            None,
        ),
        (
            "zero reference",
            &["2", "3", "5"][..],
            &["0", "3", "5"][..],
            None,
            None,
        ),
        (
            "all zero",
            &["0", "0"][..],
            &["0", "0"][..],
            Some("1"),
            Some("1"),
        ),
        (
            "shared zero and unit ratio",
            &["0", "3", "5"][..],
            &["0", "3", "5"][..],
            Some("1"),
            Some("1"),
        ),
    ] {
        let left = record(None, left);
        let right = record(None, right);
        assert_eq!(
            left.compare_with_sign_only(&right),
            sign.map(|expected| symbolica::parse!(expected)),
            "sign comparison: {name}"
        );
        assert_eq!(
            left.compare_with_scalar_rescaling(&right),
            scalar.map(|expected| symbolica::parse!(expected)),
            "scalar comparison: {name}"
        );
    }

    // A shared zero supplies no ratio constraint: 0 = 2*0. The previous
    // comparison assigned 0/0 the ratio one and declined these groupings.
    // Conservative rejection and the exact nonzero ratio both preserve values.
    for (left, right) in [
        (["0", "6", "10"], ["0", "3", "5"]),
        (["4", "6", "0"], ["2", "3", "0"]),
    ] {
        let left = record(None, &left);
        let right = record(None, &right);
        assert_eq!(left.compare_with_sign_only(&right), None);
        if let Some(ratio) = left.compare_with_scalar_rescaling(&right) {
            assert_eq!(ratio, Atom::num(2));
        }
    }

    // Canonical numerators and samples describe the same expressions. Keep
    // their coefficients consistent, including shared zeros, to check exact
    // ratios without constraining the order of symbolic matching and prefilters.
    let canonical = symbolica::parse_lit!(spenso::gamma(
        spenso::bis(4, 1),
        spenso::bis(4, 2),
        spenso::mink(4, 3)
    ));
    for (ratio, expected_sign, samples) in [
        (Atom::one(), Some(Atom::one()), ["0", "2"]),
        (-Atom::one(), Some(-Atom::one()), ["0", "-2"]),
        (symbolica::parse_lit!(g ^ 2), None, ["0", "2*g^2"]),
    ] {
        let left = record(Some(&ratio * &canonical), &samples);
        let right = record(Some(canonical.clone()), &["0", "2"]);
        assert_eq!(left.compare_with_sign_only(&right), expected_sign);
        assert_eq!(left.compare_with_scalar_rescaling(&right), Some(ratio));
    }

    // A residual Lorentz index is not a scalar coupling ratio, so an attempted
    // symbolic comparison must still reject it when no samples are available.
    let indexed = record(Some(canonical), &[]);
    let scalar = record(Some(Atom::one()), &[]);
    assert_eq!(indexed.compare_with_sign_only(&scalar), None);
    assert_eq!(indexed.compare_with_scalar_rescaling(&scalar), None);
}
