#import "../../../../assets/embedded/drawing/templates/physics-edge-style.typ": (
  coil, dashed, dotted, mi, sink-stroke, source-stroke, style, wave, zigzag,
)
#import "../theme.typ": palette

// Website-local weights: deliberately a little heavier than Linnest's
// general-purpose 0.55pt/1pt defaults so the diagrams survive at hero scale.
#let massless = 1.0pt
#let massive = 1.55pt

// The About illustration is shown as a single editorial figure rather than a
// compact catalogue thumbnail, so its graph and arrows can carry more weight.
#let about-massless = 1.25pt
#let about-massive = 1.9pt

#let particle-flow = (
  fermion-arrow: true,
  fermion-arrow-mark: (
    end: (
      symbol: ">",
      fill: palette.ink,
      stroke: palette.ink + 0.3pt,
      anchor: "center",
      shorten-to: auto,
    ),
    scale: 1.05,
  ),
)

#let about-particle-flow = (
  fermion-arrow: true,
  fermion-arrow-mark: (
    end: (
      symbol: ">",
      fill: palette.ink,
      stroke: palette.ink + 0.4pt,
      anchor: "center",
      shorten-to: auto,
    ),
    scale: 1.3,
  ),
)

#let default-edge = (
  source: source-stroke(c: palette.ink, thickness: massless),
  sink: sink-stroke(c: palette.ink, thickness: massless),
  label: none,
)

// Standard Model particle map generated by GammaLoop's `save dot` template,
// expressed here as editable, theme-aware Typst instead of generated output.
#let map = (
  "about-photon": (
    source: source-stroke(c: palette.ink, thickness: about-massless) + wave,
    sink: sink-stroke(c: palette.ink, thickness: about-massless) + wave,
    label: none,
  ),
  "about-fermion": (
    source: source-stroke(c: palette.accent, thickness: about-massive),
    sink: sink-stroke(c: palette.accent, thickness: about-massive),
    label: none,
  ) + about-particle-flow,
  "about-gluon": (
    source: source-stroke(c: palette.ink, thickness: about-massless) + coil,
    sink: sink-stroke(c: palette.ink, thickness: about-massless) + coil,
    label: none,
  ),
  "a": (
    source: source-stroke(c: palette.ink, thickness: massless) + wave,
    sink: sink-stroke(c: palette.ink, thickness: massless) + wave,
    label: mi(`{\gamma}`),
  ),
  "Z": (
    source: source-stroke(c: palette.ink, thickness: massive) + wave,
    sink: sink-stroke(c: palette.ink, thickness: massive) + wave,
    label: mi(`{Z}`),
  ),
  "W+": (
    source: source-stroke(c: palette.accent, thickness: massive) + zigzag,
    sink: sink-stroke(c: palette.accent, thickness: massive) + zigzag,
    label: mi(`{W^+}`),
  ),
  "W-": (
    source: source-stroke(c: palette.accent, thickness: massive) + zigzag,
    sink: sink-stroke(c: palette.accent, thickness: massive) + zigzag,
    label: mi(`{W^-}`),
  ),
  "g": (
    source: source-stroke(c: palette.ink, thickness: massless) + coil,
    sink: sink-stroke(c: palette.ink, thickness: massless) + coil,
    label: mi(`{g}`),
  ),
  "ghA": (
    source: source-stroke(c: palette.ink, thickness: massless, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massless, dash: dotted),
    label: mi(`\tilde{\gamma}`),
  ),
  "ghA~": (
    source: source-stroke(c: palette.ink, thickness: massless, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massless, dash: dotted),
    label: mi(`\overline{\tilde{\gamma}}`),
  ),
  "ghZ": (
    source: source-stroke(c: palette.ink, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massive, dash: dotted),
    label: mi(`\tilde{Z}`),
  ),
  "ghZ~": (
    source: source-stroke(c: palette.ink, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massive, dash: dotted),
    label: mi(`\bar{\tilde{Z}}`),
  ),
  "ghWp": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dotted),
    label: mi(`{\tilde{W}^+}`),
  ),
  "ghWp~": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dotted),
    label: mi(`{\bar{\tilde{W}}^+}`),
  ),
  "ghWm": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dotted),
    label: mi(`{\tilde{W}^-}`),
  ),
  "ghWm~": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dotted),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dotted),
    label: mi(`{\bar{\tilde{W}}^-}`),
  ),
  "ghG": (
    source: source-stroke(c: palette.ink, thickness: massless, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massless, dash: dotted),
    label: mi(`{\tilde{g}}`),
  ),
  "ghG~": (
    source: source-stroke(c: palette.ink, thickness: massless, dash: dotted),
    sink: sink-stroke(c: palette.ink, thickness: massless, dash: dotted),
    label: mi(`{\bar{\tilde{g}}}`),
  ),
  "ve": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\nu_e}`),
  )
    + particle-flow,
  "ve~": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\overline{\nu}_e}`),
  )
    + particle-flow,
  "vm": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\nu_\mu}`),
  )
    + particle-flow,
  "vm~": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\overline{\nu}_\mu}`),
  )
    + particle-flow,
  "vt": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\nu_\tau}`),
  )
    + particle-flow,
  "vt~": (
    source: source-stroke(c: palette.ink, thickness: massless),
    sink: sink-stroke(c: palette.ink, thickness: massless),
    label: mi(`{\overline{\nu}_\tau}`),
  )
    + particle-flow,
  "u": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{u}`),
  )
    + particle-flow,
  "u~": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{\overline{u}}`),
  )
    + particle-flow,
  "c": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{c}`),
  )
    + particle-flow,
  "c~": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\overline{c}}`),
  )
    + particle-flow,
  "t": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{t}`),
  )
    + particle-flow,
  "t~": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\overline{t}}`),
  )
    + particle-flow,
  "d": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{d}`),
  )
    + particle-flow,
  "d~": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{\overline{d}}`),
  )
    + particle-flow,
  "s": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{s}`),
  )
    + particle-flow,
  "s~": (
    source: source-stroke(c: palette.accent, thickness: massless),
    sink: sink-stroke(c: palette.accent, thickness: massless),
    label: mi(`{\overline{s}}`),
  )
    + particle-flow,
  "b": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{b}`),
  )
    + particle-flow,
  "b~": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\overline{b}}`),
  )
    + particle-flow,
  "H": (
    source: source-stroke(c: palette.ink, thickness: massive, dash: dashed),
    sink: sink-stroke(c: palette.ink, thickness: massive, dash: dashed),
    label: mi(`{H}`),
  ),
  "G0": (
    source: source-stroke(c: palette.ink, thickness: massive, dash: dashed),
    sink: sink-stroke(c: palette.ink, thickness: massive, dash: dashed),
    label: mi(`{G_0}`),
  ),
  "G+": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dashed),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dashed),
    label: mi(`{G^+}`),
  ),
  "G-": (
    source: source-stroke(c: palette.accent, thickness: massive, dash: dashed),
    sink: sink-stroke(c: palette.accent, thickness: massive, dash: dashed),
    label: mi(`{G^-}`),
  ),
  "e-": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{e^-}`),
  )
    + particle-flow,
  "e+": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{e^+}`),
  )
    + particle-flow,
  "mu-": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\mu^-}`),
  )
    + particle-flow,
  "mu+": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\mu^+}`),
  )
    + particle-flow,
  "ta-": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\tau^-}`),
  )
    + particle-flow,
  "ta+": (
    source: source-stroke(c: palette.accent, thickness: massive),
    sink: sink-stroke(c: palette.accent, thickness: massive),
    label: mi(`{\tau^+}`),
  )
    + particle-flow,
)

#let source-style(edge, typst-fields: "plain", ..options) = {
  let callbacks = style(
    map: map,
    default: default-edge,
    typst-fields: typst-fields,
    ..options.named(),
  )
  (callbacks.source-style)(edge)
}

#let sink-style(edge, typst-fields: "plain", ..options) = {
  let callbacks = style(
    map: map,
    default: default-edge,
    typst-fields: typst-fields,
    ..options.named(),
  )
  (callbacks.sink-style)(edge)
}

#let edge-label(edge, typst-fields: "plain", ..options) = {
  let callbacks = style(
    map: map,
    default: default-edge,
    typst-fields: typst-fields,
    ..options.named(),
  )
  (callbacks.edge-label)(edge)
}
