General:
  debug: 0
  use_ltd: false
Integrand:
  type: gamma_loop
Kinematics:
  e_cm: 3.0
  externals: !constant
  - - 2.0
    - 2.0
    - 3.0
    - 4.0
  - - 1.0
    - 2.0
    - 9.0
    - 3.0
Parameterization:
  mode: spherical
  mapping: linear
  b: 1.0
Integrator:
  n_bins: 0
  bin_number_evolution: null
  min_samples_for_update: 0
  n_start: 0
  n_increase: 0
  n_max: 0
  integrated_phase: real
  learning_rate: 0.0
  train_on_avg: false
  show_max_wgt_info: false
  max_prob_ratio: 0.0
Observables: []
Selectors: []
Stability:
  rotation_axis: x
  levels:
  - precision: Double
    required_precision_for_re: 1e-15
    required_precision_for_im: 1e-15
    escalate_for_large_weight_threshold: 0.9
    accepted_radius_in_x_range:
    - 0.0
    - 0.9
  - precision: Quad
    required_precision_for_re: 1e-15
    required_precision_for_im: 1e-15
    escalate_for_large_weight_threshold: -1.0
    accepted_radius_in_x_range:
    - 0.0
    - 1.0
