= GL638: static preparation of the 600 GeV comparison
<gl638-static-preparation-of-the-600-gev-comparison>
The retained saved state and all completed confirmation results use #strong[sqrt(s) = 1000 GeV];, with incoming momenta `(500,0,0,+500)` and `(500,0,0,-500)` GeV. The new cards use `e_cm=600` and incoming `(300,0,0,+300)`, `(300,0,0,-300)` GeV. With the unchanged masses mt=173 and mh=125 GeV, the production threshold is 471 GeV; 600 GeV leaves 129 GeV of excess energy. This is a sensible second kinematic point, but smaller phase space does not by itself certify improved numerical stability or bounded weights.

The four files in `cards/` are the matched 8-channel (six cuts, joint HZ, soft LMB) and 9-channel (add Cut3 right threshold) proposals, each with `m_uv=91.188` and `m_uv=50` GeV. #strong[mu\_r stays 91.188 GeV in all four.] Parsed TOML comparisons confirm that only the beam momenta, e\_cm, and, where requested, m\_uv differ from the 1000 GeV source cards. The real integration phase, soft channel, WH/WF prescription, other settings, and channel definitions are unchanged. `manifest.json` records all input/output hashes. These are prepared cards, not successful native runtime gates.

== Reusing the saved state
<reusing-the-saved-state>
The existing runtime API owns this change: `ProcessIntegrand::get_mut_settings` invalidates caches (`crates/gammalooprs/src/integrands/process/mod.rs:479`), then `CrossSectionIntegrand::warm_up` warms every term and rebuilds sampling (`cross_section/mod.rs:488`). Graph warmup obtains current external momenta and writes them into all parameter derivatives (`cross_section/mod.rs:2479–2500`), resets external polarizations, sets current UV and renormalization scales, and refreshes model/mass data (`2530–2553`). The sampling bridge binds current improved external momenta after that (`process/mod.rs:2719`). Thus the full same-state loaded integrand can change these runtime inputs without algebra generation; warmup must be rerun before evaluation. No state load or native warmup was performed in this audit.

The saved DOT and repository DOT have #strong[identical parsed threshold metadata, including every multiplier expression];. Their raw strings differ through saved array formatting/comment removal. There is no literal `1000` in the metadata. It contains 34 instances of the dynamic energy sum `P(0,cind(0))+P(1,cind(0))`. The multiplier workspace updates these external momentum inputs whenever effective external momenta change (`threshold_multiplier.rs:1155–1171`) and reconstructs edge energies for the current effective and star points. WH and WF are consequently not frozen to Q=1000.

The state was generated with `check_esurface_at_generation=true`. This is not unrestricted permission to vary kinematics after arbitrary generation pruning. Here the only energy-dependent exclusion bound is `Q - complement_mass` (`processes/cross_section.rs:430–447`); decreasing Q cannot revive a threshold excluded by the upper invariant bound. Structural pinch and no-radial-dependence exclusions are unchanged. With fixed masses and process, moving from 1000 to 600 GeV therefore does not need additional CTs absent from the retained state. Native warmup/catalogue gates should still record the 936 orientations, six cuts, and 19 stored variants, along with dynamic existence/decline of surfaces.

== Runtime UV-mass steering
<runtime-uv-mass-steering>
Both `m_uv_vacuum` and `m_uv_expansion` are explicit evaluator parameter slots (`param_builder.rs:252`). `m_uv_value` fills both in every derivative parameter vector (`param_builder.rs:1280–1296`) using the runtime general.m\_uv supplied during graph warmup. Direct 3D local UV contains symbolic expansion mass (`uv/approx/direct_3d/kernel.rs:617`); final local expressions identify it with symbolic vacuum mass (`uv/approx/final_integrand.rs:303`), and integrated UV generates symbolic `m_uv_vacuum` in its vacuum propagators (`uv/approx/integrated.rs:872`). The saved Vakint `direct_numerical_substition=true` refers to master-integral coefficient processing, not replacing the runtime beam/UV-mass parameter slots. mu\_r\_sq has its separate warmup setter, so changing m\_uv does not implicitly change mu\_r. Algebra regeneration is not required for this parameter scan.

The requested UV-scale independence is a numerical physics acceptance gate, #strong[not a pointwise identity];. For each fixed channel catalogue at 600 GeV, retain common Samples and integrate the paired difference `Re(F_50)-Re(F_91.188)` including the same sampling weights; estimate its error with the covariance intact. Require consistency with zero over independently seeded runs and increasing counts. Also compare each integral and |Re| variance/errors/maxima; a change in |Re| is allowed. If the difference is inconsistent, inspect local/integrated UV and physical-cut contributions before interpreting variance improvement.

== Geometry that must be regenerated
<geometry-that-must-be-regenerated>
The channel strings and their exact edge/cycle definitions remain valid. Their #strong[numerical] geometry must be rebuilt at the new energy: LU t-star, hosted H/Z roots, intersection centers/Gram certificates and active support radius, each native CT star, and all density/inverse certificates. The historical H/Z anchor and extrema cannot be reused or merely multiplied by 0.6, because mt and mh stay fixed. At the Cut3 right `[5,10]` origin-centered surface, the radius changes from `sqrt(500^2-173^2)=469.1172561311` GeV to `sqrt(300^2-173^2)=245.0938595722` GeV. The shifted physical CT center remains distinct from this map sphere and is computed afresh.

After the frozen 1000 GeV Eager/SymJIT timing comparison, the next gates are native parse/warmup plus map normalization, real-component rescue controls, fresh H/Z approaches, single/double-soft approaches with the explicit soft channel, and matched real/|Re| physics pilots for the four new cards. The existing 1000 GeV results remain a separate dataset. No claim that 600 GeV or m\_uv=50 is numerically better is made here.

No GammaLoop process, build, integration, source edit, or saved-state mutation was performed. Two preparation-only issues were corrected: the shell initially lacked python until the documented development environment was sourced, and raw DOT-string equality was replaced by the proper parsed metadata equality after identifying serialization-only differences.
