[graphs.G1]
path = "./graphs/G1.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==2 [{{2}} QCD=1]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86]
target_weight = { re = -4.986300161096361e-20, im = -8.983113256654707e-4 }

[graphs.G1.alphaloop]
t_gen_s = 0.1
disk_mb = 0.13
t_eval_ms = 0.004

[graphs.G2]
path = "./graphs/G2.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==4 [{{3}} QCD=2]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47]

[graphs.G2.alphaloop]
t_gen_s = 4.7
disk_mb = 3.0
t_eval_ms = 0.04

[graphs.G3]
path = "./graphs/G3.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==6 [{{4}} QCD=3]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47, 0.61, 0.75, 0.89]

[graphs.G3.alphaloop]
t_gen_s = 36000.0
disk_mb = 509.0
t_eval_ms = 17.6

[graphs.H1]
path = "./graphs/H1.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==2 [{{2}} QCD=1]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86]
target_weight = { re = -7.938122705437497e-21, im = 1.5008076532031015e-3 }

[graphs.H1.alphaloop]
t_gen_s = 0.07
disk_mb = 0.12
t_eval_ms = 0.006

[graphs.H2]
path = "./graphs/H2.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==4 [{{3}} QCD=2]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47]

[graphs.H2.alphaloop]
t_gen_s = 1.5
disk_mb = 1.3
t_eval_ms = 0.056

[graphs.H3]
path = "./graphs/H3.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ | t g ghG ghG~ a QED^2==2 QCD^2==6 [{{4}} QCD=3]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47, 0.61, 0.75, 0.89]

[graphs.H3.alphaloop]
t_gen_s = 255.0
disk_mb = 43.0
t_eval_ms = 2.35

[graphs.I1]
path = "./graphs/I1.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ h | t h g ghG ghG~ a QED^2==4 QCD^2==4 [{{4}} QCD=2]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47, 0.61, 0.75, 0.89]

[graphs.I1.alphaloop]
t_gen_s = 126.0
disk_mb = 22.0
t_eval_ms = 0.32

[graphs.I2]
path = "./graphs/I2.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ h h | t h g ghG ghG~ a QED^2==6 QCD^2==4 [{{4}} QCD=2]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47, 0.61, 0.75, 0.89, 0.11, 0.24, 0.37]

[graphs.I2.alphaloop]
t_gen_s = 1900.0
disk_mb = 120.0
t_eval_ms = 4.4

[graphs.I3]
path = "./graphs/I3.dot"
model = "sm-default.json"
process = "bench"
integrand = "default"
process_spec = "a > t t~ h h h | t h g ghG ghG~ a QED^2==8 QCD^2==4 [{{4}} QCD=2]"
x = [0.13, 0.27, 0.41, 0.58, 0.72, 0.86, 0.19, 0.33, 0.47, 0.61, 0.75, 0.89, 0.11, 0.24, 0.37, 0.52, 0.68, 0.83]

[graphs.I3.alphaloop]
t_gen_s = 36000.0
disk_mb = 20000.0
t_eval_ms = 3600.0

[profiles.minimal.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "CFF"
explicit_orientation_sum_only = "false"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "false"
summed = "false"
summed_function_map = "false"
compilation_mode = "symjit"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "false"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "false"
evaluator_method = "SingleParametric"
load_compiled_cff = "false"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"

[profiles.cff.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "CFF"
explicit_orientation_sum_only = "false"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "false"
summed = "false"
summed_function_map = "false"
compilation_mode = "symjit"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "false"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "false"
evaluator_method = "SingleParametric"
load_compiled_cff = "false"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"

[profiles.cff_4d.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "CFF"
explicit_orientation_sum_only = "false"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "false"
summed = "false"
summed_function_map = "false"
compilation_mode = "symjit"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "true"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "false"
evaluator_method = "SingleParametric"
load_compiled_cff = "false"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"

[profiles.ltd.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "LTD"
explicit_orientation_sum_only = "true"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "false"
summed = "false"
summed_function_map = "false"
compilation_mode = "symjit"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "true"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "true"
evaluator_method = "Summed"
load_compiled_cff = "false"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"

[profiles.optimized_cff.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "CFF"
explicit_orientation_sum_only = "false"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "true"
summed = "false"
summed_function_map = "true"
compilation_mode = "assembly"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "false"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "false"
evaluator_method = "SummedFunctionMap"
load_compiled_cff = "true"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"

[profiles.optimized_ltd.defines]
minimal_integrand = "--minimal-integrand"
logfile_directive = "off"
display_directive = "info"
log_include_fields = "false"
representation = "LTD"
explicit_orientation_sum_only = "true"
do_algebra = "false"
iterative_orientation_optimization = "false"
store_atom = "false"
compile = "true"
summed = "false"
summed_function_map = "true"
compilation_mode = "assembly"
optimization_level = "O3"
fast_math = "true"
unsafe_math = "true"
compile_custom = "[]"
enable_thresholds = "false"
check_esurface_at_generation = "true"
skip_thresholds_that_are_cuts = "true"
uv_softct = "false"
uv_inner_products = "true"
uv_generate_integrated = "false"
uv_subtract = "true"
local_uv_from_expanded_4d = "true"
tropical_panic_on_fail = "true"
disable_tropical_generation = "true"
use_ltd = "true"
evaluator_method = "SummedFunctionMap"
load_compiled_cff = "true"
enable_cache = "false"
debug_cache = "false"
generate_events = "false"
store_additional_weights_in_event = "false"
integral_unit = "picobarn"
mu_r = "91.188"
m_uv = "91.188"
disable_threshold_subtraction = "true"
sampling_graphs = "summed"
sampling_orientations = "summed"
lmb_multichanneling = "false"
lmb_channels = "summed"
coordinate_system = "spherical"
mapping = "linear"
mapping_b = "1.0"
rotation_axis = "[]"
precision = "Double"
required_precision_for_re = "1.0e-5"
required_precision_for_im = "1.0e-5"
escalate_for_large_weight_threshold = "-1.0"
