graphs=[{'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 7]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 8]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [5, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [6, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0+p2',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 7]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0+p0+p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [8, 6]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k0+p0',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [7, 8]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 3, 5],
                'indices': [11, 5, 10],
                'momenta': ['-k0', '-p2', 'k0+p2'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 22, 6],
                'edge_ids': [5, 4, 7],
                'indices': [9, 7, 14],
                'momenta': ['-k0-p2', '-p0-p1+p2', 'k0+p0+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 1, 6],
                'indices': [15, 1, 12],
                'momenta': ['-k0-p0', 'p0', 'k0'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [7, 2, 8],
                'indices': [13, 3, 16],
                'momenta': ['-k0-p0-p1', 'p1', 'k0+p0'],
                'vertex_id': 0}},
  'overall_factor': '-2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 7]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 8]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [5, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [6, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0+p2',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0+p0+p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [7, 6]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [8, 7]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 3, 5],
                'indices': [11, 5, 10],
                'momenta': ['-k0', '-p2', 'k0+p2'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 22, 6],
                'edge_ids': [5, 4, 7],
                'indices': [9, 7, 14],
                'momenta': ['-k0-p2', '-p0-p1+p2', 'k0+p0+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [7, 1, 8],
                'indices': [13, 1, 16],
                'momenta': ['-k0-p0-p1', 'p0', 'k0+p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 2, 6],
                'indices': [15, 3, 12],
                'momenta': ['-k0-p1', 'p1', 'k0'],
                'vertex_id': 0}},
  'overall_factor': '-2'}]
graph_names=["GL0","GL2"]