graphs=[{'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 9]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k0-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [7, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [8, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k0-k1+p0+p1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [10, 8]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k0-k1+p0',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 8],
                'indices': [9, 12, 16],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 3, 9],
                'indices': [15, 5, 18],
                'momenta': ['-k0+k1', '-p2', 'k0-k1+p2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 4, 10],
                'indices': [17, 7, 20],
                'momenta': ['-k0+k1-p2', '-p0-p1+p2', 'k0-k1+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 1, 7],
                'indices': [21, 1, 14],
                'momenta': ['-k0+k1-p0', 'p0', 'k0-k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [10, 2, 11],
                 'indices': [19, 3, 22],
                 'momenta': ['-k0+k1-p0-p1', 'p1', 'k0-k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 9]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k0-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [8, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+p0+p1-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [7, 8]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k0-k1+p0+p1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k0-k1+p0',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 8],
                'indices': [9, 12, 16],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 3, 10],
                'indices': [17, 5, 20],
                'momenta': ['-k0+k1-p0-p1+p2', '-p2', 'k0-k1+p0+p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 4, 9],
                'indices': [15, 7, 18],
                'momenta': ['-k0+k1', '-p0-p1+p2', 'k0-k1+p0+p1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 1, 7],
                'indices': [21, 1, 14],
                'momenta': ['-k0+k1-p0', 'p0', 'k0-k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [10, 2, 11],
                 'indices': [19, 3, 22],
                 'momenta': ['-k0+k1-p0-p1', 'p1', 'k0-k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0+k1+p0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k1+p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1+p0',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [9, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k1+p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [8, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 9]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 8]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k1-p0', '-k0', 'k0+k1+p0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 8],
                'indices': [9, 12, 16],
                'momenta': ['-k0-k1-p0', 'k0', 'k1+p0'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 3, 9],
                'indices': [19, 5, 18],
                'momenta': ['-k1', '-p2', 'k1+p2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 4, 11],
                'indices': [17, 7, 22],
                'momenta': ['-k1-p2', '-p0-p1+p2', 'k1+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 1, 10],
                'indices': [15, 1, 20],
                'momenta': ['-k1-p0', 'p0', 'k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 7],
                 'indices': [21, 3, 14],
                 'momenta': ['-k1-p0-p1', 'p1', 'k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0+k1-p1',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k1-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1-p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [9, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k1-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [7, 8]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1-p0-p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [8, 9]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k1+p1', '-k0', 'k0+k1-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 8],
                'indices': [9, 12, 16],
                'momenta': ['-k0-k1+p1', 'k0', 'k1-p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 3, 10],
                'indices': [17, 5, 20],
                'momenta': ['-k1+p2', '-p2', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 4, 9],
                'indices': [21, 7, 18],
                'momenta': ['-k1+p0+p1', '-p0-p1+p2', 'k1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 1, 11],
                'indices': [15, 1, 22],
                'momenta': ['-k1+p1', 'p0', 'k1-p0-p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [10, 2, 7],
                 'indices': [19, 3, 14],
                 'momenta': ['-k1', 'p1', 'k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': '-4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [8, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': '-k0+k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 9]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': '-k0+k1+p0+p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [10, 6]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1+p0+p1-p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': '-k0+k1+p0',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['k0-k1', '-k0', 'k1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [8, 5, 9],
                'indices': [15, 10, 18],
                'momenta': ['-k1-p0-p1', 'k0', '-k0+k1+p0+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 3, 8],
                'indices': [19, 5, 16],
                'momenta': ['-k1-p0-p1+p2', '-p2', 'k1+p0+p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 4, 10],
                'indices': [11, 7, 20],
                'momenta': ['-k1', '-p0-p1+p2', 'k1+p0+p1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 1, 7],
                'indices': [21, 1, 14],
                'momenta': ['k0-k1-p0', 'p0', '-k0+k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 2, 11],
                 'indices': [17, 3, 22],
                 'momenta': ['k0-k1-p0-p1', 'p1', '-k0+k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [8, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': '-k0+k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': '-k0+k1+p0+p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [9, 6]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1+p0+p1-p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': '-k0+k1+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 9]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['k0-k1', '-k0', 'k1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [8, 5, 9],
                'indices': [15, 10, 18],
                'momenta': ['-k1-p0-p1', 'k0', '-k0+k1+p0+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 3, 8],
                'indices': [19, 5, 16],
                'momenta': ['-k1-p0-p1+p2', '-p2', 'k1+p0+p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 4, 10],
                'indices': [11, 7, 20],
                'momenta': ['-k1', '-p0-p1+p2', 'k1+p0+p1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 1, 11],
                'indices': [17, 1, 22],
                'momenta': ['k0-k1-p0-p1', 'p0', '-k0+k1+p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 7],
                 'indices': [21, 3, 14],
                 'momenta': ['k0-k1-p1', 'p1', '-k0+k1'],
                 'vertex_id': 0}},
  'overall_factor': '-2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k1+p0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [9, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': '-k0+k1+p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1+p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': '-k0+k1+p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [8, 6]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 9]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': '-k0+k1+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 8]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['k0-k1-p0', '-k0', 'k1+p0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [8, 5, 9],
                'indices': [15, 10, 18],
                'momenta': ['-k1-p2', 'k0', '-k0+k1+p2'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 3, 8],
                'indices': [19, 5, 16],
                'momenta': ['-k1', '-p2', 'k1+p2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 4, 11],
                'indices': [17, 7, 22],
                'momenta': ['k0-k1-p2', '-p0-p1+p2', '-k0+k1+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 1, 10],
                'indices': [11, 1, 20],
                'momenta': ['-k1-p0', 'p0', 'k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 7],
                 'indices': [21, 3, 14],
                 'momenta': ['k0-k1-p0-p1', 'p1', '-k0+k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k0+k1-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [9, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k1-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1-p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [7, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 8]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k0+k1-p0-p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [8, 9]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['-k1+p1', '-k0', 'k0+k1-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 5, 8],
                'indices': [17, 10, 16],
                'momenta': ['-k0-k1+p2', 'k0', 'k1-p2'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 3, 10],
                'indices': [15, 5, 20],
                'momenta': ['-k1+p2', '-p2', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 4, 9],
                'indices': [21, 7, 18],
                'momenta': ['-k0-k1+p0+p1', '-p0-p1+p2', 'k0+k1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 1, 11],
                'indices': [11, 1, 22],
                'momenta': ['-k0-k1+p1', 'p0', 'k0+k1-p0-p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [10, 2, 7],
                 'indices': [19, 3, 14],
                 'momenta': ['-k1', 'p1', 'k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': '-2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k0+k1+p0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [9, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k1+p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [7, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 9]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1+p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 8]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['-k1-p0', '-k0', 'k0+k1+p0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 5, 8],
                'indices': [17, 10, 16],
                'momenta': ['-k0-k1', 'k0', 'k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 3, 10],
                'indices': [15, 5, 20],
                'momenta': ['-k1', '-p2', 'k1+p2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 4, 11],
                'indices': [19, 7, 22],
                'momenta': ['-k1-p2', '-p0-p1+p2', 'k1+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 1, 9],
                'indices': [11, 1, 18],
                'momenta': ['-k0-k1-p0', 'p0', 'k0+k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 7],
                 'indices': [21, 3, 14],
                 'momenta': ['-k1-p0-p1', 'p1', 'k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-6'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 9]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 10]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [7, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [8, 3]},
            5: {'PDG': 21,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 6,
                'indices': [11, 12],
                'momentum': 'k0+k1+p0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [9, 5]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k1+p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 10]},
            8: {'PDG': 6,
                'indices': [15, 16],
                'momentum': 'k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [8, 6]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 9]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k1+p0+p1-p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 7]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 5, 6],
                'indices': [13, 9, 12],
                'momenta': ['-k1-p0', '-k0', 'k0+k1+p0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 5, 8],
                'indices': [17, 10, 16],
                'momenta': ['-k0-k1', 'k0', 'k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 22, 6],
                'edge_ids': [10, 3, 11],
                'indices': [19, 5, 22],
                'momenta': ['-k1-p0-p1+p2', '-p2', 'k1+p0+p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 22, 6],
                'edge_ids': [8, 4, 10],
                'indices': [15, 7, 20],
                'momenta': ['-k1', '-p0-p1+p2', 'k1+p0+p1-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [6, 1, 9],
                'indices': [11, 1, 18],
                'momenta': ['-k0-k1-p0', 'p0', 'k0+k1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 7],
                 'indices': [21, 3, 14],
                 'momenta': ['-k1-p0-p1', 'p1', 'k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '-6'}]
graph_names=["GL0","GL4","GL8","GL12","GL16","GL18","GL24","GL26","GL28","GL34"]