graphs=[{'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 11]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+p0+p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [12, 6]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': '-k1+k2+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 10]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': '-k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [9, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': '-k1+k2+p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [10, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+p0',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 8, 9],
                'indices': [9, 15, 18],
                'momenta': ['-k0', 'k1-p0-p1', 'k0-k1+p0+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k1-k2-p0-p1', '-k1+p0+p1', 'k2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 6, 12],
                'indices': [19, 12, 24],
                'momenta': ['-k2', 'k1', '-k1+k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [12, 3, 13],
                'indices': [23, 5, 26],
                'momenta': ['k1-k2', '-p2', '-k1+k2+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 4, 11],
                 'indices': [25, 7, 22],
                 'momenta': ['k1-k2-p2', '-p0-p1+p2', '-k1+k2+p0+p1'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 7],
                 'indices': [27, 1, 14],
                 'momenta': ['-k0+k1-p0', 'p0', 'k0-k1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 2, 14],
                 'indices': [17, 3, 28],
                 'momenta': ['-k0+k1-p0-p1', 'p1', 'k0-k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(184,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(185,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(186,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(187,1,AutG(1)^-1*ExternalFermionOrderingSign(1))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0+k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [12, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1-p0-p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 11]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1+k2-p0-p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k1+k2-p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0+k1-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', '-k1', 'k0+k1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0-k1+p0+p1', 'k1-p0-p1', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k2', '-k1+p0+p1', 'k1+k2-p0-p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [12, 6, 10],
                'indices': [23, 12, 20],
                'momenta': ['-k1-k2', 'k1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 12],
                'indices': [25, 5, 24],
                'momenta': ['-k1-k2+p2', '-p2', 'k1+k2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 4, 13],
                 'indices': [21, 7, 26],
                 'momenta': ['-k1-k2+p0+p1', '-p0-p1+p2', 'k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 9],
                 'indices': [27, 1, 18],
                 'momenta': ['-k0-k1+p1', 'p0', 'k0+k1-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 2, 14],
                 'indices': [13, 3, 28],
                 'momenta': ['-k0-k1', 'p1', 'k0+k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(188,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(189,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(190,1,AutG(1)^-1*ExternalFermionOrderingSign(1))+NumeratorDependentGrouping(191,1,AutG(1)^-1*ExternalFermionOrderingSign(1))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k0-k2+p0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k2-p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 11]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k0+k2-p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [9, 6]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': '-k0+k1+k2-p2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 10]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': '-k0+k1+k2-p0',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [12, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [11, 9]},
            14: {'PDG': 1,
                 'indices': [27, 28],
                 'momentum': '-k0+k1+k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k2+p0', '-k0+k2-p0', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 8, 9],
                'indices': [9, 15, 18],
                'momenta': ['-k0', 'k0-k2+p2', 'k2-p2'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k0-k1-k2+p2', '-k0+k2-p2', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 6, 12],
                'indices': [19, 12, 24],
                'momenta': ['-k1', 'k0-k2+p0', '-k0+k1+k2-p0'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 3, 13],
                'indices': [17, 5, 26],
                'momenta': ['-k2+p2', '-p2', 'k2'],
                'vertex_id': 0},
            10: {'PDGs': [-1, 22, 1],
                 'edge_ids': [14, 4, 11],
                 'indices': [27, 7, 22],
                 'momenta': ['k0-k1-k2+p0+p1', '-p0-p1+p2', '-k0+k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 1, 7],
                 'indices': [25, 1, 14],
                 'momenta': ['-k2', 'p0', 'k2-p0'],
                 'vertex_id': 0},
            12: {'PDGs': [-1, 22, 1],
                 'edge_ids': [12, 2, 14],
                 'indices': [23, 3, 28],
                 'momenta': ['k0-k1-k2+p0', 'p1', '-k0+k1+k2-p0-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(330,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(331,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(332,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(333,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': '-k1+k2-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1+k2-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [11, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': 'k1-k2+p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+k2-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 10]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': 'k2-p2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 7]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': 'k2-p1',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 12]},
            13: {'PDG': 1,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', 'k1-k2+p1', 'k0-k1+k2-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0+k1-k2+p2', '-k1+k2-p2', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k1', 'k1-k2+p2', 'k2-p2'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [12, 6, 10],
                'indices': [23, 12, 20],
                'momenta': ['-k2+p1', '-k1+k2-p1', 'k1'],
                'vertex_id': 0},
            9: {'PDGs': [-1, 22, 1],
                'edge_ids': [11, 3, 13],
                'indices': [21, 5, 26],
                'momenta': ['-k2+p2', '-p2', 'k2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 4, 9],
                 'indices': [27, 7, 18],
                 'momenta': ['-k0+k1-k2+p0+p1', '-p0-p1+p2', 'k0-k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 1, 14],
                 'indices': [13, 1, 28],
                 'momenta': ['-k0+k1-k2+p1', 'p0', 'k0-k1+k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-1, 22, 1],
                 'edge_ids': [13, 2, 12],
                 'indices': [25, 3, 24],
                 'momenta': ['-k2', 'p1', 'k2-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(338,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(339,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(340,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(341,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0+k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [12, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1-p0-p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 11]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': 'k1+k2-p0-p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 7]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': 'k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 10]},
            13: {'PDG': 1,
                 'indices': [25, 26],
                 'momentum': 'k1+k2-p0-p1+p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [10, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0+k1-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', '-k1', 'k0+k1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0-k1+p0+p1', 'k1-p0-p1', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k2', '-k1+p0+p1', 'k1+k2-p0-p1'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [12, 6, 10],
                'indices': [23, 12, 20],
                'momenta': ['-k1-k2', 'k1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-1, 22, 1],
                'edge_ids': [11, 3, 13],
                'indices': [21, 5, 26],
                'momenta': ['-k1-k2+p0+p1', '-p2', 'k1+k2-p0-p1+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-1, 22, 1],
                 'edge_ids': [13, 4, 12],
                 'indices': [25, 7, 24],
                 'momenta': ['-k1-k2+p0+p1-p2', '-p0-p1+p2', 'k1+k2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 9],
                 'indices': [27, 1, 18],
                 'momenta': ['-k0-k1+p1', 'p0', 'k0+k1-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 2, 14],
                 'indices': [13, 3, 28],
                 'momenta': ['-k0-k1', 'p1', 'k0+k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(342,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(343,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(344,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(345,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0+k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [12, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+p0+p1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0+k1-p0-p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 11]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': 'k1+k2-p0-p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': 'k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            13: {'PDG': 1,
                 'indices': [25, 26],
                 'momentum': 'k1+k2-p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0+k1-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', '-k1', 'k0+k1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0-k1+p0+p1', 'k1-p0-p1', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k2', '-k1+p0+p1', 'k1+k2-p0-p1'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [12, 6, 10],
                'indices': [23, 12, 20],
                'momenta': ['-k1-k2', 'k1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-1, 22, 1],
                'edge_ids': [13, 3, 12],
                'indices': [25, 5, 24],
                'momenta': ['-k1-k2+p2', '-p2', 'k1+k2'],
                'vertex_id': 0},
            10: {'PDGs': [-1, 22, 1],
                 'edge_ids': [11, 4, 13],
                 'indices': [21, 7, 26],
                 'momenta': ['-k1-k2+p0+p1', '-p0-p1+p2', 'k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 9],
                 'indices': [27, 1, 18],
                 'momenta': ['-k0-k1+p1', 'p0', 'k0+k1-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 2, 14],
                 'indices': [13, 3, 28],
                 'momenta': ['-k0-k1', 'p1', 'k0+k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(346,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(347,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(348,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(349,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': '-k1+k2-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1+k2-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [11, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': 'k1-k2+p0+p1-p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+k2-p0-p1+p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 9]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2-p0-p1+p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [10, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': 'k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': 'k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 10]},
            13: {'PDG': 1,
                 'indices': [25, 26],
                 'momentum': 'k1+p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 8]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [9, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', 'k1-k2+p1', 'k0-k1+k2-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0+k1-k2+p0+p1-p2', '-k1+k2-p0-p1+p2', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['-k1', 'k1-k2+p0+p1-p2', 'k2-p0-p1+p2'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [12, 6, 13],
                'indices': [23, 12, 26],
                'momenta': ['-k2', '-k1+k2-p1', 'k1+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [14, 3, 9],
                'indices': [27, 5, 18],
                'momenta': ['-k0+k1-k2+p0+p1', '-p2', 'k0-k1+k2-p0-p1+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-1, 22, 1],
                 'edge_ids': [10, 4, 12],
                 'indices': [19, 7, 24],
                 'momenta': ['-k2+p0+p1-p2', '-p0-p1+p2', 'k2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 1, 14],
                 'indices': [13, 1, 28],
                 'momenta': ['-k0+k1-k2+p1', 'p0', 'k0-k1+k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-1, 22, 1],
                 'edge_ids': [13, 2, 11],
                 'indices': [25, 3, 22],
                 'momenta': ['-k1-p1', 'p1', 'k1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(358,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(359,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(360,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(361,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': '-k1+k2-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1+k2-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [11, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': 'k1-k2+p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1+k2-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 10]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2-p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [9, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': 'k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            12: {'PDG': 1,
                 'indices': [23, 24],
                 'momentum': 'k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            13: {'PDG': 1,
                 'indices': [25, 26],
                 'momentum': 'k1+p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 8]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', 'k1-k2+p1', 'k0-k1+k2-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0+k1-k2+p2', '-k1+k2-p2', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['-k1', 'k1-k2+p2', 'k2-p2'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [12, 6, 13],
                'indices': [23, 12, 26],
                'momenta': ['-k2', '-k1+k2-p1', 'k1+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-1, 22, 1],
                'edge_ids': [10, 3, 12],
                'indices': [19, 5, 24],
                'momenta': ['-k2+p2', '-p2', 'k2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 4, 9],
                 'indices': [27, 7, 18],
                 'momenta': ['-k0+k1-k2+p0+p1', '-p0-p1+p2', 'k0-k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 1, 14],
                 'indices': [13, 1, 28],
                 'momenta': ['-k0+k1-k2+p1', 'p0', 'k0-k1+k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-1, 22, 1],
                 'edge_ids': [13, 2, 11],
                 'indices': [25, 3, 22],
                 'momenta': ['-k1-p1', 'p1', 'k1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(362,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(363,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(364,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(365,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1-k2-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 1,
                'indices': [13, 14],
                'momentum': 'k0+k1-k2-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [11, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+k2+p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 1,
                'indices': [17, 18],
                'momentum': 'k0+k1-k2-p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 10]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2+p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 9]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [12, 7]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [9, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k1-p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [8, 12]},
            14: {'PDG': 1,
                 'indices': [27, 28],
                 'momentum': 'k0+k1-k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', '-k1+k2+p1', 'k0+k1-k2-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0-k1+k2+p2', 'k1-k2-p2', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k2-p2', '-k1+k2+p2', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [13, 6, 12],
                'indices': [25, 12, 24],
                'momenta': ['-k1+p1', 'k1-k2-p1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [12, 3, 10],
                'indices': [23, 5, 20],
                'momenta': ['-k2', '-p2', 'k2+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-1, 22, 1],
                 'edge_ids': [14, 4, 9],
                 'indices': [27, 7, 18],
                 'momenta': ['-k0-k1+k2+p0+p1', '-p0-p1+p2', 'k0+k1-k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-1, 22, 1],
                 'edge_ids': [7, 1, 14],
                 'indices': [13, 1, 28],
                 'momenta': ['-k0-k1+k2+p1', 'p0', 'k0+k1-k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 13],
                 'indices': [21, 3, 26],
                 'momenta': ['-k1', 'p1', 'k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(496,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(497,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(498,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(499,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1-k2-p1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 1,
                'indices': [13, 14],
                'momentum': 'k0+k1-k2-p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [11, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1+k2+p0+p1-p2',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 1,
                'indices': [17, 18],
                'momentum': 'k0+k1-k2-p0-p1+p2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 9]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2+p0+p1-p2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 10]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [12, 7]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [10, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k1-p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [8, 12]},
            14: {'PDG': 1,
                 'indices': [27, 28],
                 'momentum': 'k0+k1-k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [9, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['-k0', '-k1+k2+p1', 'k0+k1-k2-p1'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k0-k1+k2+p0+p1-p2', 'k1-k2-p0-p1+p2', 'k0'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 11],
                'indices': [19, 16, 22],
                'momenta': ['-k2-p0-p1+p2', '-k1+k2+p0+p1-p2', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [13, 6, 12],
                'indices': [25, 12, 24],
                'momenta': ['-k1+p1', 'k1-k2-p1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-1, 22, 1],
                'edge_ids': [14, 3, 9],
                'indices': [27, 5, 18],
                'momenta': ['-k0-k1+k2+p0+p1', '-p2', 'k0+k1-k2-p0-p1+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 4, 10],
                 'indices': [23, 7, 20],
                 'momenta': ['-k2', '-p0-p1+p2', 'k2+p0+p1-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-1, 22, 1],
                 'edge_ids': [7, 1, 14],
                 'indices': [13, 1, 28],
                 'momenta': ['-k0-k1+k2+p1', 'p0', 'k0+k1-k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 2, 13],
                 'indices': [21, 3, 26],
                 'momenta': ['-k1', 'p1', 'k1-p1'],
                 'vertex_id': 0}},
  'overall_factor': 'NumeratorDependentGrouping(508,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(509,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(510,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))+NumeratorDependentGrouping(511,1,AutG(1)^-1*ExternalFermionOrderingSign(1)*NumeratorIndependentSymmetryGrouping(2))'}]
graph_names=["GL187","GL188","GL333","GL338","GL342","GL346","GL359","GL363","GL496","GL508"]