graphs=[{'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 11]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [9, 6]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': '-k1+k2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k0-k1+p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [10, 9]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k0-k1+p0+p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+p0',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 8, 9],
                'indices': [9, 15, 18],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k1-k2', '-k1', 'k2'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 6, 11],
                'indices': [19, 12, 22],
                'momenta': ['-k2', 'k1', '-k1+k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [9, 3, 12],
                'indices': [17, 5, 24],
                'momenta': ['-k0+k1', '-p2', 'k0-k1+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 4, 13],
                 'indices': [23, 7, 26],
                 'momenta': ['-k0+k1-p2', '-p0-p1+p2', 'k0-k1+p0+p1'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 7],
                 'indices': [27, 1, 14],
                 'momenta': ['-k0+k1-p0', 'p0', 'k0-k1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 2, 14],
                 'indices': [25, 3, 28],
                 'momenta': ['-k0+k1-p0-p1', 'p1', 'k0-k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k0-k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 11]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k0-k1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [10, 6]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': '-k1+k2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k0-k1+p0+p1-p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k0-k1+p0+p1',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k0-k1+p0',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [7, 6, 5],
                'indices': [13, 11, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 8, 9],
                'indices': [9, 15, 18],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k1-k2', '-k1', 'k2'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 6, 11],
                'indices': [19, 12, 22],
                'momenta': ['-k2', 'k1', '-k1+k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [12, 3, 13],
                'indices': [23, 5, 26],
                'momenta': ['-k0+k1-p0-p1+p2', '-p2', 'k0-k1+p0+p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 4, 12],
                 'indices': [17, 7, 24],
                 'momenta': ['-k0+k1', '-p0-p1+p2', 'k0-k1+p0+p1-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 7],
                 'indices': [27, 1, 14],
                 'momenta': ['-k0+k1-p0', 'p0', 'k0-k1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 2, 14],
                 'indices': [25, 3, 28],
                 'momenta': ['-k0+k1-p0-p1', 'p1', 'k0-k1+p0'],
                 'vertex_id': 0}},
  'overall_factor': '4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': '-k0+k2-p0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k2-p0',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [12, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k0',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2-p0',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 11]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': '-k0+k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k2-p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [11, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['k0-k2+p0', '-k0', 'k2-p0'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k2+p0', 'k0', '-k0+k2-p0'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k0-k1', '-k0', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 6, 11],
                'indices': [19, 12, 22],
                'momenta': ['-k1', 'k0', '-k0+k1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [12, 3, 13],
                'indices': [23, 5, 26],
                'momenta': ['-k2+p2', '-p2', 'k2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 4, 12],
                 'indices': [27, 7, 24],
                 'momenta': ['-k2+p0+p1', '-p0-p1+p2', 'k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 1, 9],
                 'indices': [25, 1, 18],
                 'momenta': ['-k2', 'p0', 'k2-p0'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 2, 14],
                 'indices': [13, 3, 28],
                 'momenta': ['-k2+p0', 'p1', 'k2-p0-p1'],
                 'vertex_id': 0}},
  'overall_factor': '4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 6,
                'indices': [9, 10],
                'momentum': '-k0+k2+p1',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [5, 6]},
            6: {'PDG': 21,
                'indices': [11, 12],
                'momentum': 'k0',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 8]},
            7: {'PDG': 6,
                'indices': [13, 14],
                'momentum': 'k2+p1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [12, 5]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k0',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2+p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [6, 11]},
            10: {'PDG': 1,
                 'indices': [19, 20],
                 'momentum': 'k1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [8, 7]},
            11: {'PDG': 1,
                 'indices': [21, 22],
                 'momentum': '-k0+k1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [7, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k2+p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [10, 9]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 12]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k2+p0+p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-6, 21, 6],
                'edge_ids': [5, 6, 7],
                'indices': [9, 11, 14],
                'momenta': ['k0-k2-p1', '-k0', 'k2+p1'],
                'vertex_id': 0},
            6: {'PDGs': [-6, 21, 6],
                'edge_ids': [9, 8, 5],
                'indices': [17, 15, 10],
                'momenta': ['-k2-p1', 'k0', '-k0+k2+p1'],
                'vertex_id': 0},
            7: {'PDGs': [-1, 21, 1],
                'edge_ids': [11, 8, 10],
                'indices': [21, 16, 20],
                'momenta': ['k0-k1', '-k0', 'k1'],
                'vertex_id': 0},
            8: {'PDGs': [-1, 21, 1],
                'edge_ids': [10, 6, 11],
                'indices': [19, 12, 22],
                'momenta': ['-k1', 'k0', '-k0+k1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 12],
                'indices': [25, 5, 24],
                'momenta': ['-k2', '-p2', 'k2+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 4, 14],
                 'indices': [23, 7, 28],
                 'momenta': ['-k2-p2', '-p0-p1+p2', 'k2+p0+p1'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 9],
                 'indices': [27, 1, 18],
                 'momenta': ['-k2-p0-p1', 'p0', 'k2+p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [7, 2, 13],
                 'indices': [13, 3, 26],
                 'momenta': ['-k2-p1', 'p1', 'k2'],
                 'vertex_id': 0}},
  'overall_factor': '4'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [10, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': '-k1+k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 11]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': '-k1+k2+p0+p1',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [12, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2+p0+p1-p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': '-k1+k2+p0',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [11, 12]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['k1-k2', '-k1', 'k2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [11, 7, 12],
                'indices': [21, 14, 24],
                'momenta': ['-k2-p0-p1', 'k1', '-k1+k2+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 11],
                'indices': [25, 5, 22],
                'momenta': ['-k2-p0-p1+p2', '-p2', 'k2+p0+p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 4, 13],
                 'indices': [17, 7, 26],
                 'momenta': ['-k2', '-p0-p1+p2', 'k2+p0+p1-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 1, 10],
                 'indices': [27, 1, 20],
                 'momenta': ['k1-k2-p0', 'p0', '-k1+k2'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 2, 14],
                 'indices': [23, 3, 28],
                 'momenta': ['k1-k2-p0-p1', 'p1', '-k1+k2+p0'],
                 'vertex_id': 0}},
  'overall_factor': '2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [10, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': '-k1+k2',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2+p0+p1',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': '-k1+k2+p0+p1',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [11, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2+p0+p1-p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': '-k1+k2+p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [12, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['k1-k2', '-k1', 'k2'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [11, 7, 12],
                'indices': [21, 14, 24],
                'momenta': ['-k2-p0-p1', 'k1', '-k1+k2+p0+p1'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 11],
                'indices': [25, 5, 22],
                'momenta': ['-k2-p0-p1+p2', '-p2', 'k2+p0+p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 4, 13],
                 'indices': [17, 7, 26],
                 'momenta': ['-k2', '-p0-p1+p2', 'k2+p0+p1-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 1, 14],
                 'indices': [23, 1, 28],
                 'momenta': ['k1-k2-p0-p1', 'p0', '-k1+k2+p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 2, 10],
                 'indices': [27, 3, 20],
                 'momenta': ['k1-k2-p1', 'p1', '-k1+k2'],
                 'vertex_id': 0}},
  'overall_factor': '2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k2+p0',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [11, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': '-k1+k2+p0',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2+p2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [8, 9]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': '-k1+k2+p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [10, 8]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 11]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': '-k1+k2+p0+p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [12, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['k1-k2-p0', '-k1', 'k2+p0'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [11, 7, 12],
                'indices': [21, 14, 24],
                'momenta': ['-k2-p2', 'k1', '-k1+k2+p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 11],
                'indices': [25, 5, 22],
                'momenta': ['-k2', '-p2', 'k2+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [12, 4, 14],
                 'indices': [23, 7, 28],
                 'momenta': ['k1-k2-p2', '-p0-p1+p2', '-k1+k2+p0+p1'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 1, 13],
                 'indices': [17, 1, 26],
                 'momenta': ['-k2-p0', 'p0', 'k2'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 2, 10],
                 'indices': [27, 3, 20],
                 'momenta': ['k1-k2-p0-p1', 'p1', '-k1+k2+p0'],
                 'vertex_id': 0}},
  'overall_factor': '2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k1+k2-p1',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [11, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2-p1',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2-p2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k1+k2-p2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 10]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [12, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k1+k2-p0-p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [10, 11]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['-k2+p1', '-k1', 'k1+k2-p1'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [12, 7, 11],
                'indices': [23, 14, 22],
                'momenta': ['-k1-k2+p2', 'k1', 'k2-p2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 3, 13],
                'indices': [21, 5, 26],
                'momenta': ['-k2+p2', '-p2', 'k2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 4, 12],
                 'indices': [27, 7, 24],
                 'momenta': ['-k1-k2+p0+p1', '-p0-p1+p2', 'k1+k2-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 1, 14],
                 'indices': [17, 1, 28],
                 'momenta': ['-k1-k2+p1', 'p0', 'k1+k2-p0-p1'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 2, 10],
                 'indices': [25, 3, 20],
                 'momenta': ['-k2', 'p1', 'k2-p1'],
                 'vertex_id': 0}},
  'overall_factor': '2'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k1+k2+p0',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [11, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2+p0',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [9, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 11]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2+p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [10, 9]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k2+p0+p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [12, 10]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['-k2-p0', '-k1', 'k1+k2+p0'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [12, 7, 11],
                'indices': [23, 14, 22],
                'momenta': ['-k1-k2', 'k1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [11, 3, 13],
                'indices': [21, 5, 26],
                'momenta': ['-k2', '-p2', 'k2+p2'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [13, 4, 14],
                 'indices': [25, 7, 28],
                 'momenta': ['-k2-p2', '-p0-p1+p2', 'k2+p0+p1'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 1, 12],
                 'indices': [17, 1, 24],
                 'momenta': ['-k1-k2-p0', 'p0', 'k1+k2'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 2, 10],
                 'indices': [27, 3, 20],
                 'momenta': ['-k2-p0-p1', 'p1', 'k2+p0'],
                 'vertex_id': 0}},
  'overall_factor': '8'},
 {'edges': {1: {'PDG': 22,
                'indices': [1],
                'momentum': 'p0',
                'name': 'p1',
                'type': 'in',
                'vertices': [2, 11]},
            2: {'PDG': 22,
                'indices': [3],
                'momentum': 'p1',
                'name': 'p2',
                'type': 'in',
                'vertices': [1, 12]},
            3: {'PDG': 22,
                'indices': [5],
                'momentum': 'p2',
                'name': 'p3',
                'type': 'out',
                'vertices': [9, 4]},
            4: {'PDG': 22,
                'indices': [7],
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'type': 'out',
                'vertices': [10, 3]},
            5: {'PDG': 1,
                'indices': [9, 10],
                'momentum': 'k0',
                'name': 'q1',
                'type': 'virtual',
                'vertices': [6, 5]},
            6: {'PDG': 1,
                'indices': [11, 12],
                'momentum': 'k0-k1',
                'name': 'q2',
                'type': 'virtual',
                'vertices': [5, 6]},
            7: {'PDG': 21,
                'indices': [13, 14],
                'momentum': 'k1',
                'name': 'q3',
                'type': 'virtual',
                'vertices': [5, 8]},
            8: {'PDG': 21,
                'indices': [15, 16],
                'momentum': '-k1',
                'name': 'q4',
                'type': 'virtual',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'indices': [17, 18],
                'momentum': 'k1+k2+p0',
                'name': 'q5',
                'type': 'virtual',
                'vertices': [11, 7]},
            10: {'PDG': 6,
                 'indices': [19, 20],
                 'momentum': 'k2+p0',
                 'name': 'q6',
                 'type': 'virtual',
                 'vertices': [7, 12]},
            11: {'PDG': 6,
                 'indices': [21, 22],
                 'momentum': 'k2',
                 'name': 'q7',
                 'type': 'virtual',
                 'vertices': [10, 8]},
            12: {'PDG': 6,
                 'indices': [23, 24],
                 'momentum': 'k1+k2',
                 'name': 'q8',
                 'type': 'virtual',
                 'vertices': [8, 11]},
            13: {'PDG': 6,
                 'indices': [25, 26],
                 'momentum': 'k2+p0+p1-p2',
                 'name': 'q9',
                 'type': 'virtual',
                 'vertices': [9, 10]},
            14: {'PDG': 6,
                 'indices': [27, 28],
                 'momentum': 'k2+p0+p1',
                 'name': 'q10',
                 'type': 'virtual',
                 'vertices': [12, 9]}},
  'nodes': {1: {'PDGs': [22],
                'edge_ids': [2],
                'indices': [3],
                'momenta': ['-p1'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [1],
                'indices': [1],
                'momenta': ['-p0'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [4],
                'indices': [7],
                'momenta': ['p0+p1-p2'],
                'vertex_id': -2},
            4: {'PDGs': [22],
                'edge_ids': [3],
                'indices': [5],
                'momenta': ['p2'],
                'vertex_id': -2},
            5: {'PDGs': [-1, 21, 1],
                'edge_ids': [6, 7, 5],
                'indices': [11, 13, 10],
                'momenta': ['-k0+k1', '-k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [-1, 21, 1],
                'edge_ids': [5, 8, 6],
                'indices': [9, 15, 12],
                'momenta': ['-k0', 'k1', 'k0-k1'],
                'vertex_id': 0},
            7: {'PDGs': [-6, 21, 6],
                'edge_ids': [10, 8, 9],
                'indices': [19, 16, 18],
                'momenta': ['-k2-p0', '-k1', 'k1+k2+p0'],
                'vertex_id': 0},
            8: {'PDGs': [-6, 21, 6],
                'edge_ids': [12, 7, 11],
                'indices': [23, 14, 22],
                'momenta': ['-k1-k2', 'k1', 'k2'],
                'vertex_id': 0},
            9: {'PDGs': [-6, 22, 6],
                'edge_ids': [13, 3, 14],
                'indices': [25, 5, 28],
                'momenta': ['-k2-p0-p1+p2', '-p2', 'k2+p0+p1'],
                'vertex_id': 0},
            10: {'PDGs': [-6, 22, 6],
                 'edge_ids': [11, 4, 13],
                 'indices': [21, 7, 26],
                 'momenta': ['-k2', '-p0-p1+p2', 'k2+p0+p1-p2'],
                 'vertex_id': 0},
            11: {'PDGs': [-6, 22, 6],
                 'edge_ids': [9, 1, 12],
                 'indices': [17, 1, 24],
                 'momenta': ['-k1-k2-p0', 'p0', 'k1+k2'],
                 'vertex_id': 0},
            12: {'PDGs': [-6, 22, 6],
                 'edge_ids': [14, 2, 10],
                 'indices': [27, 3, 20],
                 'momenta': ['-k2-p0-p1', 'p1', 'k2+p0'],
                 'vertex_id': 0}},
  'overall_factor': '8'}]
graph_names=["GL664","GL668","GL674","GL679","GL944","GL946","GL952","GL954","GL956","GL964"]