General:
  debug: 0
  use_ltd: false
  load_compiled_cff: true
  load_compiled_numerator: true
  joint_numerator_eval: true
  amplitude_prefactor:
    re: 0.0
    im: 1.0
  load_compiled_separate_orientations: false
  force_orientations: null
Integrand:
  type: gamma_loop
Kinematics:
  e_cm: 3.0
  externals:
    type: constant
    data:
      momenta:
      - - 0.0
        - 0.0
        - 0.0
        - 0.6324555320336759
      - - 0.0
        - -0.6970921746799343
        - 0.0
        - -0.5138701197773616
      - dependent
      helicities:
      - 1
      - 1
      - 1
      - 1
Integrator:
  n_bins: 16
  bin_number_evolution: null
  min_samples_for_update: 100
  n_start: 1000000
  n_increase: 0
  n_max: 100000000
  integrated_phase: real
  discrete_dim_learning_rate: 0.0
  continuous_dim_learning_rate: 0.0
  train_on_avg: false
  show_max_wgt_info: false
  max_prob_ratio: 1000.0
  seed: 0
Observables: []
Selectors: []
Stability:
  rotation_axis:
  - type: euler_angles
    alpha: 0.1
    beta: 0.45
    gamma: 0.88
  rotate_numerator: false
  levels:
  - precision: Double
    required_precision_for_re: 1e-7
    required_precision_for_im: 1e-7
    escalate_for_large_weight_threshold: 0.9
  - precision: Quad
    required_precision_for_re: 1e-10
    required_precision_for_im: 1e-10
    escalate_for_large_weight_threshold: -1.0
sampling:
  type: default
  mode: spherical
  mapping: linear
  b: 1.0
  input_rescaling:
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  shifts:
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
subtraction:
  local_ct_settings:
    dampen_integrable_singularity:
      type: exponential
    uv_localisation:
      sliver_width: 10.0
      dynamic_width: false
      gaussian_width: 1.0
  integrated_ct_settings:
    range:
      type: infinite
      h_function_settings:
        function: poly_exponential
        sigma: 1.0
        enabled_dampening: true
        power: null
  overlap_settings:
    force_global_center: null
    check_global_center: true
    try_origin: false
    try_origin_all_lmbs: false
